### ISSUE TITLE
文件下载总是在40%左右卡死

### ISSUE THREAD

**Issue by Axinyp** [proxyee-down-org/proxyee-down#1004]
### 
![image](https://user-images.githubusercontent.com/42953066/47834001-8e9b0a80-ddd8-11e8-9246-e30705021eed.png)

**Comment by monkeyWie** [comment]
尝试刷新下载链接：https://github.com/proxyee-down-org/proxyee-down/wiki/%E5%88%B7%E6%96%B0%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5
