### ISSUE TITLE
能不能更新个JDK11能用的版本

### ISSUE THREAD

**Issue by aniceking** [proxyee-down-org/proxyee-down#1005]

**Comment by sxft1978** [comment]
你还得下载个openjfx11,指定路径，运行还得加上插件名，我就再ubuntu18.04运行了

**Comment by sxft1978** [comment]
运行命令：java -jar --module-path $PATH_TO_FX --add-modules=javafx.controls,javafx.fxml,javafx.base,javafx.graphics,javafx.media,javafx.swing,javafx.web /home/你的路径/proxyee-down-main.jar
