### ISSUE TITLE
3.31 源码编译失败

### ISSUE THREAD

**Issue by bcc290786** [proxyee-down-org/proxyee-down#1008]
### 问题描述(必要)
源码编译失败
### 版本号(必要)
3.31
### 操作系统(必要)
Win10 1803 x64, java version "1.8.0_181", Apache Maven 3.6.0
### 相关日志
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.pdown.gui:main:jar:3.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-resources-plugin is missing. @ org.pdown.gui:main:[unknown-version], D:\code_server\pdown30\main\pom.xml, line 94, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] -------------------------< org.pdown.gui:main >-------------------------
[INFO] Building main 3.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ main ---
[INFO] Deleting D:\code_server\pdown30\main\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ main ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 28 resources
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ main ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 41 source files to D:\code_server\pdown30\main\target\classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/extension/mitm/util/ExtensionCertUtil.java:[20,25] sun.security.x509.X500Name is internal proprietary API and may be removed in a future release
[WARNING] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/extension/mitm/util/ExtensionCertUtil.java:[73,28] sun.security.x509.X500Name is internal proprietary API and may be removed in a future release
[WARNING] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/util/ConfigUtil.java: Some input files use unchecked or unsafe operations.
[WARNING] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/util/ConfigUtil.java: Recompile with -Xlint:unchecked for details.
[INFO] 4 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[15,33] cannot find symbol
  symbol:   class HttpDownRestCallback
  location: package org.pdown.rest.controller
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[16,29] cannot find symbol
  symbol:   class DownInfo
  location: package org.pdown.rest.entity
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[22,42] cannot find symbol
  symbol: class HttpDownRestCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/DownApplication.java:[52,33] cannot find symbol
  symbol:   class HttpDownRestCallback
  location: package org.pdown.rest.controller
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/extension/mitm/intercept/ScriptIntercept.java:[51,34] cannot find symbol
  symbol:   method getUrl(io.netty.handler.codec.http.HttpRequest)
  location: class org.pdown.core.util.HttpDownUtil
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/http/controller/NativeController.java:[374,34] cannot find symbol
  symbol:   method isWindowsXP()
  location: class org.pdown.core.util.OsUtil
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[26,3] method does not override or implement a method from a supertype
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[28,5] cannot find symbol
  symbol:   variable super
  location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[31,3] method does not override or implement a method from a supertype
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[33,5] cannot find symbol
  symbol:   variable super
  location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[36,3] method does not override or implement a method from a supertype
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[38,5] cannot find symbol
  symbol:   variable super
  location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[39,5] cannot find symbol
  symbol:   class DownInfo
  location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[39,25] cannot find symbol
  symbol:   method findDownInfo(org.pdown.core.boot.HttpDownBootstrap)
  location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[52,102] cannot find symbol
  symbol:   method getUrl(org.pdown.core.entity.HttpRequestInfo)
  location: class org.pdown.core.util.HttpDownUtil
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[71,3] method does not override or implement a method from a supertype
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[73,5] cannot find symbol
  symbol:   variable super
  location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[76,3] method does not override or implement a method from a supertype
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[78,5] cannot find symbol
  symbol:   variable super
  location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/DownApplication.java:[66,55] cannot find symbol
  symbol:   method isWindowsXP()
  location: class org.pdown.core.util.OsUtil
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/DownApplication.java:[100,16] cannot find symbol
  symbol:   method isWindowsXP()
  location: class org.pdown.core.util.OsUtil
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/DownApplication.java:[130,5] cannot find symbol
  symbol:   variable HttpDownRestCallback
  location: class org.pdown.gui.DownApplication
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/DownApplication.java:[330,15] cannot find symbol
  symbol:   method isWindowsXP()
  location: class org.pdown.core.util.OsUtil
[INFO] 23 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.482 s
[INFO] Finished at: 2018-11-02T15:20:38+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project main: Compilation failure: Compilation failure:
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[15,33] cannot find symbol
[ERROR]   symbol:   class HttpDownRestCallback
[ERROR]   location: package org.pdown.rest.controller
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[16,29] cannot find symbol
[ERROR]   symbol:   class DownInfo
[ERROR]   location: package org.pdown.rest.entity
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[22,42] cannot find symbol
[ERROR]   symbol: class HttpDownRestCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/DownApplication.java:[52,33] cannot find symbol
[ERROR]   symbol:   class HttpDownRestCallback
[ERROR]   location: package org.pdown.rest.controller
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/extension/mitm/intercept/ScriptIntercept.java:[51,34] cannot find symbol
[ERROR]   symbol:   method getUrl(io.netty.handler.codec.http.HttpRequest)
[ERROR]   location: class org.pdown.core.util.HttpDownUtil
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/http/controller/NativeController.java:[374,34] cannot find symbol
[ERROR]   symbol:   method isWindowsXP()
[ERROR]   location: class org.pdown.core.util.OsUtil
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[26,3] method does not override or implement a method from a supertype
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[28,5] cannot find symbol
[ERROR]   symbol:   variable super
[ERROR]   location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[31,3] method does not override or implement a method from a supertype
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[33,5] cannot find symbol
[ERROR]   symbol:   variable super
[ERROR]   location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[36,3] method does not override or implement a method from a supertype
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[38,5] cannot find symbol
[ERROR]   symbol:   variable super
[ERROR]   location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[39,5] cannot find symbol
[ERROR]   symbol:   class DownInfo
[ERROR]   location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[39,25] cannot find symbol
[ERROR]   symbol:   method findDownInfo(org.pdown.core.boot.HttpDownBootstrap)
[ERROR]   location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[52,102] cannot find symbol
[ERROR]   symbol:   method getUrl(org.pdown.core.entity.HttpRequestInfo)
[ERROR]   location: class org.pdown.core.util.HttpDownUtil
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[71,3] method does not override or implement a method from a supertype
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[73,5] cannot find symbol
[ERROR]   symbol:   variable super
[ERROR]   location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[76,3] method does not override or implement a method from a supertype
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/rest/HttpDownAppCallback.java:[78,5] cannot find symbol
[ERROR]   symbol:   variable super
[ERROR]   location: class org.pdown.gui.rest.HttpDownAppCallback
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/DownApplication.java:[66,55] cannot find symbol
[ERROR]   symbol:   method isWindowsXP()
[ERROR]   location: class org.pdown.core.util.OsUtil
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/DownApplication.java:[100,16] cannot find symbol
[ERROR]   symbol:   method isWindowsXP()
[ERROR]   location: class org.pdown.core.util.OsUtil
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/DownApplication.java:[130,5] cannot find symbol
[ERROR]   symbol:   variable HttpDownRestCallback
[ERROR]   location: class org.pdown.gui.DownApplication
[ERROR] /D:/code_server/pdown30/main/src/main/java/org/pdown/gui/DownApplication.java:[330,15] cannot find symbol
[ERROR]   symbol:   method isWindowsXP()
[ERROR]   location: class org.pdown.core.util.OsUtil
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by monkeyWie** [comment]
依赖包已经上传到maven仓库了，更新下pdown-core和pdown-rest

**Comment by bcc290786** [comment]
可以了 感谢大神~
另外想问下 4.0会改用go写吗?

**Comment by monkeyWie** [comment]
有考虑过用go写，不过怕是没这么多时间和精力了

**Comment by sxft1978** [comment]
如何更新pdown-core和pdown-rest
