### ISSUE TITLE
v.3.32 二级代理无法关闭和二级代理信息丢失

### ISSUE THREAD

**Issue by TomLao** [proxyee-down-org/proxyee-down#1017]
### 相关截图:
1. 开启sock5代理，并填写设置。
![image](https://user-images.githubusercontent.com/24352942/47948433-3d238480-df6c-11e8-9b0d-6135d1ec2986.png)

2. 关闭二级代理。
![image](https://user-images.githubusercontent.com/24352942/47948446-680dd880-df6c-11e8-8de1-0d176f647f39.png)

3. 访问网页，看到依旧在使用代理。

4. 重启proxyee，看到二级代理任然处于开启状态。上次的关闭操作并没有成功执行并保存。
![image](https://user-images.githubusercontent.com/24352942/47948503-6264c280-df6d-11e8-8892-0f3dad71f143.png)

5. 尝试在关闭二级代理的状态下，同时关闭启动弹窗：
![image](https://user-images.githubusercontent.com/24352942/47948611-d2277d00-df6e-11e8-973e-964aaaa9ab3b.png)

6. 重启proxyee

7. 此时二级代理成功关闭。***估计是二级代理的滑动按钮没有设置保存状态。***
![image](https://user-images.githubusercontent.com/24352942/47948601-6c3af580-df6e-11e8-9945-db774b5daddd.png)

8. 但再次开启二级代理按钮，看到上次设置的信息被清除。
![image](https://user-images.githubusercontent.com/24352942/47948593-53cadb00-df6e-11e8-82bb-5ae14fd38fc5.png)

### 相关日志：上传log文件，但显示为空。不知这样的反馈合不合规范？

**Comment by note286** [comment]
@TomLao  你试试把mian里的pdown.cfg最后改为"proxyConfig":null应该就可以关闭二级代理了吧。

**Comment by monkeyWie** [comment]
3.4版本已经修复
