### ISSUE TITLE
无法下载https://github.com/opengapps/arm64/releases上的链接

### ISSUE THREAD

**Issue by ggshuini** [proxyee-down-org/proxyee-down#1019]
### 相关截图
![2018-11-03-14-27-40](https://user-images.githubusercontent.com/32868716/47948911-b626da00-df74-11e8-9500-675612f02e05.png)

**Comment by 14SHIKE** [comment]
![1 ceshi](https://user-images.githubusercontent.com/37872513/47965408-f2942c00-e081-11e8-8a9f-f5ff0e4ac33a.gif)
这里正常
![2 ceshi](https://user-images.githubusercontent.com/37872513/47965436-4acb2e00-e082-11e8-9375-4c710cb86ded.gif)

**Comment by monkeyWie** [comment]
github的文件服务器经常被墙的，所以你懂的
