### ISSUE TITLE
B站PD下载标识消失问题，需要手动清理浏览器数据才会再次出现

### ISSUE THREAD

**Issue by 14SHIKE** [proxyee-down-org/proxyee-down#1024]
版本3.32
扩展最新
浏览器谷歌，重新安装的浏览器
打开新安装的浏览器，输入链接
[https://www.bilibili.com/video/av35199206/?p=3](url)
出现PD下载，点击下载后，再打开别的链接，PD下载标识消失，ctrl+shift+del 清理浏览器数据后刷新链接，PD下载标识出现，再打开别的链接，PD下载标识消失
另外不知道是不是连接数调的较高的原因(90-100)，在下载1080视频时容易出现下载状态未知或者失败的情况，调低连接数后情况好多了
通过链接创建任务倒是没有问题
下载速度很快，我是4G热点下载，速度5M/S+

![bili](https://user-images.githubusercontent.com/37872513/47965319-764d1900-e080-11e8-98fc-556e906c09a5.gif)
![20181104214156](https://user-images.githubusercontent.com/37872513/47965331-b3b1a680-e080-11e8-931f-ccdf50730376.png)
![20181104214140](https://user-images.githubusercontent.com/37872513/47965332-b3b1a680-e080-11e8-8eb6-badbf33cb703.png)
![20181104214114](https://user-images.githubusercontent.com/37872513/47965333-b44a3d00-e080-11e8-84b9-0de38b0d3133.png)

**Comment by monkeyWie** [comment]
可能是还在加载，不需要清缓存的 等一等或者刷新下页面就可以
