### ISSUE TITLE
不可以更改默认下载地址，一打开要那个选择文件夹的窗口直接卡死崩溃

### ISSUE THREAD

**Issue by huangjiajin** [proxyee-down-org/proxyee-down#1025]
### 相关截图
![xd20i8z181 wvwsp 645ac](https://user-images.githubusercontent.com/44749571/47965713-36d4fb80-e085-11e8-826c-c3480d4a90fe.png)

**Comment by 14SHIKE** [comment]
这里正常
可以尝试英文目录放软件
路径可能对移动硬盘支持不太好
![3 ceshi](https://user-images.githubusercontent.com/37872513/47965762-e01bf180-e085-11e8-89b7-1d87f5b95225.gif)

**Comment by monkeyWie** [comment]
Duplicate of #792

**Comment by huangjiajin** [comment]
我也不知道原因到底出在哪里，我的路径是全英文的，是我没有安装JAVA软件的原因吗？

**Comment by huangjiajin** [comment]
> 
> 
> 这里正常
> 可以尝试英文目录放软件
> 路径可能对移动硬盘支持不太好
> ![3 ceshi](https://user-images.githubusercontent.com/37872513/47965762-e01bf180-e085-11e8-89b7-1d87f5b95225.gif)
> 参考#792

我也不知道原因到底出在哪里，我的路径是全英文的，是我没有安装JAVA软件的原因吗？
![qq 20181105124708](https://user-images.githubusercontent.com/44749571/47978502-35451b00-e0f9-11e8-8fdc-970215040aec.png)
![qq 20181105124746](https://user-images.githubusercontent.com/44749571/47978503-35ddb180-e0f9-11e8-8cab-90cf4971e77b.png)

**Comment by huangjiajin** [comment]
我的不是移动硬盘
