### ISSUE TITLE
3.32版本下载进度到90.2%时会停止下载，状态变为未知

### ISSUE THREAD

**Issue by difuer-yl** [proxyee-down-org/proxyee-down#1026]
### 相关截图
![image](https://user-images.githubusercontent.com/16017414/47968516-16696900-e0a6-11e8-9114-2e95387ed38c.png)

**Comment by yyccn** [comment]
可以尝试调整下载的块，百度网盘现在似乎加入了检测链接块数的，调整到10可以有速度，但是就很慢了。你可以尝试一下调整到适合的块。
我本人系统是win10 proxyee是3.32

**Comment by tbfuiaw** [comment]
我的也是，速度很慢

**Comment by monkeyWie** [comment]
尝试刷新下载链接：https://github.com/proxyee-down-org/proxyee-down/wiki/%E5%88%B7%E6%96%B0%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5
