### ISSUE TITLE
所有下载失败

### ISSUE THREAD

**Issue by NaixHw** [proxyee-down-org/proxyee-down#1029]
### 问题描述(必要)
速度0状态未知 一会儿就全部失败了

**Comment by NaixHw** [comment]
....重启后有一个文件下完了 其他试了几次还是失败

**Comment by 14SHIKE** [comment]
参考https://github.com/proxyee-down-org/proxyee-down/issues/987

**Comment by NaixHw** [comment]
> 
> 
> 参考#987

无用 我又不是没下载完 .而且复制链接到idm是有速度的

**Comment by 14SHIKE** [comment]
复制链接？哪来的链接？建议看教程
如果idm有速度你可以用idm，既然你能提取到链接

**Comment by NaixHw** [comment]
> 
> 
> 复制链接？哪来的链接？建议看教程
> 如果idm有速度你可以用idm，既然你能提取到链接

任务里就能看到链接 idm合并起来卡而且限速 又不是教程问题.今天更新后就用不了

**Comment by lydygg** [comment]
对的……我这里也出现这个问题了……而且上午早前还挺好的，然后过了一会儿就出现这个情况了，不知道是不是度娘干了什么

**Comment by hihila** [comment]
我也是

**Comment by chuhemiao** [comment]
同度娘地址，一直显示下载失败

**Comment by 14SHIKE** [comment]
等更新吧，今天下载失败应该是网盘问题，看开发能不能解决

**Comment by CRO2017** [comment]
今天百度云太给力了，基本上PCS和proxyee-down都GG了

**Comment by 14SHIKE** [comment]
> 今天百度云太给力了，基本上PCS和proxyee-down都GG了

登陆下载也不行吗？pcsgo不是登陆下载的

**Comment by CRO2017** [comment]
> > 今天百度云太给力了，基本上PCS和proxyee-down都GG了
> 
> 登陆下载也不行吗？pcsgo不是登陆下载的

你试试吧😂，反正我G了，没有试aria2,反正p2p的资源，干脆客户端解决了

**Comment by 14SHIKE** [comment]
> > > 今天百度云太给力了，基本上PCS和proxyee-down都GG了
> > 
> > 
> > 登陆下载也不行吗？pcsgo不是登陆下载的
> 
> 你试试吧😂，反正我G了，没有试aria2,反正p2p的资源，干脆客户端解决了

等更新吧，开发很能肝的，也很厉害

**Comment by dawn-lc** [comment]
我不小心开成老版本了，真是绝了，老版本居然可以正常下载。。。

**Comment by dawn-lc** [comment]
> > 我不小心开成老版本了，真是绝了，老版本居然可以正常下载。。。
> 
> 妈耶，是第几版呀

![image](https://user-images.githubusercontent.com/30336566/48010886-71a86380-e159-11e8-8fa8-8d588a71f809.png)
2.53版

**Comment by dawn-lc** [comment]
真™绝了hhhhhhhhh

**Comment by JaminZhang** [comment]
> > > 我不小心开成老版本了，真是绝了，老版本居然可以正常下载。。。
> > 
> > 
> > 妈耶，是第几版呀
> 
> ![image](https://user-images.githubusercontent.com/30336566/48010886-71a86380-e159-11e8-8fa8-8d588a71f809.png)
> 2.53版

请问哪里下载 2.53 版本？。。。

**Comment by dawn-lc** [comment]
> > > > 我不小心开成老版本了，真是绝了，老版本居然可以正常下载。。。
> > > 
> > > 
> > > 妈耶，是第几版呀
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/30336566/48010886-71a86380-e159-11e8-8fa8-8d588a71f809.png)
> > 2.53版
> 
> 请问哪里下载 2.53 版本？。。。

很早以前的用的，后来更新了之后，旧版本忘了没去删，我也不清楚哪里有下

**Comment by JaminZhang** [comment]
> 我不小心开成老版本了，真是绝了，老版本居然可以正常下载。。。

百度抽疯了，我这新版本偶尔也可以下载。。。

**Comment by dawn-lc** [comment]
> > 我不小心开成老版本了，真是绝了，老版本居然可以正常下载。。。
> 
> 百度抽疯了，我这新版本偶尔也可以下载。。。

我试了一下，新版本能下载的十不存一，旧版本基本上都能正常下载。。。。。

**Comment by JaminZhang** [comment]
> > > 我不小心开成老版本了，真是绝了，老版本居然可以正常下载。。。
> > 
> > 
> > 百度抽疯了，我这新版本偶尔也可以下载。。。
> 
> 我试了一下，新版本能下载的十不存一，旧版本基本上都能正常下载。。。。。

确实。。。
能共享下你的老版本包吗？

**Comment by RockeyX** [comment]
> 我不小心开成老版本了，真是绝了，老版本居然可以正常下载。。。

我的老版完全不行

**Comment by aifennng** [comment]
2.5.4亲测可用

**Comment by RockeyX** [comment]
我选中文件后点击下载直接就跳到空白页了，

**Comment by coderykw** [comment]
> 2.5.4亲测可用

能分享到谷歌盘 我去下吗？ 2.5.4

**Comment by JaminZhang** [comment]
> 2.5.4亲测可用

能分享一下吗？

**Comment by RockeyX** [comment]
> 2.5.4亲测可用

我点下载之后就直接空白页了，怎么破?

**Comment by RockeyX** [comment]
> > > 2.5.4亲测可用
> > 
> > 
> > 我点下载之后就直接空白页了，怎么破?
> 
> 代理要改成之前的模式，127.0.0.1 9999

改完之后百度盘的网页直接进不去了，我不是从老版本用过来的，麻烦你详细点解释下，多谢。

**Comment by aifennng** [comment]
> > > > 2.5.4亲测可用
> > > 
> > > 
> > > 我点下载之后就直接空白页了，怎么破?
> > 
> > 
> > 代理要改成之前的模式，127.0.0.1 9999
> 
> 改完之后百度盘的网页直接进不去了，我不是从老版本用过来的，麻烦你详细点解释下，多谢。

Google一下就有教程
https://www.zhanghuanglong.com/detail/another-download-of-magic-proxyee-down

**Comment by RockeyX** [comment]
> > > > > 2.5.4亲测可用
> > > > 
> > > > 
> > > > 我点下载之后就直接空白页了，怎么破?
> > > 
> > > 
> > > 代理要改成之前的模式，127.0.0.1 9999
> > 
> > 
> > 改完之后百度盘的网页直接进不去了，我不是从老版本用过来的，麻烦你详细点解释下，多谢。
> 
> Google一下就有教程
> https://www.zhanghuanglong.com/detail/another-download-of-magic-proxyee-down

我去研究研究，多谢

**Comment by RockeyX** [comment]
> > > > 2.5.4亲测可用
> > > 
> > > 
> > > 能分享到谷歌盘 我去下吗？ 2.5.4
> > 
> > 
> > https://drive.google.com/file/d/1GZ98-X38tJbQPE7aj9c2-sGtA_kE4PLM/view?usp=sharing
> > https://drive.google.com/file/d/196bXhps1fVXjqkzKNyIqJV79D5pQDXAI/view?usp=sharing
> 
> 谢谢分享。
> 这个是需要登陆百度账号才能下载的吧？

这是谷歌云，何来登陆百度账号？

**Comment by lyf1134** [comment]
百度云扩展更新了

**Comment by RockeyX** [comment]
> 百度云扩展更新了

可用吗？

**Comment by hihila** [comment]
0.3扩展更新
可是不行,下载失败

**Comment by lyf1134** [comment]
速度波动比较大，但是可以用
0，500K,4M,10M,5M,600K,0,
一直这么跳
不过均速也在3-4M

**Comment by a1798636524** [comment]
更新了0.3扩展后，下载仍然失败，全部失败

**Comment by lyf1134** [comment]
![1](https://user-images.githubusercontent.com/42033610/48042316-15c2f680-e1bc-11e8-87bf-2986c961b090.JPG)
为什么你们下不了

**Comment by RockeyX** [comment]
> 速度波动比较大，但是可以用
> 0，500K,4M,10M,5M,600K,0,
> 一直这么跳
> 不过均速也在3-4M

更新了之后我网页直接没有小红标了

**Comment by a1798636524** [comment]
具体说来，是不登录无法下载，登陆后下载巨慢

**Comment by RockeyX** [comment]
> 具体说来，是不登录无法下载，登陆后下载巨慢

简单来说是这样。

**Comment by Ajept** [comment]
2.54下载巨慢
0.3扩展还是不行
QAQ

**Comment by lydygg** [comment]
下了一下午了，800M的东西下了10% QAQ

**Comment by herexf** [comment]
目前只有压缩可以用了，其他的都挂了。。。
大文件还可以，小文件几乎不行了

**Comment by monkeyWie** [comment]
百度云扩展更新到0.31就好

**Comment by RockeyX** [comment]
一天肝两个版本，感谢开发小哥哥啊。
