### ISSUE TITLE
下载解压双击Proxyee Down.exe,没有窗口显示。

### ISSUE THREAD

**Issue by yzh7271** [proxyee-down-org/proxyee-down#1030]
### 问题描述(必要)
下载解压双击Proxyee Down.exe,没有窗口显示。右键任务栏图标（不太看得清楚）有菜单，但点击菜单没反应。
### 版本号(必要)
3.3.0
### 操作系统(必要)
win XP

**Comment by GM01A** [comment]
大哥你还用xp呢。。。

**Comment by monkeyWie** [comment]
xp用3.4版本
