### ISSUE TITLE
2.5.4 mac版本我传了

### ISSUE THREAD

**Issue by coderykw** [proxyee-down-org/proxyee-down#1033]
https://t.me/Pojieapp/2707

**Comment by coderykw** [comment]
本博客Proxyee-down版本为：2.54 win在这

Proxyee-down：2.54下载地址：链接: https://pan.baidu.com/s/1kcgwSVg5xmJlmWJzNXZpvA 提取码: 5mxv

**Comment by activing** [comment]
我的百度网盘下载不了。。。

**Comment by ted423** [comment]
这里是提交issue的地方吧。。。。
