### ISSUE TITLE
续传问题

### ISSUE THREAD

**Issue by wzk44** [proxyee-down-org/proxyee-down#1034]
### 问题描述(必要)
文件续传时，完成度达到100%后，该任务不会自动从“进行中”栏目移除，且该任务临时文件不会自动删除。下载的文件没有问题。 
### 版本号(必要)
3.32
### 操作系统(必要)
win7 64位
### 相关截图
无
### 相关日志
无

**Comment by TailendWong** [comment]
版本3.32

**Comment by TailendWong** [comment]
版本：3.32
问题：【断点续传】下载任务开始一段时间后，暂停后，再点击继续下载，会导致下载失败。
建议：添加 “重新下载” 功能

**Comment by monkeyWie** [comment]
3.4已经修复了这个bug
