### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by 1357310795** [proxyee-down-org/proxyee-down#1035]
### 问题描述(必要)
拖动连接数时，出现一堆“保存成功”，比较反感
![qq 20181106163035](https://user-images.githubusercontent.com/35869804/48052046-d27b7e80-e1e1-11e8-992f-5e3ddd63292d.png)

### 版本号(必要)
3.32
### 操作系统(必要)
win10 x64

**Comment by HotYearKit** [comment]
slider之必然

**Comment by monkeyWie** [comment]
3.4版本已经修复
