### ISSUE TITLE
更新了插件到0.3还是无法下载

### ISSUE THREAD

**Issue by tao5133** [proxyee-down-org/proxyee-down#1036]
### 相关截图
![qq 20181106170213](https://user-images.githubusercontent.com/44801038/48053834-98f94200-e1e6-11e8-9a0a-96ddb6ea1b84.png)
![qq 20181106170228](https://user-images.githubusercontent.com/44801038/48053835-9991d880-e1e6-11e8-8c5e-075b8ff321dc.png)
![qq 20181106170234](https://user-images.githubusercontent.com/44801038/48053836-9a2a6f00-e1e6-11e8-8ec9-69f89ec7f923.png)

**Comment by panda-coin** [comment]
等更新吧

**Comment by monkeyWie** [comment]
更新到0.31即可

**Comment by tao5133** [comment]
更新了。还是下载失败呢。
