### ISSUE TITLE
使用之后有应用无法联网了

### ISSUE THREAD

**Issue by stickeeper** [proxyee-down-org/proxyee-down#1040]
我在使用这个应用下了几个百度云的文件后发现别的运用有无法联网的情况,比如网易云音乐和爱奇艺,为了确认我在别的电脑上试了一下,不能联网了

**Comment by lyf1134** [comment]
你可以少下几个文件或者把连接数调低一点
调的连接多了别的就连不上了

**Comment by endingly** [comment]
@stickeeper 你能用？不会失败吗

**Comment by ted423** [comment]
你检查下你的代理设置呢。。。

**Comment by stickeeper** [comment]
@ted423 我就是怀疑代理的问题,但是不知道怎么弄

**Comment by stickeeper** [comment]
@endingly 在下能用

**Comment by ted423** [comment]
百度查下ie代理怎么设置就好了

**Comment by monkeyWie** [comment]
把全网嗅探扩展关了，这个会让所有连接都走代理的
