### ISSUE TITLE
2018/11/07测试baiduyun基本没速度；b站番剧只有6分钟，部分视频失败；

### ISSUE THREAD

**Issue by 3Lzm** [proxyee-down-org/proxyee-down#1044]
问题描述：baiduyun基本没速度；b站番剧只有6分钟；
版本号：3.32
操作系统：mac 10.11.6
相关截图：
### 1.第一行为baiduyun，第二行为b站速度
<img width="505" alt="2018-11-07 11 24 18" src="https://user-images.githubusercontent.com/36028655/48140930-c0cecf80-e2e4-11e8-958e-e4c5c5963e1a.png">
### 2.测试番剧链接：https://www.bilibili.com/bangumi/play/ep72045
一共24分钟，下载下来只有6分钟
<img width="444" alt="2018-11-07 11 42 02" src="https://user-images.githubusercontent.com/36028655/48142208-4b183300-e2e7-11e8-98fd-c05d43b7b799.png">
<img width="430" alt="2018-11-07 11 41 52" src="https://user-images.githubusercontent.com/36028655/48142213-50757d80-e2e7-11e8-81cf-c7f4d5fc4a92.png">

**Comment by monkeyWie** [comment]
这个你可以分别到扩展的主页看看
![image](https://user-images.githubusercontent.com/13160176/48613032-96a49e00-e9c5-11e8-9122-085b41ed66a8.png)
