### ISSUE TITLE
最新版百度下载卡死，无法下载，失败

### ISSUE THREAD

**Issue by Chris0Shh08** [proxyee-down-org/proxyee-down#1048]

**Comment by smallasahi** [comment]
我是下载一直0kb然后直接变成失败
版本号是3.32 
系统是win10家庭版
![image](https://user-images.githubusercontent.com/44871069/48203903-93952680-e3a3-11e8-9d1e-6ff6cf9825ef.png)

**Comment by amostang** [comment]
和你一樣，只有部分非常小的文件可以下載

**Comment by player2017** [comment]
我开始也失败，但更新了SwitchyOmega的PAC网址就好了，proxyee-down里面复制粘贴过去

**Comment by sunny-dark** [comment]
我是先有一段正常速度，然后平均百分之六十的时候变成0KB/S

**Comment by monkeyWie** [comment]
Duplicate of #1075
