### ISSUE TITLE
下载被限速, 通过分享链接下载失效

### ISSUE THREAD

**Issue by PotatoFirst** [proxyee-down-org/proxyee-down#1049]
### 相关截图  
![default](https://user-images.githubusercontent.com/44870285/48203515-a9561c00-e3a2-11e8-801d-41cbd7d44f56.JPG)

### 相关日志
必须在个人主页中打开文件才能下载，且下载速度明显降低（pandownload显示账号已被限速）

无痕界面打开分享链接下载无速度

图中上面的任务为登陆状态下载，下面任务为无痕状态通过分享链接下载

**Comment by daiqu** [comment]
放心 都不能用了

**Comment by monkeyWie** [comment]
Duplicate of #1075
