### ISSUE TITLE
PD是凉凉了还是被公关了？

### ISSUE THREAD

**Issue by jiffei** [proxyee-down-org/proxyee-down#1050]
不能用这么久了，也没更新。

**Comment by aceslup** [comment]
多点理解，人家不是拿这个挣钱，而突破技术限制是需要烧脑的。

**Comment by zhuangyingjie** [comment]
从出现开始了，就注定要凉，一直希望这天来的晚一点。

**Comment by monkeyWie** [comment]
我想说一下pd只是个普通的http高速下载器，不存在凉不凉的。
然后关于百度云的问题可以看这里：https://community.pdown.org/topic/128
