### ISSUE TITLE
3.4，任务下载失败

### ISSUE THREAD

**Issue by baiduyunmansigeren** [proxyee-down-org/proxyee-down#1054]
### 相关截图
![image](https://user-images.githubusercontent.com/44897816/48262566-edf2bd80-e45d-11e8-965d-31f1c4b42a7b.png)
![image](https://user-images.githubusercontent.com/44897816/48262621-33af8600-e45e-11e8-8b6e-c232580e8d0b.png)

**Comment by Piao03152004az** [comment]
我也是

**Comment by hdshuai** [comment]
下载失败，速度0

**Comment by phoenixrever** [comment]
同样问题

**Comment by Lan-megumi** [comment]
同样问题，升级到3.4之前我用的3.2也出现了这个问题

**Comment by Angle-bo** [comment]
同样的问题。

**Comment by MarionMaMY** [comment]
> 下载失败的。点击 扩展管理，百度云下载，设置（螺丝帽），填写 BDUSS 和 UA 即可

UA要从哪获取啊。。

**Comment by baiduyunmansigeren** [comment]
>           下载失败的。点击 扩展管理，百度云下载，设置（螺丝帽），填写 BDUSS 和 UA 即可
BDUSS和UA要写什么内容？
