### ISSUE TITLE
更新至3.4版本后，在百度网盘中无法直链下载和批量下载。

### ISSUE THREAD

**Issue by EEERT** [proxyee-down-org/proxyee-down#1055]
### 3.4
###win10企业版 长期服务版2016
###

**Comment by Aliina608** [comment]
OS版也不可以 点击下载选项后软件无反应

**Comment by helynd** [comment]
3.4+0.33
点了没任何反应~没添加任何下载~

**Comment by garydevil** [comment]
3.4+0.33点了没任何反应 x2

**Comment by wuliaoasd** [comment]
只需要在 Extensions里面调整下百度云下载就好了，百度云下载插件是ON状态，后面有个上传图标点击等待上传完就可以了。要是OFF状态下载插件就好。

**Comment by hdshuai** [comment]
> 只需要在 Extensions里面调整下百度云下载就好了，百度云下载插件是ON状态，后面有个上传图标点击等待上传完就可以了。要是OFF状态下载插件就好。

怎么调整？？？

**Comment by ailmm** [comment]
我也是，除了压缩连接下载，PD都是没有反应的。

**Comment by catia2018** [comment]
请教，为什么我的3.4只能压缩下载其他的选项如直接下载一直没速度，暂停后再次启动还是没有下载速度，反复多次仍然无法下载，何故？

**Comment by monkeyWie** [comment]
百度云扩展升级到0.34就好，详见 #1075

**Comment by Xia-Ao** [comment]
百度云扩展已升级到0.34，chrome, win10 64位，单个下载没有问题， 但是批量只在页面显示推送成功，但是proxydown 页面没有反应
