### ISSUE TITLE
Ua是什么，我难道想错了，还是不行啊

### ISSUE THREAD

**Issue by lkde558907** [proxyee-down-org/proxyee-down#1057]
### 相关截图
![image](https://user-images.githubusercontent.com/44836030/48298336-a5d3a980-e4f6-11e8-83ee-0a5e5e53a208.png)

**Comment by baiduyunmansigeren** [comment]
BDUSS又是怎么？百度链接里的吗？

**Comment by NOVA-MUSIC** [comment]
怎么弄都不行。

**Comment by helynd** [comment]
所以UA是什么啊？

**Comment by monkeyWie** [comment]
UA是你理解的意思没错，不过扩展已经更新到0.34了，不需要设置了。
具体请看：https://community.pdown.org/topic/128
