### ISSUE TITLE
下载PS PR下到三分之一32% 下载速度0 下载状态未知 然后下载状态错误  刷新没用 版本3.4

### ISSUE THREAD

**Issue by lironghua53** [proxyee-down-org/proxyee-down#1058]
### 相关截图 
![image](https://user-images.githubusercontent.com/28616394/48308805-b80d2080-e5a6-11e8-846f-a0e27d08c44d.png)

**Comment by fansangg** [comment]
一样

**Comment by monkeyWie** [comment]
Duplicate of #1075
