### ISSUE TITLE
Firefox证书信任有问题

### ISSUE THREAD

**Issue by MasterBility** [proxyee-down-org/proxyee-down#1063]
### 问题描述(必要)
内无“信任由此证书颁发机构标识的软件开发者”选项
### 版本号(必要)
3.4
### 操作系统(必要)
win10 1803专业版
### 相关截图
![qq 20181111225800](https://user-images.githubusercontent.com/44946446/48314616-d571d700-e606-11e8-9ea5-a08f3389786a.png)

**Comment by monkeyWie** [comment]
参考：https://github.com/proxyee-down-org/proxyee-down/wiki/%E7%81%AB%E7%8B%90%E6%B5%8F%E8%A7%88%E5%99%A8%E8%AF%81%E4%B9%A6%E5%AE%89%E8%A3%85
