### ISSUE TITLE
点PD下载后无法推送到Proxyee Down里 

### ISSUE THREAD

**Issue by daydayhip** [proxyee-down-org/proxyee-down#1064]
PC系统WIN7
Proxyee Down 3.4
Google Chrome浏览器

**Comment by mapleshadow** [comment]
同上，貌似无效了

**Comment by knzh** [comment]
从个人网盘网页点没有反应，但是选择压缩下载有反应

**Comment by kentcc88** [comment]
我也是，我是没试过下载成功，升级之后，似乎问题多多，不知道是不是百度云升级的的太厉害，我现在是暂停使用了。。。

**Comment by lincz123** [comment]
我也是这个问题

**Comment by monkeyWie** [comment]
升级百度云扩展，Duplicate of #1075
