### ISSUE TITLE
扩展列表无法刷出

### ISSUE THREAD

**Issue by firewiki** [proxyee-down-org/proxyee-down#1065]
### 问题描述(必要)
公司通过http代理服务器上网，首先在proxyee down的软件设置里设置二级代理，安装CA证书，(用的是firefox浏览器，根据firefox安装CA证书的方法，手动安装证书)， 进入扩展管理->扩展中心， 界面一直等待扩展列表的加载。

上面方法失败后， 尝试把proxyee down的二级代理关闭， IE浏览器里的代理用的代理配置没问题，firefox使用系统代理设置，仍然无法刷出扩展列表。
### 版本号(必要)
3.4
### 操作系统(必要)
win7
### 相关截图
![image](https://user-images.githubusercontent.com/31975616/48322995-097be500-e665-11e8-8b8f-64d70c9198fa.png)

**Comment by monkeyWie** [comment]
用浏览器模式试试

**Comment by firewiki** [comment]
浏览器模式是什么意思？怎么用？

**Comment by HotYearKit** [comment]
软件设置>UI选浏览器

**Comment by firewiki** [comment]
浏览器模式可以刷出。

**Comment by monkeyWie** [comment]
Haven't replied for a long time.
