### ISSUE TITLE
mac os Chrome浏览器访问百度云资源时，未出现PD下载

### ISSUE THREAD

**Issue by myself521** [proxyee-down-org/proxyee-down#1067]
### 问题描述(必要)
使用mac os 下载的版本为：3.4 ，下载百度云拓展插件时报错，报错内容如下：java.lang.RuntimeException: http get error:http://127.0.0.1:55828/proxy/disabled?ns=USB 10/100/1000 LAN

### 版本号(必要)
3.4

### 操作系统(必要)
mac os 10.13.6 (17G65)
### 相关截图
![image](https://user-images.githubusercontent.com/40910081/48334787-6770f280-e68e-11e8-9a6c-44867170a64c.png)

### 相关日志
java.lang.RuntimeException: http get error:http://127.0.0.1:55828/proxy/disabled?ns=USB 10/100/1000 LAN

**Comment by myself521** [comment]
重启电脑后插件正常下载，但是开启后，在谷歌浏览器的百度云盘未出现pd下载的标示 截图如下：
![image](https://user-images.githubusercontent.com/40910081/48335424-3db8cb00-e690-11e8-8bb8-ece7d356370a.png)
![image](https://user-images.githubusercontent.com/40910081/48335441-48736000-e690-11e8-864c-3b906b832a03.png)
谷歌浏览器版本：
![image](https://user-images.githubusercontent.com/40910081/48335484-6e006980-e690-11e8-8a91-af393b786822.png)

**Comment by ArielCharlotte** [comment]
下载百度云拓展插件时报错,我之前用家里有线下载也遇到这个问题，换成无线连接就好了。

**Comment by ArielCharlotte** [comment]
浏览器的百度云盘未出现pd下载的标示是因为“扩展管理-全局代理“未打开。

**Comment by myself521** [comment]
@ArielCharlotte 
![image](https://user-images.githubusercontent.com/40910081/48456920-67d6ce00-e7f3-11e8-825a-93a279fe41dc.png)
![image](https://user-images.githubusercontent.com/40910081/48456966-9359b880-e7f3-11e8-98b1-8635970d8c6a.png)
仍然没有pd下载

**Comment by monkeyWie** [comment]
可以试试用SwitchyOmega接管代理：https://github.com/proxyee-down-org/proxyee-down/wiki/%E4%BD%BF%E7%94%A8SwitchyOmega%E6%8E%A5%E7%AE%A1%E4%BB%A3%E7%90%86

**Comment by cuiYuhe** [comment]
SwitchyOmega接管代理已经添加并切换，也是不可以 :(
