### ISSUE TITLE
升级到最新，百度还是下载不了

### ISSUE THREAD

**Issue by seventeeeen** [proxyee-down-org/proxyee-down#1070]

**Comment by seventeeeen** [comment]
升级到最新，百度还是下载不了

**Comment by AsyDynamics** [comment]
版本3.4，chrome 72 on win10，已安装证书，坐标欧洲。在百度云网页版点PD直接下载后，软件不会自动创建任务

**Comment by zaz1414** [comment]
升级之前百度能直接直连下载，升级之后必须选择压缩连接下载。win10  家庭版  版本是1803

**Comment by monkeyWie** [comment]
Duplicate of #1075
