### ISSUE TITLE
Mac版无法升级3.4，升级一直提示更新失败，请检查网络或手动下载更新包

### ISSUE THREAD

**Issue by shiruchao** [proxyee-down-org/proxyee-down#1072]
### 问题描述(必要)
Mac版无法升级3.4，升级一直提示更新失败，请检查网络或手动下载更新包，电脑是可是上网的！重启也无效！关闭系统代理也是无效！
### 版本号(必要)
现版本号为3.32
### 操作系统(必要)
MacOS 14.1
### 相关截图
![image](https://user-images.githubusercontent.com/20981112/48384829-f598b780-e726-11e8-9563-b46c943abc1b.png)

**Comment by shiruchao** [comment]
可以手动安装升级！但是无法自动安装！

**Comment by monkeyWie** [comment]
额 这个网络问题，一直失败的话就只能手动更新了
