### ISSUE TITLE
最新版的也挂了

### ISSUE THREAD

**Issue by VCDVD** [proxyee-down-org/proxyee-down#1081]
可以调用下载，但是开始速度奇慢，断断续续，后面就直接下载失败了。

**Comment by yechawang2008** [comment]
我也是 慢的出奇

**Comment by DubheBroken** [comment]
其他工具也挂了，现在下载强制要求登录，运气好能偷跑几个文件，然后就开始疯狂掉速和失败，据说发现用加速工具会封号封IP

**Comment by fgb3420** [comment]
我是下载前几秒是满速的，后面速度就会越来越慢而且会连续断开连接，我觉得可能是百度对流量或下载速度“不正常”的账号进行限制了

**Comment by ThomasChant** [comment]
也遇到这个情况，开始下载还好好的，过了一会后下载就下载不了了

**Comment by 2dcon** [comment]
另外从自己网盘里下载，用过proxydown的文件会无法在官方客户端里下载orz

**Comment by monkeyWie** [comment]
暂时没什么好办法了啊，只有充会员才能解除限速了~

**Comment by VCDVD** [comment]
挂就挂了，干嘛关闭我的帖子？

**Comment by F13370108086** [comment]
完全不能用了，我用的3.4版本，根本不行
