### ISSUE TITLE
安装插件后百度云网站页面显示错乱

### ISSUE THREAD

**Issue by amefan** [proxyee-down-org/proxyee-down#1084]
### 问题描述(必要)
安装插件后百度云网站页面显示错乱
### 版本号(必要)
3.4
### 操作系统(必要)
win10
### 相关截图
![image](https://user-images.githubusercontent.com/26429068/48526990-82c54300-e8c4-11e8-92e3-4e3d1bf07c2d.png)
![image](https://user-images.githubusercontent.com/26429068/48527002-92dd2280-e8c4-11e8-9cba-d42e1f7bb924.png)

**Comment by laocoon123** [comment]
如果禁用掉扩展里的百度云插件倒是正常显示了，也可以看见pd下载按钮

**Comment by monkeyWie** [comment]
我这测试正常哦
