### ISSUE TITLE
3.4版本掉速至0

### ISSUE THREAD

**Issue by waterlogithub** [proxyee-down-org/proxyee-down#1088]

**Comment by hihila** [comment]
same issue

**Comment by owaranai** [comment]
类似情况，128 256 512等数字出现概率很高 几乎是下一秒停五秒 全最新版本 win10

**Comment by SeAL80s** [comment]
百度封禁第三方下载。几乎全军覆没，百度云盘VIP破解、无限试用，SpeedPan、PanDown、Baidupcs-Go、Proxyee-down都被限速。现在唯一的办法就是.........弃用百度产品

**Comment by huming2207** [comment]
似乎aria2c+baidu exporter也是一样，估计又是百度在搞鬼。

**Comment by Piao03152004az** [comment]
估计百度在你第一次下载的时候没限速，第二次就限速了。

**Comment by 609453361** [comment]
3.32发现开始时低速及0kb断续，之后大几率失败，升3.4问题仍然存在

**Comment by vampire827** [comment]
年费超级会员了解一下～

**Comment by monkeyWie** [comment]
Duplicate of #1075
