### ISSUE TITLE
没有PD按钮.....

### ISSUE THREAD

**Issue by ZhuGeKongBo** [proxyee-down-org/proxyee-down#1090]
### 问题描述(必要)
安装了证书、扩展管理里的百度云下载和全网嗅探、打开了左上角的全局代理，在关闭浏览器情况下反复安装尝试，但依然不出现PD下载按钮。搞了一个小时了。
用的是谷歌浏览器，浏览器的扩展程序里有一个sadpand，没有看见proxyee相关
### 版本号(必要)
3.2
### 操作系统(必要)
Windows10

**Comment by ZhuGeKongBo** [comment]
更新：切换了IE浏览器后出现了，但是下载速度还是0K

**Comment by bfx1000** [comment]
Duplicate of #1075
