### ISSUE TITLE
证书文件在Proxyee Down安装目录/main/ssl 无法找到 。main下不存在ssl文件。

### ISSUE THREAD

**Issue by Mic-ao** [proxyee-down-org/proxyee-down#1093]

**Comment by peipengw** [comment]
顶一个。11月18号下载的64位找不到证书。

**Comment by twinkleevan** [comment]
可以试试去看proxyee down软件界面的扩展管理那里
有三个扩展，分别是百度云下载，全网嗅探和B站视频下载
在“百度云下载”列找到那个下载按钮，点击下载安装，并且打开开关
再去  Proxyee Down安装目录/main  那里就能找到证书文件了
