### ISSUE TITLE
磁头写入频繁，建议加入写入缓存

### ISSUE THREAD

**Issue by wzk44** [proxyee-down-org/proxyee-down#1098]
### 问题描述(必要)
因为最近百度限速，速度只有几十K不等，而磁头写入动作却过于频繁（约为1次/秒），建议依据时间和一定数据量来重新设置。
### 版本号(必要)
3.4
### 操作系统(必要)
win10 1709

**Comment by monkeyWie** [comment]
这是因为在记录下载进度，频率高是怕断电导致进度丢失太多
