### ISSUE TITLE
百度云已无法使用

### ISSUE THREAD

**Issue by ytyzxm123** [proxyee-down-org/proxyee-down#1101]
### 相关截图
![qq 20181120110332](https://user-images.githubusercontent.com/45189019/48749259-1330c880-ecb5-11e8-9cec-9e9be8fa9721.jpg)

### 相关日志2018-11-20  11:00:35.418 [http-nio-26339-exec-8] ERROR lee.study.down.mvc.exception.RestExceptionHandler - rest error:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

**Comment by dongfangy2011** [comment]
我已经等了很多天了，一位会解决的，结果还是一样

**Comment by monkeyWie** [comment]
Duplicate of #1075
