### ISSUE TITLE
B站大会员视频无法下载

### ISSUE THREAD

**Issue by vivahu** [proxyee-down-org/proxyee-down#1122]
### 问题描述(必要)
「非」大会员视频下载无问题，但是大会员视频无法下载
测试URL：https://www.bilibili.com/bangumi/play/ep250468

### 版本号(必要)
3.4

### 操作系统(必要)
macOS 10.14.1

### 相关截图
![image](https://user-images.githubusercontent.com/1997175/49060761-d8e1a100-f249-11e8-9c12-f235aee29d6b.png)

### 相关日志
无

**Comment by monkeyWie** [comment]
可以把issue提到扩展主页这里：https://github.com/monkeyWie/bilibili-helper/issues
