### ISSUE TITLE
关于账号限速

### ISSUE THREAD

**Issue by Quofataferunt** [proxyee-down-org/proxyee-down#1124]
### 问题描述(必要)
一个新账号只有最开始的1-3次不限速下载，之后就会被限速，资源是同一个账号共享出来的
### 版本号(必要)
3,4
### 操作系统(必要)
Windows
### 相关日志

这个问题不知道是不是普遍存在，有什么办法解决吗

**Comment by monkeyWie** [comment]
目前没什么解决办法，除非开会员，10块的那种就可以。

**Comment by Quofataferunt** [comment]
10块稍微能接受，不过付给百度有点难受

**Comment by Quofataferunt** [comment]
> 目前没什么解决办法，除非开会员，10块的那种就可以。

10块能接受，不过付给百度有点难受

**Comment by ArielCharlotte** [comment]
> 目前没什么解决办法，除非开会员，10块的那种就可以。

我开了10元会员也不能下载呀
