### ISSUE TITLE
下载速度一直为0

### ISSUE THREAD

**Issue by holen1210** [proxyee-down-org/proxyee-down#1126]
### 问题描述(必要)
下载速度一直为0
### 版本号(必要)
1.0
### 操作系统(必要)
mac os 10.13.6
### 相关截图
![image](https://user-images.githubusercontent.com/20247164/49194353-ba9cb200-f3bd-11e8-8fe5-ab95f9e7acf6.png)

### 相关日志
无

**Comment by monkeyWie** [comment]
Duplicate of #1075
