### ISSUE TITLE
任务文件名显示unknown

### ISSUE THREAD

**Issue by mynameiskiller** [proxyee-down-org/proxyee-down#1128]
### 问题描述(必要)
       将百度云分享链接复制到创建任务的链接栏后，创建任务会显示unknown。并且图二中的连接数和路径均不可更改。
### 版本号(必要)
       3.4
### 操作系统(必要)
       win10 ×64位
### 相关截图
![default](https://user-images.githubusercontent.com/35190570/49325365-16ad3500-f57c-11e8-9d52-fd8ffd4eaab4.JPG)
![2](https://user-images.githubusercontent.com/35190570/49325367-19a82580-f57c-11e8-8860-a491b4ba9291.JPG)

**Comment by monkeyWie** [comment]
不是这样用的哦，建议安装扩展之后再下载

**Comment by dengruquan** [comment]
安装扩展后，创建任务中加入百度云分享链接还是unknown，同时下载内容还是分享链接的html内容
