### ISSUE TITLE
编译页面报错

### ISSUE THREAD

**Issue by FanQijun** [proxyee-down-org/proxyee-down#1132]
### 问题描述(必要)
编译页面时 报2个error
### 版本号(必要)
3.4
### 操作系统(必要)
macOS Majave
### 相关截图
![image](https://user-images.githubusercontent.com/24284164/49369500-83673180-f72c-11e8-99bf-5cd6a7fb383f.png)

**Comment by xlhd19980327** [comment]
issue都没有开发人员来解决吗。。。看了好几个都是这样

**Comment by monkeyWie** [comment]
@monkeyWie 太忙了啊 老哥。。 都是抽空看看

**Comment by FanQijun** [comment]
就是按照你提供的编译步骤 编译脚本有2个打印 导致报错 注释掉就好了 建议修复下

monkeyWie <notifications@github.com> 于2018年12月6日周四 下午4:42写道：
