### ISSUE TITLE
百度云一个文件夹中超过100个文件时无法下载100以后的文件

### ISSUE THREAD

**Issue by yoyoyosoro** [proxyee-down-org/proxyee-down#1136]
### 一个文件夹中超过100个文件时无法下载100以后的文件，自动添加只添加一百个，即使手动选择也无法 
       识别，会红框提示请选择文件。
### 相关日志
[pdown-error.2018-12-04.log](https://github.com/proxyee-down-org/proxyee-down/files/2643353/pdown-error.2018-12-04.log)

**Comment by monkeyWie** [comment]
相同的问题，待解决：https://github.com/monkeyWie/baiduyun-helper/issues/19
