### ISSUE TITLE
proxyee-down无下载速度

### ISSUE THREAD

**Issue by llr007** [proxyee-down-org/proxyee-down#1137]
### 问题描述(必要)
运行3.4的时候无下载速度

### 版本号(必要)
Proxyee Down.3.4.windows.x64

### 操作系统(必要)
64位win10

### 相关截图
图片无法上传

**Comment by NOVA-MUSIC** [comment]
是的

**Comment by FrankCooper** [comment]
我的也是0速度...

**Comment by xlhd19980327** [comment]
issue都没有开发人员来解决吗。。。看了好几个都是这样

**Comment by monkeyWie** [comment]
如果是百度云下载的话，参考这个：#1075
