### ISSUE TITLE
下载的最新版下载器中无插件可安装

### ISSUE THREAD

**Issue by xlhd19980327** [proxyee-down-org/proxyee-down#1138]
### 相关日志

下载的proxyee down中，拓展管理栏下，点了安装之后，无论是是否取消全局代理，扩展中心中扩展插件均显示为0，如图所示：
![image](https://user-images.githubusercontent.com/33627523/49503676-f995a080-f8b2-11e8-9522-b46230c7bccd.png)
![image](https://user-images.githubusercontent.com/33627523/49503696-06b28f80-f8b3-11e8-8499-6447b5f1fc1f.png)

版本号：最新版3.4
操作系统：Windows7 64位家庭普通版

**Comment by monkeyWie** [comment]
你可以手动安装扩展，在这里下载扩展文件：https://github.com/proxyee-down-org/proxyee-down-extension
下完之后通过加装本地扩展按钮选择对应的扩展目录就行

**Comment by xlhd19980327** [comment]
请问是dist文件夹里面吗

**Comment by monkeyWie** [comment]
不用选dist，选外面的大文件夹比如百度云的扩展是`baiduYun`

**Comment by xlhd19980327** [comment]
好的，请问这个软件支持仅ipv6的网络下载吗？如若不支持，如何在本地仅有ipv6的网络下下载呢？

**Comment by monkeyWie** [comment]
ipv6的话我没试过，应该没问题吧，毕竟这不是应用层的事

**Comment by xlhd19980327** [comment]
请问这个问题应该找哪个咨询呢？因为后来我发现造成以上问题的应该是ipv6的原因，使用ipv4就能正常下载并且安装拓展

**Comment by monkeyWie** [comment]
应该是扩展服务器不支持ipv6啊，和你本地没关系

**Comment by xlhd19980327** [comment]
百度网盘不支持ipv6流量下载，所以使用百度网盘拓展下载文件就没法使用ipv6流量吗？

**Comment by monkeyWie** [comment]
这个又可能哦 不过我不知道百度网盘支不支持ipv6啊

**Comment by xlhd19980327** [comment]
的确不支持ipv6，想问下你们这个拓展大概是什么原理能加速百度云啊

**Comment by monkeyWie** [comment]
扩展只是为了获取文件的下载链接，加速下载就是靠的下载器本身

**Comment by monkeyWie** [comment]
看看这个吧：https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Range
