### ISSUE TITLE
idea 无法运行

### ISSUE THREAD

**Issue by zuiailaoda** [proxyee-down-org/proxyee-down#1143]
git 了最新版本，idea启动没有报错，显示白板页面

![image](https://user-images.githubusercontent.com/43024499/49615434-88f0a000-f9e8-11e8-8bcc-cb83ef05b065.png)

**Comment by monkeyWie** [comment]
前端没编译吧？

**Comment by zuiailaoda** [comment]
spring boot 项目在哪下载呢？这边只有jar包

**Comment by zuiailaoda** [comment]
找到了，谢谢
