### ISSUE TITLE
请尝试更新脚本或复制以下信息提交issue  Exception: downloadManager.js加载失败  Script Ver: 0.1.8  TemperMonkey Ver: 4.7.44  UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36

### ISSUE THREAD

**Issue by fuqingdidi** [proxyee-down-org/proxyee-down#1144]
### 相关截图请尝试更新脚本或复制以下信息提交issue

Exception: downloadManager.js加载失败

Script Ver: 0.1.8

TemperMonkey Ver: 4.7.44

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
### 相关日志

**Comment by monkeyWie** [comment]
Invalid question.
