### ISSUE TITLE
请问这个能不能支持断点下载啊

### ISSUE THREAD

**Issue by xlhd19980327** [proxyee-down-org/proxyee-down#1169]
### 相关日志
如题，希望程序员实现断点下载，老是下到一半失败好可惜啊。。。

**Comment by yttrium3** [comment]
我记得可以断点续传啊，但是如果和百度云那边断开连接之后可能需要刷新下载链接

**Comment by monkeyWie** [comment]
支持的啊，但是你这种情况应该是属于下载链接失效了，具体看看：https://github.com/proxyee-down-org/proxyee-down/wiki/%E5%88%B7%E6%96%B0%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5
