### ISSUE TITLE
关于代理

### ISSUE THREAD

**Issue by dreamchonghua** [proxyee-down-org/proxyee-down#1179]
希望增加一个功能，本来浏览器就是是谷歌上网助手上网的，浏览器设置了代理，可以上油管
但是这个软件没有设置代理的地方，如：
HTTP代理
HTTPS代理
SOCK4代理
SOCK5代理
如果你们的软件可以设置代理就好了，谢谢！！！

**Comment by monkeyWie** [comment]
设置界面有二级代理可以设置的
