### ISSUE TITLE
如何清理电脑上因为安装Proxyee-down而增加的代理

### ISSUE THREAD

**Issue by lyh530128740** [proxyee-down-org/proxyee-down#1237]
[log.zip](https://github.com/proxyee-down-org/proxyee-down/files/2879248/log.zip)

### 问题描述(必要)
安装Proxyee-down，然后安装了百度云的扩展，全局代理自动打开，但是电脑上的Microsoft Teams软件无法正常登陆，提示网络有问题。截图如下：
![image 3](https://user-images.githubusercontent.com/47775373/53003596-40cf0e80-346a-11e9-8eb0-aa6a68910a52.png)
请问，在Proxyee-down软件关闭的情况下，如何清理电脑上因为安装Proxyee-down而增加的代理？
### 版本号(必要)
3.4
### 操作系统(必要)
W10
### 相关截图
如上
### 相关日志
如上

**Comment by monkeyWie** [comment]
在IE浏览器里面可以取消掉，或者退出软件就会自动取消。

**Comment by jinyu121** [comment]
那么mac下呢？每次启动都会要输入密码或者按指纹，是做了什么？求如何取消？
