### ISSUE TITLE
mvn not found

### ISSUE THREAD

**Issue by Dearj611** [proxyee-down-org/proxyee-down#1256]
### 问题描述(必要)

请问提示bash: mvn: command not found 该怎么办啊

**Comment by monkeyWie** [comment]
如果你要自己编译项目的话，mvn需要安装maven。

**Comment by Dearj611** [comment]
好的，谢谢:) 直接下载macos的程序不知道为啥点击了程序也不弹出来，只有自己编译了。

**Comment by monkeyWie** [comment]
也可以下载jar包直接命令行运行
