### ISSUE TITLE
某些分段下载较慢,能否让其他下载完support他？

### ISSUE THREAD

**Issue by peter0530** [proxyee-down-org/proxyee-down#130]
### 相关日志

**Comment by 1160062997** [comment]
欸，我就是按了一下午的暂停、开始，可算是把视频下载完了

拿油猴插件弄出来的链接，idm还提示没有权限下载，很是头疼。
pandownload又关了。。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
