### ISSUE TITLE
macos 的任务栏没有显示图标

### ISSUE THREAD

**Issue by issuessss** [proxyee-down-org/proxyee-down#221]
### 问题描述(必要)
看说明,应该在任务栏上显示proxyee-down的图标,但是没有任何显示,通过启动脚本,也提示启动成功
启动如下

➜  proxyee-down-2.42 sh start.sh
正在启动proxyee-down，运行需要管理员权限，请输入用户密码按回车键确认(若无输入提示请忽略)
Password:
                                                          _
                                                         | |
 _ __   _ __   ___  __  __ _   _   ___   ___  ______   __| |  ___  __      __ _ __
| '_ \ | '__| / _ \ \ \/ /| | | | / _ \ / _ \|______| / _` | / _ \ \ \ /\ / /| '_ \
| |_) || |   | (_) | >  < | |_| ||  __/|  __/        | (_| || (_) | \ V  V / | | | |
| .__/ |_|    \___/ /_/\_\ \__, | \___| \___|         \__,_| \___/   \_/\_/  |_| |_|
| |                         __/ |
|_|                        |___/
^C%

### 版本号(必要)
proxyee-down-2.42-mac.zip

### 操作系统(必要)
10.13.3 (17D102)

### 相关日志

**Comment by 14SHIKE** [comment]
2.42版本刚发出来就撤掉了，有bug
等作者上传新的2.42版本

**Comment by qydxyx** [comment]
跟bartender有冲突，运行完后没法显示图标，只有退出bartender后才能正常显示。

**Comment by issuessss** [comment]
原来如此,我是装了bartender3,等下一个稳定版出来
