### ISSUE TITLE
软件优化建议

### ISSUE THREAD

**Issue by XAIOS** [proxyee-down-org/proxyee-down#226]
# 主要问题：每次打开软件都需要稍微配置一下
## 浏览器版本：Chrome 64
提供下日志文件：[error.2018-03-30.log](https://github.com/monkeyWie/proxyee-down/files/1862519/error.2018-03-30.log)

不知道是不是因为加载配置失败，导致每次启动软件都需要做些调整（主要是切换为浏览器 UI），希望可以尽快修复一下，本机上在安装这个软件之前是没有配置过任何关于Java的东西的，不知道会不会有所影响。

## 在全局 CSS 中写入
```css
::-webkit-scrollbar {
  display: none;
}
```
可以隐藏 webkit 内核的相关浏览器（如 Chrome）的滚动条，这样子体验上会好一点，因为如果任务较多或点击查看详情的时候，因为页面长度超过了一屏，滚动条会出现，然后增加进来的十多个像素会影响页面的布局，举个栗子，我每次点击详情，页面都会闪一下（比喻），体验上比（fei）较（chang）不好。

希望大佬加油~

**Comment by 14SHIKE** [comment]
gui问题（窗口不显示）新版本已经修复
现在版本是2.43
注意：由于网盘限制了批量下载的并发数，分段数尽量不超过64：单文件则没有此限制
另外2.43版本  不建议  下载时勾选文件夹！

**Comment by monkeyWie** [comment]
@XAIOS 配置保存的问题可以更新到最新版，已经修复了
