### ISSUE TITLE
出现了一个新问题，貌似是文件占用

### ISSUE THREAD

**Issue by ghost** [proxyee-down-org/proxyee-down#231]
问题描述：在shell中启动proxyee-down提示Unable to access jarfile,怀疑是文件占用的问题，但是不会解除占用，这就很尴尬了……
版本：3.43
操作系统：deepin 15.5
![](https://raw.githubusercontent.com/aojie654/gitLearn/a0eb16a0adddac10c96c8e43d6100c3288ecae90/DeepinScreenshot_deepin-terminal_20180330185128.png)

**Comment by monkeyWie** [comment]
直接java -jar proxyee-down.jar 运行试试

**Comment by aojie654** [comment]
@monkeyWie 有时候会出现，很奇怪……下次再这样的话我试试看吧，谢谢啦，开发者辛苦了  :-3

**Comment by monkeyWie** [comment]
那是应为没有正常退出吧

**Comment by aojie654** [comment]
@monkeyWie 正常退出指的是现状态栏退出再关闭terminal吗？

**Comment by monkeyWie** [comment]
你是直接kill进程退出吗？

**Comment by aojie654** [comment]
@monkeyWie ctrl+C -_-||

**Comment by aojie654** [comment]
不行，试了一下java -jar proxyee-down.jar，不能访问……

**Comment by hooboor** [comment]
1、你的说法很值得怀疑，Unable to access jarfile首先想到的是文件权限问题，而不是文件占用问题！你是这个文件的属主吗？你的文件访问权限是755吗？

2、已经在deepin15.5上进行了测试，完全可以运行。并没有你说的那种情况发生！！！


3、 安装步骤按照作者给出的方法进行操作

4、查看文件信息
test@test-PC:~/proxyee-down-2.44$ ls -lh
total 64K
drwxr-xr-x 5 test test 4.0K Apr 16 16:40 main
-rwxr-xr-x 1  test test 58K  Apr  2 16:02 proxyee-down.jar

5、执行程序时，会报一堆警告：
WARNING: Could not lock System prefs. Unix error code 0.
Apr 16, 2018 5:09:49 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Apr 16, 2018 5:10:19 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock System prefs. Unix error code 0.
Apr 16, 2018 5:10:19 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
但这并不影响程序运行。

6、出现上面的告警，请参考http://fan.iteye.com/blog/798649。如果程序界面不能显示，请删除用户目录下的.java隐藏目录，再重新运行程序。

**Comment by aojie654** [comment]
@hooboor 首先，以root方式运行提示java不是一个命令，这个估计是jdk配置问题
其次：不能运行是偶发出现的，不是每次都有的，所以排除权限问题
再次：我自己下载的文件，我自己解压的，确认过权限了，请不要用三个感叹号，给人感觉很不好！！！
最后，不想引战，自重

**Comment by monkeyWie** [comment]
更新到2.5试试
