### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by JokeJoe8806** [proxyee-down-org/proxyee-down#233]
分段数建议设置3个
<1m <10m 其他。小文件分段数太高有时无法下载。
或者有一个线程下载完后，从现有线程分一半任务出来，不然下都最后只有几个线程在下

**Comment by 14SHIKE** [comment]
分段数支持后期作者会考虑
由于网盘限制
单文件下载分段数不限   网速高就高分段，速度没有限制
多文件下载分段数64以下，下载时不要勾选到文件夹，速度还是可以的
