### ISSUE TITLE
想问下，下载的文件是root用户权限的，这个有计划优化吗

### ISSUE THREAD

**Issue by fengjx** [proxyee-down-org/proxyee-down#235]
### 版本号
2.42
### 操作系统
macOS

**Comment by monkeyWie** [comment]
可以在设置里禁用证书检查并且把嗅探模式关闭，然后不用sudo启动应该可以解决

**Comment by wujianbotju** [comment]
@monkeyWie 请问如何在设置里面禁用证书检查，我发现现在新版在打开https://pan.baidu.com时都会提示我『您的连接不是私密连接』，请教如何解决

**Comment by hooboor** [comment]
程序刚刚起步你就要优化，要求太高了。

**Comment by monkeyWie** [comment]
@wujianbotju 需要安装证书啊，参考手动证书安装教程https://github.com/monkeyWie/proxyee-down/blob/master/.guide/common/ca/read.md
