### ISSUE TITLE
繁體中文在地化

### ISSUE THREAD

**Issue by kulaLin** [proxyee-down-org/proxyee-down#236]
### 相关日志

**Comment by monkeyWie** [comment]
首先谢谢你的支持，不过现在软件还不支持国际化，因为当初开发的时候想到应该都是国内用户所以架子没有搭好，以后重构的话再@你

**Comment by zz234807** [comment]
别国际化了。让友人冲个会员为祖国奉献奉献。

**Comment by kulaLin** [comment]
@monkeyWie 要3.0了，字串代碼給我，我來處理在地化

**Comment by kulaLin** [comment]
@monkeyWie 
怎麼給我？

**Comment by monkeyWie** [comment]
@kulaLin  如果你可以提交pr的话，就直接clone 3.0分支提交吧。

**Comment by kulaLin** [comment]
@monkeyWie 
不過字串文件我沒找到

**Comment by monkeyWie** [comment]
@kulaLin

**Comment by kulaLin** [comment]
@monkeyWie 
好的請我時間做在地化，
繁體中文OS執行3.0的exe會無法打開，用Locale Emulator模擬簡體中文才能正常打開
Win10 64bit

**Comment by monkeyWie** [comment]
@kulaLin 解压到全英文的路径运行试试看

**Comment by kulaLin** [comment]
@monkeyWie 
這點有嘗試過，問題依舊

**Comment by monkeyWie** [comment]
@kulaLin 额 我有空测试下把系统设置为繁体看看

**Comment by kulaLin** [comment]
@monkeyWie 
提交PR了，後續添加請@我

**Comment by BlackHole1** [comment]
@kulaLin 十分感謝您的貢獻

**Comment by kulaLin** [comment]
@monkeyWie 
目前只能用Locale Emulator模擬簡體中文使用
此外扩展並無顯示，0.15版顯示已安裝

**Comment by kulaLin** [comment]
@monkeyWie 
3.0RC還是只能用Locale Emulator打開
語言切換成繁體中文，會顯示成英文

錯誤log
[hs_err_pid7068.log](https://github.com/proxyee-down-org/proxyee-down/files/2345325/hs_err_pid7068.log)

**Comment by monkeyWie** [comment]
@kulaLin 
扩展的设置看看https://monkeywie.github.io/2018/09/05/proxyee-down-3-0-guide/#%E5%85%A8%E5%B1%80%E4%BB%A3%E7%90%86

**Comment by kulaLin** [comment]
@monkeyWie @BlackHole1 
字串再次更新。
我的系統還是只能透過Locale Emulator打開，如何解?

**Comment by kulaLin** [comment]
@monkeyWie @BlackHole1 
這三處無法在地化
![sshot-2018-09-08- 00-26-37](https://user-images.githubusercontent.com/17091825/45231302-2ced8100-b2fe-11e8-891f-a53ef5e0da44.png)
![sshot-2018-09-08- 00-26-52](https://user-images.githubusercontent.com/17091825/45231303-2ced8100-b2fe-11e8-8c0a-d2512da262e2.png)
![sshot-2018-09-08- 00-27-18](https://user-images.githubusercontent.com/17091825/45231305-2ced8100-b2fe-11e8-980b-1981ed6fddec.png)

**Comment by monkeyWie** [comment]
@kulaLin 你用qq吗？或者有什么IM软件联系下

**Comment by kulaLin** [comment]
@monkeyWie 
QQ號
3180941603

**Comment by kulaLin** [comment]
@monkeyWie 
感謝解決我的問題，也可能是大家的問題。
原來只是JAVA造成的BUG

**Comment by monkeyWie** [comment]
用3.03的64位版本运行就好了，32位jre运行可能会碰到这个奇葩bug
