### ISSUE TITLE
提几个建议，望大佬采纳!

### ISSUE THREAD

**Issue by man2018** [proxyee-down-org/proxyee-down#257]
### 问题描述(必要)
1、如果之前已经启动了一个proxyee-down进程，此时如果手误重新启动了，希望能增加监测功能
2、每次启动时都要求root密码才能启动成功，但我用shuttle无法设置自动输入密码功能，希望proxyee-down增加自启动功能或者开机后启动时不用输入密码功能
### 相关日志

**Comment by ivae09** [comment]
其他的我不知道 mac 我自己封装了一个自动操作流程 app，可以实现以上功能。。。

**Comment by ted423** [comment]
我是觉得windows可能也需要，因为没必要多开，并且开多了会提示端口占用，还可能关错

**Comment by BlackHole1** [comment]
部分问题新版已经修复
