### ISSUE TITLE
Run without sudo

### ISSUE THREAD

**Issue by jinyu121** [proxyee-down-org/proxyee-down#263]
### 问题描述(必要)

I can not run it without `sudo`. 

A WARNING occurred, and exited? OK, that's due to permission, but I changed the permission of `prefs.tmp` and `prefs.xml`, nothing helps.

### 版本号(必要)

2.44

### 操作系统(必要)

Debian 9

### 相关截图

```
> proxyee-down-2.44 java -jar proxyee-down.jar
四月 10, 2018 9:13:37 下午 java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush system prefs: java.util.prefs.BackingStoreException: Can't rename /etc/.java/.systemPrefs/prefs.tmp to /etc/.java/.systemPrefs/prefs.xml
```

### 相关日志

Nope. Since no log created

**Comment by hooboor** [comment]
权限不够

**Comment by monkeyWie** [comment]
jdk用的什么版本？有安装javafx吗？

**Comment by jinyu121** [comment]
@hooboor
sodu 当然可以，但是作为一个下载工具，为什么要用sudo？

@monkeyWie 
openjdk-8-jre: 8u162-b12-1~deb9u1
openjfx: 8u111-b14-1

**Comment by monkeyWie** [comment]
sudo是为了设置代理服务器和安装ca证书用的，不想sudo的话可以关闭嗅探模式和证书检查

**Comment by hooboor** [comment]
你上面的警告信息，我在deepin上面见过，但并不影响程序运行！
你说你是普通用户，为何你的.java会在/etc/目录下？按说应该在你运行程序的用户目录下

**Comment by monkeyWie** [comment]
@hooboor 谢谢反馈 不过这个错误信息应该是判断是否有root权限的地方抛出异常了
