### ISSUE TITLE
看介绍，好像支持Linux，那么能否安装到梅林上？

### ISSUE THREAD

**Issue by Antecer** [proxyee-down-org/proxyee-down#264]
如题：这个下载器，体验了几个小时，感觉真的很棒，分段拉满，虽然带宽没跑满，但是也很不错了，比常规的三方下载器还是快很多了。
看介绍应该是能在Linux系统上用？那么我是否可以把它安装到梅林系统的智能路由上，实现脱机下载？

**Comment by YLaido** [comment]
应该没问题，但硬路由性能与vps有很大差距，体验可能很差

**Comment by vivahu** [comment]
关键是路由器的硬件跑JVM虚拟机效率如何？
