### ISSUE TITLE
希望提供下载限速控制

### ISSUE THREAD

**Issue by EverHE** [proxyee-down-org/proxyee-down#279]
如题。

电脑硬盘IO较差，带宽又较大的时候。会占用大量磁盘IO,导致整个系统反映卡顿。
或者满速下载占满带宽，影响浏览网页。

**Comment by 14SHIKE** [comment]
可以修改分段数，控制下载速度，具体分多少，需要你测试

**Comment by BlackHole1** [comment]
新版已经修复
