### ISSUE TITLE
MAC下如何设置默认目录，我设置的失效。

### ISSUE THREAD

**Issue by Mrycp** [proxyee-down-org/proxyee-down#281]
mac下如何设置默认下载目录，我用脚本设置的不生效。会自动下载一个系统目录里。

**Comment by monkeyWie** [comment]
什么脚本设置？下载器默认会记录上一次的下载路径的

**Comment by Mrycp** [comment]
百度云盘PX-下载的脚本，下载百度云盘文件的时候有个PX-下载按钮，点击里面有个下载设置、PX-下载、PX-压缩下载三个选项。我点第一个的下载设置，输入下载路径，但是下载后没有存在我设置的文件夹。而下载器里没有地方设置下载路径。

**Comment by monkeyWie** [comment]
这个脚本不是我写的，建议你直接按这里的教程来下载。
