### ISSUE TITLE
打不开百度的所有网站

### ISSUE THREAD

**Issue by annemarchetta** [proxyee-down-org/proxyee-down#286]
### 相关日志

**Comment by ted423** [comment]
捂脸。。。那就是你代理把所有baidu.com都导到端口9999去了啊。
话说这个issue本身不该丢在这的。。。是你SwitchyOmega设置问题

**Comment by ted423** [comment]
理论上这么用就好了
*.baidupcs.com +9999

**Comment by Lan-megumi** [comment]
我这里是百度账户登录超时
然后刷新一下就有

**Comment by ted423** [comment]
发现原因了，软件是自动设置pac的。有时候，关闭软件（例如关机时）可能会没有把pac那块改回来，会导致IE包括win10的应用商店连接不了
