### ISSUE TITLE
无法正常打开百度云

### ISSUE THREAD

**Issue by AcquireKnown** [proxyee-down-org/proxyee-down#307]
### 问题描述(必要)
运行软件后，谷歌和火狐都无法正常打开百度云网站，始终在刷新,不知道是否在海外有关系，尝试过使用switch omega也没有用，但是前天的时候是能够打开的，但也是多次尝试之后才成功，现在一直刷新也没用，把软件关了之后才能打开百度云
### 相关日志

**Comment by monkeyWie** [comment]
页面提示什么？

**Comment by AcquireKnown** [comment]
是一直在加载，没有任何提示

**Comment by AcquireKnown** [comment]
![image](https://user-images.githubusercontent.com/32730772/39255110-541d0c3a-48de-11e8-9ec4-60ad1910858a.png)

**Comment by monkeyWie** [comment]
你代理怎么设置的？

**Comment by PaleMooon** [comment]
https://imgur.com/aOWrJJk
https://imgur.com/rtKBotd
嗅探模式-百度云，火狐打不开分享页面
改成全网，所有HTTPS网页如截图

http网页显示 
405 Not Allowed
bfe/1.0.8.13-sslpool-patch

**Comment by AcquireKnown** [comment]
我按照教程都试过，不使用switchOmega，只运行软件，打开百度云嗅探，一直加载，使用switchOmega，从教程里下的backup，然后选的自动，嗅探关闭或者打开，也是一直加载，谷歌和火狐都是同样的情况

**Comment by monkeyWie** [comment]
@PaleMooon 
教程里有提到火狐的证书需要另外安装，你都不看的吗
![image](https://user-images.githubusercontent.com/13160176/39309326-49090c10-499a-11e8-8dba-32cbfb5a12ac.png)

**Comment by monkeyWie** [comment]
@AcquireKnown 不用代理就能打开网页吗？

**Comment by JiataoWen** [comment]
同样的问题，一样是海外用户。switchOmega和软件一打开，百度云就一直加载。只有关闭后才能连接上

**Comment by AcquireKnown** [comment]
我昨天试了下，把之前的删掉，把代理也清掉，然后重新下载软件，再来一遍步骤，就可以打开并下载，然后今天打开软件之后，百度云网页又和之前一样了，一直加载不出来

**Comment by 14SHIKE** [comment]
国外的，应该先翻到内地，才能用吧
可以设置一下二级代理

**Comment by monkeyWie** [comment]
把油猴关了试试看
