### ISSUE TITLE
Mac版无法选择其它硬盘分区

### ISSUE THREAD

**Issue by 1900forever** [proxyee-down-org/proxyee-down#308]
### 问题描述(必要)
在Mac下无法选择/Users目录之外的路径。我有两块硬盘，想把文件下载到另一块硬盘上。
### 版本号(必要)
2.51
### 操作系统(必要)
macOS 10.15.4

**Comment by monkeyWie** [comment]
可以手动输入绝对路径

**Comment by 1900forever** [comment]
我知道可以手动，只是汇报一下不能点选其它分区
