### ISSUE TITLE
win10安装失败

### ISSUE THREAD

**Issue by wqw547243068** [proxyee-down-org/proxyee-down#327]
### 问题描述(必要)
win10油猴安装失败，老是弹窗
![image](https://user-images.githubusercontent.com/3257257/39426713-82d3da4e-4cb3-11e8-880e-6293b87d5985.png)

### 版本号(必要)
下载来源：https://greasyfork.org/zh-CN/scripts/23635-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B
### 操作系统(必要)
win10
### 相关截图
![image](https://user-images.githubusercontent.com/3257257/39426713-82d3da4e-4cb3-11e8-880e-6293b87d5985.png)

### 相关日志

**Comment by monkeyWie** [comment]
教程没说要装油猴啊

**Comment by 14SHIKE** [comment]
你添加的只是脚本，并不是油猴
可以看相关教程参考下
