### ISSUE TITLE
视频类文件解压极易文件损坏或视频卡顿。

### ISSUE THREAD

**Issue by Noel615** [proxyee-down-org/proxyee-down#328]

**Comment by Noel615** [comment]
补充一下： 不确定是否一定与文件类型有关，
上个月使用下载本子（大量图片）时 下载了3次才下好（部分文件损坏）

**Comment by hooboor** [comment]
@Noel615 
出现这种情况，可以这样来试着排除
1、下载文件确实存在问题；
2、如果视频可在线播放，试着在线播放看看是不是也是这种情况；
3、使用其他下载软件下载，看看问题是不是依旧；

**Comment by ted423** [comment]
版本号2.4.1？有试最新的么，百度网盘下载的？

**Comment by ted423** [comment]
我下载视频也遇到了，不大清楚是不是因为中间断过，换过连接
https://www.overwatchleague.cn/zh-cn/videos

**Comment by BlackHole1** [comment]
新版已经修复
