### ISSUE TITLE
这软件真坑啊，好不容易下载完成，合并解压又出先这个，气死了

### ISSUE THREAD

**Issue by huaijiuhun** [proxyee-down-org/proxyee-down#33]
这么多BUG就别发出来害人好不好啊！不然你会折寿的！
首先合并时空间不足会不停的重新合并，比如0-1G，没空间了，1G-0，无限循环。艹浪费时间，还好我仔细查了一下。
连个提示都没有，合并时也不能暂停。
空间腾出来了，合并完成，尼玛解压时又尼玛损坏文件，然后抱着侥幸心理去用什么云解压，4G多的解压了2G就完事了，这尼玛从下载时就已经出错了，折腾半天没卵子用。
作者赶快弃坑吧，别挂着支付宝圈钱坑人了，弄坏别人硬盘你还得赔钱。
真是日了狗，竟然用了这个软件。看到的别用了，还是用IDM去吧。

**Comment by monkeyWie** [comment]
哦 这个issue就不关了让大家围观下一个人的素质到底可以低到什么程度。

**Comment by fadewalk** [comment]
？？挺好用的啊

**Comment by Dave12138** [comment]
....吐槽下硬盘空间不够下载什么大文件.....

**Comment by binext** [comment]
有bug提bug，别一上来就乱叫，
大家围观下一个人的素质到底可以低到什么程度

**Comment by joshatt** [comment]
用了几天了,下载很多电影,还有批量, 没有一个合并有问题的, 比IDM靠谱多了.....有了一点问题就乱叫, 只能说没有素质

**Comment by BinarySatan** [comment]
喷啥子喷嘛，  你去fork一下，自己改好了 在pull上去， 这样对大家都好嘛~  你说是不是呢 ...?

**Comment by wtfgfw1984** [comment]
百度云会员，走好不送~

**Comment by geek4d** [comment]
还是没想通为啥这个人的硬盘分区可以满到这种程度，少下点大姐姐，小心肾亏

**Comment by zao123h** [comment]
这么厉害，请你写出没bug的软件啊。

**Comment by 0cean** [comment]
围观脑残。

**Comment by ttentau** [comment]
围观脑残。

**Comment by WangBo994** [comment]
围观

**Comment by caofengzi** [comment]
硬盤沒有空間了與軟件有什麼關係呢？

**Comment by yj21world** [comment]
这个人好厉害，可以代笔写政文了。

**Comment by kun95** [comment]
围观一下脑残 嘿嘿嘿

**Comment by BillCai06** [comment]
围观

**Comment by findagnar** [comment]
围观脑残。

**Comment by wuyanlin** [comment]
围观脑残

**Comment by dongxiansuixin** [comment]
github居然还有这种人，厉害厉害

**Comment by Mosney** [comment]
这种人居然还有GitHub账号

**Comment by NimaQu** [comment]
笑死，睿智人士

**Comment by jinjidecj** [comment]
= =

**Comment by Luluno01** [comment]
把github当小学生贴吧了

**Comment by YXCQU** [comment]
围观下，现在喷子都会上github了，厉害了啊

**Comment by linkinghack** [comment]
什么鬼，是谁在把github泄露给微博脑残了

**Comment by xchz** [comment]
扎心了  哈哈

**Comment by ted423** [comment]
还是关了吧，碍眼

**Comment by ghl143** [comment]
怪不得有的免费的好东西作者会寒心，这种败类

**Comment by zhanglhz** [comment]
我在mac和windows上用都没问题。首先用的人智商要够。

**Comment by lzhaoyang** [comment]
给hub主点赞，围观睿智。

**Comment by xchz** [comment]
@zhanglhz 就算有问题也不应该喷奥

**Comment by duanego** [comment]
牛逼呀大兄弟！

**Comment by DirtyBat** [comment]
围观脑残+1

**Comment by Apkme** [comment]
分享与不分享都在于作者个人意愿，既然都分享出来了，而且又没收费，没逼着你用。有BUG你issue反馈一下就好了，作者空了说不定还给修复一下。不但不报以感谢的态度，而是说一堆粗(ě)俗(xīn)的话。真不知道这种人是怎么有勇气说出这些话？。有本事有能耐自己也做一个出来，没有BUG，十分完美的东西拿出来分享还免费？
在我看来，既然使用人家的软件  就应当是默认了使用协议出了任何问题咱们也得遵守规矩来。
一个好工具不仅在于东西本身，还有使用者的(…)那个啥。有问题就喷，那你自己去修复吧。如果你能力强我给你拍巴巴掌，没那本事就别BB。
我不站在任何一方，只是作为客观的第三方看待这个问题了，兄弟们说呢？

**Comment by StriveCheng** [comment]
中国就是像你这种素质低下的人太多，自己不愿意分享，还喷分享的人，导致中国很多努力的开源作者无力维护。无耻的人不配使用开源的东西

**Comment by misaka10032w** [comment]
‘滑稽😏

**Comment by hautxuhaihu** [comment]
这种人还知道Github?我觉得github应该设立一种文明机制，大家一起举报这种没素质的人，封号，使这种人远离Github。同时，支持作者，作者的努力与付出很伟大，希望作者再接再厉，不要被一些事情坏了心情！

**Comment by 8023lsy** [comment]
围观

**Comment by jinfa11** [comment]
本来看看天天有人怼他挺可怜的，想说大家算了吧，又看了一遍他发的issue，这种人真的欠

**Comment by youyiqin** [comment]
这算找茬还是碰瓷?

**Comment by hcxin** [comment]
软件还没用，不过源码还是有很多值得学习的。

**Comment by TsukiSeele** [comment]
围观蝼蚁

**Comment by pedoc** [comment]
围观脑残+1
全球丢脸

**Comment by gnome-terminal** [comment]
好好做狗，别学人类用电脑

**Comment by BlackHole1** [comment]
没有必要再开这个issues了，免得带来负能量
