### ISSUE TITLE
mac系统证书安装失败没提示

### ISSUE THREAD

**Issue by gzlicanyi** [proxyee-down-org/proxyee-down#345]
### 问题描述(必要)
可能是新的mac系统，导致mac 系统安装证书失败没有提示？debug模式运行，看到并没有抛异常，最后只能自己手动加sudo安装证书
### 版本号(必要)
2.53
### 操作系统(必要)
10.13.3 (17D102)
### 相关截图
![image](https://user-images.githubusercontent.com/16240434/39661633-4d941a74-5087-11e8-8676-1047b752c4cc.png)
![image](https://user-images.githubusercontent.com/16240434/39661643-729350f6-5087-11e8-8e63-fa543f9f777d.png)

### 相关日志

**Comment by monkeyWie** [comment]
你可以打印下安装证书的命令看看
