### ISSUE TITLE
大佬，每次启动proxyee-down时需要输入密码，能记住密码吗？

### ISSUE THREAD

**Issue by man2018** [proxyee-down-org/proxyee-down#349]
大佬，每次都要手动输入密码，这个很麻烦啊，能加个记住密码的选项吗？
我用expect命令设置自动输入密码是失败的，因为expect无法指定新窗口来输入，只能指定固定窗口的

**Comment by monkeyWie** [comment]
是MAC系统吗

**Comment by man2018** [comment]
@monkeyWie 嗯。是mac系统的。我用expect这个命令指定自动输入密码时，当打开proxyee-down的star jar时会自动在终端添加一个exit，所以无法自动输入密码。。。。

**Comment by monkeyWie** [comment]
可以不用sudo运行就好了

**Comment by man2018** [comment]
@monkeyWie 是啊，现在proxyee-down启动需要输入sudo权限，如果不需要sudo就问题全解了

**Comment by monkeyWie** [comment]
你可以直接写个shell，不加sudo就好了

**Comment by man2018** [comment]
@monkeyWie 可以通过shell启动proxyee-down，但每次都要输入密码，这个我不会解决了。。。小白呀

**Comment by monkeyWie** [comment]
你把start这个文件用文本编辑器打开，把里面的sudo去掉就好
