### ISSUE TITLE
下载到97%没速度

### ISSUE THREAD

**Issue by github361** [proxyee-down-org/proxyee-down#353]
下载到97%就没速度，下不动了
2.44
win10 1803
![snipaste_20180507_182545](https://user-images.githubusercontent.com/33155648/39697617-15211658-5224-11e8-9f7c-fb34a7419c70.png)

**Comment by hooboor** [comment]
暂停再重新开始下载不行？

**Comment by xxxlfu** [comment]
不行，试了好几遍了

**Comment by monkeyWie** [comment]
试试刷新链接https://github.com/monkeyWie/proxyee-down/blob/master/.guide/common/refresh/read.md
