### ISSUE TITLE
使用2.53版打开百度网盘显示代理服务器拒绝连接

### ISSUE THREAD

**Issue by github361** [proxyee-down-org/proxyee-down#354]
使用2.53版，Firefox 59.3浏览器打开百度网盘显示代理服务器拒绝连接，关闭软件后再刷新百度网盘又能正常使用
2.53
win10 1803

![snipaste_20180507_183200](https://user-images.githubusercontent.com/33155648/39697851-f327ab1a-5224-11e8-825f-25772024f4aa.png)

**Comment by monkeyWie** [comment]
重启软件看看

**Comment by xxxlfu** [comment]
重启没用

**Comment by monkeyWie** [comment]
证书安装了吗
