### ISSUE TITLE
软件在运行时不定期弹出警告

### ISSUE THREAD

**Issue by verity886** [proxyee-down-org/proxyee-down#358]
### 相关截图
![default](https://user-images.githubusercontent.com/37663967/39747062-cb5c8492-52de-11e8-83cb-6f1721991c77.JPG)

### 相关日志

**Comment by monkeyWie** [comment]
浏览器弹的吗

**Comment by verity886** [comment]
应该不是，看起来像是系统的对话框@monkeyWie

**Comment by monkeyWie** [comment]
那是哪里弹的，下载器不会弹这个啊
