### ISSUE TITLE
开启防盗链了吗？

### ISSUE THREAD

**Issue by 1688pc** [proxyee-down-org/proxyee-down#359]
可怕，吃想越来越难看，百度你这是要赶尽杀绝的节奏么
{"error_code":31426,"error_msg":"hotlinking forbidden , hitcode:113","request_id":8728264119299058673}
https://pan.baidu.com/s/1u1nmmd7olnTfaTSJJIyhlQ#list/path=%2FProgram%20Files%2F%E5%86%B0%E7%82%B9%E6%96%87%E5%BA%93&parentPath=%2FProgram%20Files
单选一个文件无法下载，全选能下载速度很慢
![1](https://user-images.githubusercontent.com/14054316/39754095-a1301552-52f3-11e8-90d1-0bd175da7bed.PNG)

**Comment by hooboor** [comment]
@1688pc 
![ub o l pw agb c300](https://user-images.githubusercontent.com/3361746/39761375-8182de62-530a-11e8-878f-2dd52e751dce.png)
下载这个文件夹确实慢，平均100+k

**Comment by monkeyWie** [comment]
我测试了下你发的链接没问题啊，你是用脚本取的直链吗
![image](https://user-images.githubusercontent.com/13160176/39791989-038133c6-5371-11e8-8409-69b70b9ab6c1.png)

**Comment by 1688pc** [comment]
@monkeyWie 没有使用脚本，可能是ip被百度云检测到，也可能是win101803系统的问题

**Comment by monkeyWie** [comment]
你可以退出帐号下载试试

**Comment by canfily** [comment]
我也遇到了同样的问题，之前下载都好好的，现在突然之间就被卡了。
点击网盘下载按钮就出现
{"error_code":31426,"error_msg":"hotlinking` forbidden , hitcode:113","request_id":8822031221555361485}
这样一个东西
这个下载软件和另一个aria2都不能用来下百度网盘里面的东西了。

**Comment by BlackHole1** [comment]
过一段时间在试试。估计是百度封IP了
