### ISSUE TITLE
无法开启switchyomega proxyee-down代理

### ISSUE THREAD

**Issue by FQFQzzy** [proxyee-down-org/proxyee-down#362]
### win10 
[error.2018-05-09.log](https://github.com/monkeyWie/proxyee-down/files/1987832/error.2018-05-09.log)

**Comment by monkeyWie** [comment]
截个图看看

**Comment by FQFQzzy** [comment]
今天可以打开，但是很卡慢。会不会是因为我在国外的原因？

**Comment by monkeyWie** [comment]
@FQFQzzy 国外确实会有这个问题，目前也还没找到原因。可以先配合直链提取脚本来下载

**Comment by FQFQzzy** [comment]
直链提取脚本在哪里下载？

**Comment by olilili** [comment]
我也是 然后网页都打不开 不懂为什么

**Comment by monkeyWie** [comment]
用油猴的https://greasyfork.org/scripts/39776
