### ISSUE TITLE
通过proxyee-down下载文件，默认地址设置为download，download文件夹会由下载变为download

### ISSUE THREAD

**Issue by le-matin** [proxyee-down-org/proxyee-down#363]
### 问题描述(必要)
通过proxyee-down下载文件，默认地址设置为C:\Users\用户名\Downloads，用户文件夹下"downloads"文件夹在windows中为"下载"，proxyee-down下载文件后该文件夹会由"下载"变为"downloads"
已经测试过几个下载软件，发现是由proxyee-down导致。麻烦下版本中处理一下。谢谢
### 版本号(必要)
2.53
### 操作系统(必要)
windows 10
### 相关截图
下载前
![image](https://user-images.githubusercontent.com/39133320/39829593-8b3e6d08-53f1-11e8-9dbe-436ca7380de7.png)
下载后
![image](https://user-images.githubusercontent.com/39133320/39829782-0f3b3956-53f2-11e8-92e7-325f8142da5c.png)

### 相关日志

**Comment by ted423** [comment]
我这倒不会。。。我把下载挪到了F盘，但是proxyee-down默认还是放到user文件夹下

**Comment by le-matin** [comment]
你试试把设置为用户文件夹下，应该不是我是个例吧？

**Comment by ted423** [comment]
公司电脑确实显示是Downloads，不过我也没在意

**Comment by le-matin** [comment]
强迫症表示难以接受

**Comment by minipato** [comment]
强迫症目前只能 手动改回下载两字然后 右键-属性-自定义-更改图标-还原默认值

**Comment by dongxiansuixin** [comment]
好像qbittorrent也会出这个问题

**Comment by monkeyWie** [comment]
@le-matin 多谢提出的解决办法，以后加到程序里去
