### ISSUE TITLE
在macos 13.3中顶部托盘未出现，试了三台电脑均未出现

### ISSUE THREAD

**Issue by bingcheng1998** [proxyee-down-org/proxyee-down#366]
### 相关日志

**Comment by monkeyWie** [comment]
跟bartender有冲突，你是不是装了这个

**Comment by bingcheng1998** [comment]
对的，关了还是没有

**Comment by BlackHole1** [comment]
目前还是没有么？

**Comment by bingcheng1998** [comment]
2.54没有提示，我试了2.53，有了提示：

![提示](https://ws1.sinaimg.cn/large/006tNbRwly1fu4goov06vj30ge09a3ys.jpg)

safari，Chrome，都没有显示proxyee的标志，都不能下载。

![我的系统](https://ws2.sinaimg.cn/large/006tNbRwly1fu4gqtpa23j30wk0jowhm.jpg)

**Comment by BlackHole1** [comment]
好的。 @monkeyWie

**Comment by BlackHole1** [comment]
已经加入3.0待修复版本

**Comment by monkeyWie** [comment]
试试3.0版本
