### ISSUE TITLE
下载文件的文件名错位了

### ISSUE THREAD

**Issue by foolfsh** [proxyee-down-org/proxyee-down#368]
在百度盘下了一部电视剧 网盘里的集数都是没问题的 但是下载后看这个视频集数全部错乱了。就是比如网盘里的文件名是第30集的那打开后就是第30集  但是下载后文件名显示的是第30集但实际确是其它集数  一般是同时添加下载的那几个视频文件名互相错位  比如同时添加下载的是27 28 29 30这四集，文件名就是这几集之间互相错位   文件没重复就是文件名好像对不上 就今天下的这个电视碰到这个问题   确定网盘那边的文件没问题

**Comment by ted423** [comment]
这估计还是百度本身的问题吧..............毕竟是百度进行的打包。除非解压缩的时候把文件名弄混，但一般不大可能出这个问题。请确定，下载的压缩文件里文件是否是正常的，再单独下载第30集到电脑上看看。

**Comment by monkeyWie** [comment]
用什么软件解压的？
