### ISSUE TITLE
建议解压的时候改为解压到当前文件夹

### ISSUE THREAD

**Issue by zhuxiaoxi** [proxyee-down-org/proxyee-down#382]
建议解压的时候改为解压到当前文件夹，而不是与下载文件同名文件夹。当下载文件夹`A/Vidoe.mp4`的时候，会下载`A.zip`，解压后就变成了`A/A/Video.mp4`。希望可以直接解压成`A/Video.mp4`

**Comment by BlackHole1** [comment]
这个如果后期有时间，我们优化此问题，感谢反馈

**Comment by monkeyWie** [comment]
这是按zip里的目录结构解压的
