### ISSUE TITLE
没什么问题。就想提个建议

### ISSUE THREAD

**Issue by mysq1isworst** [proxyee-down-org/proxyee-down#391]
### 问题描述(必要)
能不能加入随开机自动启动的功能，每次还要自己去打开，好麻烦
### 版本号(必要)
2.54
### 操作系统(必要)
win10 64位 教育版
### 相关截图
无
### 相关日志
无

**Comment by pe200012** [comment]
其实你可以用计划任务......

**Comment by BlackHole1** [comment]
可以参考 @pe200012 以及 @chengchunkit 的解决方案
