### ISSUE TITLE
调整UI字体大小，在设置面板里增加字体大小选项

### ISSUE THREAD

**Issue by SunshineExpress** [proxyee-down-org/proxyee-down#395]
分辨率1920*1080，125%缩放，不最大化显示不下大部分内容。建议添加UI字体大小调节功能。

**Comment by BlackHole1** [comment]
方便截图么？

**Comment by SunshineExpress** [comment]
![screenshot](https://user-images.githubusercontent.com/22676175/40694652-205da6b6-63f0-11e8-8693-014f1a4e58c0.png)
我觉得字体可以再缩小两个号
