### ISSUE TITLE
桌面目录变成Desktop

### ISSUE THREAD

**Issue by Colinelleo** [proxyee-down-org/proxyee-down#397]
如果我把下载路径设置为桌面，那在下载后我的桌面显示名称会变Desktop。我也检查过desktop.ini文件，内容并没改变。恢复名称为桌面的方法也很简单，只需要把系统桌面指向改个路径再改回来就正常了。
程序版本：2.44-2.54的所有版本。
系统：windows10 专业版 x64 版本号17134

**Comment by BlackHole1** [comment]
这个问题，确实存在。我们正在努力的修复

**Comment by monkeyWie** [comment]
3.0已经修复
