### ISSUE TITLE
添加任务以后一直在pending

### ISSUE THREAD

**Issue by gaarasama1221** [proxyee-down-org/proxyee-down#400]
### 相关日志

**Comment by BlackHole1** [comment]
请问现在问题解决了吗？可以提供相关的下载链接及日志文件么

**Comment by gaarasama1221** [comment]
现在还是这种情况，无论下载什么链接，那个Java都不会自动弹出，得把其他软件都最小化了才可以。而且会一直在这个界面（见附件图片）。估摸着时间差不多了，重启软件，下好的文件就显示在Java里了。
请问日志文件从哪里找到？

**Comment by monkeyWie** [comment]
重新下载安装一遍试试看
