### ISSUE TITLE
这个软件不是Java写的吗，为啥下载下来运行文件为exe而不是jar

### ISSUE THREAD

**Issue by 958640368** [proxyee-down-org/proxyee-down#401]
这个软件不是Java写的吗，为啥下载下来运行文件为exe而不是jar

**Comment by 958640368** [comment]
这个软件不是Java写的吗，为啥下载下来运行文件为exe而不是jar

**Comment by hcxin** [comment]
@958640368 用命令打包的windows下的可执行文件，参考 http://javafx-maven-plugin.github.io/
