### ISSUE TITLE
局域网浏览文件系统目录漏洞？

### ISSUE THREAD

**Issue by SunshineExpress** [proxyee-down-org/proxyee-down#405]
访问浏览器UI界面没有任何认证手段，可在同一局域网下任意一台计算机进入，创建下载任务，浏览文件系统目录等。

**Comment by ted423** [comment]
试了下，确实。

**Comment by monkeyWie** [comment]
下个版本修改成监听127.0.0.1吧。

**Comment by ted423** [comment]
但是个人觉得，有些人也可能会需要局域网内添加任务

**Comment by SunshineExpress** [comment]
可以加入登录认证功能吗？就像无线路由器那样。

**Comment by monkeyWie** [comment]
默认127.0.0.1 可配置成开发局域网。这样应该可以吧
