### ISSUE TITLE
在QQ浏览器10 中一直弹出浏览器的下载对话框

### ISSUE THREAD

**Issue by lyuewei** [proxyee-down-org/proxyee-down#406]
问题描述：在在QQ浏览器10 当中，点击下载弹出的是浏览器的下载对话框，而不是proxyee-down的。如果下载的是文件夹，复制浏览器的下载对话框的下载地址到proxyee-down可以正常下载，当下载的是文件的话，复制下载地址到proxyee-down就一直下载到403.html文件
版本号：:2.54
操作系统：win7
 相关截图
 相关日志

**Comment by BlackHole1** [comment]
请问问题解决了么？如果没有可以提供相关的受下载链接及日志文件么

**Comment by monkeyWie** [comment]
参考下FAQ第一点。
