### ISSUE TITLE
mac 出现 command not found 问题，无法启动应用

### ISSUE THREAD

**Issue by 164738777** [proxyee-down-org/proxyee-down#413]
### 问题描述(必要)
Mac 正确输入密码后出现command not found 问题，然后无法启动应用了。
### 版本号(必要)
2.54
### 操作系统(必要)
Mac 10.13.3
### 相关截图
<img width="566" alt="2018-05-24 9 40 55" src="https://user-images.githubusercontent.com/21001567/40489384-880f94da-5f9b-11e8-8b18-9f80fc7537f7.png">

### 相关日志
main文件夹下没有log日志文件

**Comment by 164738777** [comment]
就是正常下载的mac包，然后解压，看到目录下也有java，就是不清楚为毛还说找不到命令。
目录也是全英文

**Comment by itblingfeng** [comment]
你试下 ./jre1.8.0_162/Contents/Home/bin/java -version 看看有没有版本号输出，如果有的话。因该是sudo命令的问题

**Comment by 164738777** [comment]
@itblingfeng 有版本号输出
<img width="571" alt="2018-05-25 12 22 28" src="https://user-images.githubusercontent.com/21001567/40498939-0a3e62da-5fb3-11e8-9102-c373a362a374.png">
那是需要怎么解决呢？

**Comment by monkeyWie** [comment]
怎么看起来多了:号啊

**Comment by monkeyWie** [comment]
要不重新下载并解压再试试，还不行的话等新版本吧。3.0版本MAC会打包成原生的.app程序

**Comment by 164738777** [comment]
@hvaggg 目前我重新下载解压也是这个问题，应该只能等3.0版本了。

**Comment by xuchaofei** [comment]
我估计也是  等等吧  真心解决不了

**Comment by monkeyWie** [comment]
3.0版本已出
