### ISSUE TITLE
批量下载文件名出错

### ISSUE THREAD

**Issue by bobcvx** [proxyee-down-org/proxyee-down#414]
批量下载后文件名称颠倒
### 相关截图
下载后名称
![2018-05-25_015437.png](http://s8.img26.com/2018/05/25/2018-05-25_015437.png)
百度云名称
![2018-05-25_015452.png](http://s9.img26.com/2018/05/25/2018-05-25_015452.png)
### 相关日志

**Comment by monkeyWie** [comment]
用的px插件下载的吗

**Comment by paul131130** [comment]
好像是文件大小属性错位了

**Comment by bobcvx** [comment]
对，就是px下载的
![2018-05-25_150543.png](http://s16.img26.com/2018/05/25/2018-05-25_150543.png)
![2018-05-25_150600.png](http://s18.img26.com/2018/05/25/2018-05-25_150600.png)

**Comment by monkeyWie** [comment]
px插件有问题。可以联系那个作者
