### ISSUE TITLE
启动程序自动更改IE代理设置，退出则不还原

### ISSUE THREAD

**Issue by gsdagsa** [proxyee-down-org/proxyee-down#415]
启动程序自动更改IE代理设置，退出则不还原
![_20180525092844](https://user-images.githubusercontent.com/20218458/40521456-56870a7a-5ffe-11e8-8411-d498626244ea.png)

**Comment by monkeyWie** [comment]
是正常退出吗？

**Comment by ted423** [comment]
印象里有几次关机后再重启是这样

**Comment by archiezhie** [comment]
我也是这样。
