### ISSUE TITLE
下载错误+压缩错误

### ISSUE THREAD

**Issue by wth461694678** [proxyee-down-org/proxyee-down#417]
-->
### 问题描述(必要)
1.点击下载后弹出网页表示出现错误，另外软件未出现下载窗口
2.下载下来的压缩包13G，解压后只有12G
### 版本号(必要)
2.54
### 操作系统(必要)
Mac
### 相关截图
1.![8cb930b9-dcf8-4e79-af6f-fd3977f010e9](https://user-images.githubusercontent.com/39629728/40555572-2501c67e-607c-11e8-8fb0-fa569e51cbc1.png)
2.由于解压后文件已彻底删除 未保留图片
### 相关日志
P.S. 在设置中能否添加一条下载完成后是否解压？对于不需要解压的用户，每次在新建任务里去掉还是有点麻烦

**Comment by authwork** [comment]
多谢作者提供这么一个好用的工具。
在我的使用中，我发现下载7z压缩包文件会出现下载完后无法打开的情况, 我尝试过一下方案:
1. 下载小于200M的7z包
2. 下载大于2G的7z包
3. 将200M的7z包和90M的rar包进行批量下载，使用百度云工具解压后，rar包可以正常打开，但是7z包不行。
不知大家是否有什么解决方案？
然后还有一个问题就是，使用该工具会不会设计到P2P下载？(因为我注意到有一定程度的上传数据，因为海外对P2P管得比较严)

Many thanks

**Comment by monkeyWie** [comment]
@wth461694678 关于自动解压相关的issue已经有很多了，参考https://github.com/proxyee-down-org/proxyee-down/issues/288

**Comment by monkeyWie** [comment]
@authwork 应该和7z没有关系啊，没用到p2p下载，看到的上传数据都是本地的数据只是UI获取进度的上传数据
