### ISSUE TITLE
###I can not find the proxyee-down-x.xx-mac.zip,I want to download it.

### ISSUE THREAD

**Issue by kirintwodog** [proxyee-down-org/proxyee-down#418]
### 相关日志

**Comment by BlackHole1** [comment]
**download:**
https://imhx-my.sharepoint.com/personal/pd_imhx_onmicrosoft_com/Documents/Forms/All.aspx?slrid=ff426b9e%2Da0c5%2D0000%2D0801%2D8b393915c462&FolderCTID=0x012000536DC31294EC264084FE880734F95AEA&id=%2Fpersonal%2Fpd%5Fimhx%5Fonmicrosoft%5Fcom%2FDocuments%2Fproxyee%2Ddown%2F2%2E54
