### ISSUE TITLE
proxyee-down-x.xx-mac.zip

### ISSUE THREAD

**Issue by kirintwodog** [proxyee-down-org/proxyee-down#419]
### 相关日志

**Comment by kirintwodog** [comment]
I can't find the proxyee-down-x.xx-mac.zip, I want to download it.
10.13.4
Mac

**Comment by BlackHole1** [comment]
https://imhx-my.sharepoint.com/personal/pd_imhx_onmicrosoft_com/Documents/Forms/All.aspx?slrid=eb426b9e%2D906e%2D0000%2D0801%2D8ef4a0dac62f&FolderCTID=0x012000536DC31294EC264084FE880734F95AEA&id=%2Fpersonal%2Fpd%5Fimhx%5Fonmicrosoft%5Fcom%2FDocuments%2Fproxyee%2Ddown%2F2%2E54%2Fproxyee%2Ddown%2D2%2E54%2Dmac%2Ezip&parent=%2Fpersonal%2Fpd%5Fimhx%5Fonmicrosoft%5Fcom%2FDocuments%2Fproxyee%2Ddown%2F2%2E54
