### ISSUE TITLE
速度显示错误

### ISSUE THREAD

**Issue by 1357310795** [proxyee-down-org/proxyee-down#420]
### 问题描述(必要)
软件界面速度一栏始终为0（如图前3个任务），但实际有速度（进度条在动）。
重启软件后正常。
### 版本号(必要)
2.54
### 操作系统(必要)
win7 x64
### 相关截图
![default](https://user-images.githubusercontent.com/35869804/40572753-1f8722d2-60e7-11e8-811f-b5a234765c38.PNG)

### 相关日志
无

**Comment by PaleMooon** [comment]
我也有个速度显示的错误。
实际下载速度是6M+，网卡占用和路由器都看了。
软件里却显示速度8M+

**Comment by BlackHole1** [comment]
3.0将会修复
