### ISSUE TITLE
Mac系统下载完成之后找不到文件

### ISSUE THREAD

**Issue by UniKoA** [proxyee-down-org/proxyee-down#421]
### 问题描述  
下载完之后通过软件打开文件夹之后没有任何文件

### 版本号
2.54

### 操作系统
Mac

### 相关截图
<a href="http://tinypic.com?ref=2natdmc" target="_blank"><img src="http://i68.tinypic.com/2natdmc.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

### 相关日志

**Comment by BlackHole1** [comment]
你当前用户是否为Guest？

**Comment by Xiaosehu** [comment]
改一下文件夹的用户权限就行
![qq20180528-0](https://user-images.githubusercontent.com/39693812/40606890-6876ba6c-6299-11e8-9f4e-a696a29ac09a.jpg)
