### ISSUE TITLE
开发问题：设计缺陷

### ISSUE THREAD

**Issue by LEXUGE** [proxyee-down-org/proxyee-down#423]
是不是在每一个任务中伴随着其它分段一个个的下载完成，总速度就会下降，最后一段的下载体验总是差强人意。可否在这种情况下再对剩余内容进行拆分，始终保持大量的活跃分段以提高速度？

**Comment by monkeyWie** [comment]
新版本正在优化下载的算法，到时候下载完的连接会来支持其他没下完的连接
