### ISSUE TITLE
proxyee-down Windows下非正常关闭程序后出现网页访问不了的问题

### ISSUE THREAD

**Issue by liabco** [proxyee-down-org/proxyee-down#424]
### 问题描述(必要)
程序非正常关闭程序后出现网页访问不了的问题——关机
出现问题后再开程序然后右键退出，网页就能访问了（看了下IE的代理，是没开的）
### 版本号(必要)
2.53
### 操作系统(必要)
windows10 1803（17134.48）
### 相关截图
![image](https://user-images.githubusercontent.com/10543023/40581856-771e4260-6195-11e8-838c-e70501946f0b.png)

### 相关日志 #

**Comment by monkeyWie** [comment]
非正常关闭，系统(IE) http代理服务器设置不会正常还原的。这个是正常情况
