### ISSUE TITLE
嗅探到任务、弹出下载窗口时文件名里中文无法显示，只有占位空格；开始下载后程序立即闪退

### ISSUE THREAD

**Issue by devcon** [proxyee-down-org/proxyee-down#425]
### 相关日志 [hs_err_pid17912.log](https://github.com/proxyee-down-org/proxyee-down/files/2043738/hs_err_pid17912.log)

**Comment by monkeyWie** [comment]
有任务的下载地址吗

**Comment by devcon** [comment]
我试图重现问题，这次是将能用的2.41版整个目录更名、最新的2.54解压在全新目录里启动，提示需要删除再重新导入证书，完成后下载任务正常，再无闪退；而之前是直接讲2.54覆盖在2.41的目录下，可能与此有关系。
