### ISSUE TITLE
UI改进建议：自动隐藏已经下载完成的分块

### ISSUE THREAD

**Issue by nukewarrior** [proxyee-down-org/proxyee-down#426]
### 问题描述(必要)
UI改进建议：自动隐藏已经下载完成的分块
### 版本号(必要)
2.54
### 操作系统(必要)
win10 76 pro
### 相关截图
![_20180528155658](https://user-images.githubusercontent.com/10683831/40604085-81a11df6-6290-11e8-867c-9c1dc81758db.png)

最后感谢作者带来的这个非常好用的软件，谢谢！

**Comment by monkeyWie** [comment]
谢谢你提供的建议，不过我觉的这个改进意义不大现阶段还是先把功能完善。
