### ISSUE TITLE
断电之后失去下载进度

### ISSUE THREAD

**Issue by BGMjie** [proxyee-down-org/proxyee-down#427]
### 问题描述(必要)
突然断电之后，重启发现丢失文件下载进度，所有东西需要重新下载
### 版本号(必要)
2.5.4
### 操作系统(必要)
WIN10
### 相关日志
日志文件约有20M不能上传，能否留下你们的邮箱让我发邮件？

**Comment by BlackHole1** [comment]
可以先发到我的邮箱:158blackhole@gmail.com

**Comment by BlackHole1** [comment]
很抱歉，现在才回复，请问问题解决了么。如果日志还有保留，可以发到`158blackhole@gmail.com`邮箱
