### ISSUE TITLE
希望增加网络位置的支持

### ISSUE THREAD

**Issue by ted423** [proxyee-down-org/proxyee-down#428]
电脑上是有挂网络路径的，用这个软件会无法选择
![image](https://user-images.githubusercontent.com/7042766/40632966-c8d6f40a-631e-11e8-84e6-6d3d9935d718.png)

**Comment by BlackHole1** [comment]
@monkeyWie 可以参考你之前的弹窗选择下载位置，可以解决'桌面'文件名变化的问题，还能使用网络位置

**Comment by monkeyWie** [comment]
3.0已支持
