### ISSUE TITLE
其他菜单点击都是在原tab页，工具菜单每次都会打开新的tab页

### ISSUE THREAD

**Issue by huangjun6** [proxyee-down-org/proxyee-down#429]
### 问题描述(必要)
其他菜单点击都是在原tab页，工具菜单每次都会打开新的tab页
### 版本号(必要)
2.54
### 操作系统(必要)
win7
### 相关截图
![image](https://user-images.githubusercontent.com/8352667/40642382-9000e33a-634f-11e8-8224-dfa01b0c34c2.png)
### 相关日志

**Comment by BlackHole1** [comment]
这个bug确实存在，我会在开发版本上进行修复

**Comment by monkeyWie** [comment]
这个其实不算bug，有意为之的
