### ISSUE TITLE
百度网盘无法下载大文件

### ISSUE THREAD

**Issue by wsysl1989** [proxyee-down-org/proxyee-down#430]
### 相关日志

**Comment by ted423** [comment]
来个截图看看？

**Comment by BendMoly** [comment]
我下载安装完后也尝试了一下，小文件基本直接外链下载，但是大文件，超过100M就不行了

**Comment by ted423** [comment]
这是百度禁了大文件下载，需要脚本解决，跟这个软件没关系

**Comment by BlackHole1** [comment]
请尝试使用[EX[(https://github.com/gxvv/ex-baiduyunpan/)脚本来获取下载链接。

**Comment by monkeyWie** [comment]
参考FAQ 第一个点
