### ISSUE TITLE
有没有办法可以不安装插件使用

### ISSUE THREAD

**Issue by badlyenglish** [proxyee-down-org/proxyee-down#431]
用了几台电脑做试验，有几台直接可以使用不需要安装swithomage插件，但是有台就不行，由于安装插件后不能正常浏览网页，要来回切换。所以想问下，这到底是哪方面的区别，有没有可以不安装插件的解决办法，毕竟插件只支持chrome，如果用IE或者微信直接打开链接就没法下载了！
谢谢大神回答

**Comment by zjn225** [comment]
确实好奇怪，我这台也不用安装插件。我也不知道这个插件有何意义。

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/40696097-e317d8ce-63f6-11e8-9595-e73842734b70.png)

**Comment by badlyenglish** [comment]
改变嗅探模式没什么用，什么办法都用了，就是必须装插件，但是有几台，直接解压就可以用了，不用安装swithomage

**Comment by badlyenglish** [comment]
其实，插件安装不麻烦，就是切换模式麻烦，另外只是安装插件的话，IE和微信直接打开的链接不能支持，好想研究出不用安装插件的电脑里是多了什么

**Comment by ted423** [comment]
嗅探模式就是改IE的代理信息，如果chrome没改什么的话也是跟着走IE 。swithomage就是代理的扩展，装了后chrome就不走IE的代理信息了

**Comment by badlyenglish** [comment]
哦哦哦，懂了，但是我改了嗅探模式，仍然没有用，IE的代理信息看过是跟我不用安装插件的电脑是一样的，chrome也没改什么，应该是跟着IE走，所以也就是两个都不能用，感谢大神
