### ISSUE TITLE
能不能手动指定本地jre？？

### ISSUE THREAD

**Issue by tyc600** [proxyee-down-org/proxyee-down#433]
原程序本来很小巧的，但是包含了一个jre，体积剧增了几十倍吧。
再者，不少机器上本来就已经安装的jre的，没必要再次下载这个打包的jre。
能不能在下个版本内置一个ini文件，来手动定位bin文件夹或者java.exe，来调用本地的jre，
当然作者可提示兼容性最佳的jre版本以确保功能正常。

### 相关日志

**Comment by Edinjohn** [comment]
同问

**Comment by monkeyWie** [comment]
可以啊 下载jar包手动运行就好了

**Comment by SciUnivMoring** [comment]
能啊，在命令行里输入
` jre地址 -jar proxyee-down.jar`
就OK
