### ISSUE TITLE
linux下出现无响应现象

### ISSUE THREAD

**Issue by shanghj01** [proxyee-down-org/proxyee-down#437]
因反馈问题不清楚，所以更正反馈。
反馈（1）程序运行反馈。用java -jar pro..启动后可正常运行，但右键UI模式选择“浏览器”后出现浏览器中并无相关页面，并且右键程序图标也无任何响应，同时再次运行指令提示端口占用。

反馈（2）SwitchyOmega配置反馈。用SwitchyOmega这个软件，配置完全按照安装文档配置，但是在访问度盘相关的页面会出现资源未加载（***.baidu.com资源未加载在SwitchyOmega中显示**，**页面显示加载列表失败**）现象。不管是否登录账户都会出现。并且极易出现“隐私设置错误”问题，具体显示为：

>  您的连接不是私密连接
> 攻击者可能会试图从 pan.baidu.com 窃取您的信息（例如：密码、通讯内容或信用卡信息）。了解详情
> NET::ERR_CERT_INVALID
> Subject: pan.baidu.com
> 
> Issuer: ProxyeeRoot
> 
> Expires on: 2028年5月29日
> 
> Current date: 2018年6月3日

**并且chrome中无其他并行代理插件。**

**Linux版本：Ubuntu16.04lts-64bit
Java版本：java-se1.8-64bit
chrome版本：66.0.3359.139-1
Proxy SwitchyOmega版本：Proxy SwitchyOmega 2.5.9 下载于谷歌商店。**

_对于首次反馈不清楚造成的困扰我在此表示抱歉。
很感谢作者可以开发出这样的软件并进行无偿共享。_

**Comment by ted423** [comment]
都用linux了......不给具体是哪个linux，不给版本号的么。。。。

**Comment by BlackHole1** [comment]
是否可以提供，java环境、linux发行版、linux发行版版本号、日志等相关可以帮助到你的东西。并且有没有尝试使用sudo来尝试。

**Comment by shanghj01** [comment]
Ubuntu16.04lts，Java1.8。以普通用户安装在普通用户个人的home文件夹下。

**Comment by BlackHole1** [comment]
因最近比较忙，月底左右我会对此bug进行复现，不知是否可以？

**Comment by BlackHole1** [comment]
您好，我复现了一下，并没有成功复现此问题。请问现在好了么？
