### ISSUE TITLE
Dock栏的图标可以增加一个吗？

### ISSUE THREAD

**Issue by kuangshenyan** [proxyee-down-org/proxyee-down#438]
### Mac OS X 10.13.3

**Comment by BlackHole1** [comment]
Mac上的Dock不是可以直接拖拽进行添加么。而图标也是可以进行自定义改变的。如果你是想问有没有软件的logo的话，那附上一张：

![](https://avatars0.githubusercontent.com/u/39588481?s=200&v=4)
