### ISSUE TITLE
下载分享中的文件

### ISSUE THREAD

**Issue by juwen** [proxyee-down-org/proxyee-down#443]
可以增加下载分享中的文件功能吗，这样就不用先转存到自己网盘，再下载了。

**Comment by juwen** [comment]
@BlackHole1 你是说这个脚本吗？https://greasyfork.org/zh-CN/scripts/39776
还是还有其他脚本？

**Comment by BlackHole1** [comment]
我用的是这个：[EX](https://greasyfork.org/zh-CN/scripts/26638-ex-%E7%99%BE%E5%BA%A6%E4%BA%91%E7%9B%98)

**Comment by monkeyWie** [comment]
本来就支持下载分享的资源啊，而且就是建议不要登录自己的账号下载

**Comment by juwen** [comment]
我是说群组里分享的文件，不是别人通过链接分享的文件

**Comment by monkeyWie** [comment]
这个是不支持，看看可以转存出来下载吗
