### ISSUE TITLE
下载后没有自动解压，手动解压报错

### ISSUE THREAD

**Issue by RIIYN** [proxyee-down-org/proxyee-down#446]
### 问题描述(必要)
下载时已经选择了自动解压选项，但是没有自动解压，选择下载器自带的解压工具报错，无法解压
### 版本号(必要)
2.54
### 操作系统(必要)
win10
### 相关截图
![image](https://user-images.githubusercontent.com/31130403/40884183-bf46729a-6741-11e8-93d9-dbb68e490f47.png)
### 相关日志

**Comment by monkeyWie** [comment]
不是批量下载的zip文件吧？

**Comment by RIIYN** [comment]
是批量下载的，91个G的文件

**Comment by monkeyWie** [comment]
那可能是损坏了，可以用winrar解压试试，可能能抢救下来一点。 不行的话只能重新下载了，建议分多个任务下载

**Comment by RIIYN** [comment]
WinRAR解压的打不开，只解压了一点点，重新下了
