### ISSUE TITLE
关于对多线路的支持问题

### ISSUE THREAD

**Issue by BGMjie** [proxyee-down-org/proxyee-down#447]
### 问题描述(必要)
我是校园网，然后我使用爱快软路由进行多重认证达到增加网速的目的，现在使用的是两个账号的拨号。单个账号拨号的极限速度是2.5M/s，双拨理论极限速度是5M/s。但是好像您这个软件对于双拨不太友好，并不能完美利用起这些网速。往往这个软件最多能跑满一条线路的网速，然而迅雷对于这一方面做的比较好，可以跑满网速达到4.5M/s。希望能更新一下此功能，让软件更强大！
这里是我学习爱快多重拨号的网站：https://blog.csdn.net/u011373710/article/details/54379794
![qq 20180604135540](https://user-images.githubusercontent.com/38123875/40900792-e5e01b04-67ff-11e8-9eda-01a241ed5398.png)
![qq 20180604135913](https://user-images.githubusercontent.com/38123875/40900793-e60f1d46-67ff-11e8-9757-1c6b3d5a96bd.png)
![qq 20180604135941](https://user-images.githubusercontent.com/38123875/40900794-e63ec528-67ff-11e8-8997-2eb281690267.png)
![qq 20180604135954](https://user-images.githubusercontent.com/38123875/40900795-e66f5f6c-67ff-11e8-90fe-8385eeccba1e.png)
![qq 20180604140029](https://user-images.githubusercontent.com/38123875/40900796-e6b0eb6c-67ff-11e8-9a7d-e55762643dcf.png)

### 版本号(必要)
2.54
### 操作系统(必要)
WIN10
### 相关截图

![qq 20180604135913](https://user-images.githubusercontent.com/38123875/40900793-e60f1d46-67ff-11e8-9757-1c6b3d5a96bd.png)
![qq 20180604135941](https://user-images.githubusercontent.com/38123875/40900794-e63ec528-67ff-11e8-8997-2eb281690267.png)
![qq 20180604135954](https://user-images.githubusercontent.com/38123875/40900795-e66f5f6c-67ff-11e8-90fe-8385eeccba1e.png)
![qq 20180604140029](https://user-images.githubusercontent.com/38123875/40900796-e6b0eb6c-67ff-11e8-9a7d-e55762643dcf.png)

### 相关日志

**Comment by ted423** [comment]
想问下你这个是从速度来判断是否使用了两条线路么？个人感觉......不是很准，虽然近期没有下载百度网盘的东西，但实际上下百度的东西很少能达到1M的，特别是稍微大点的文件

**Comment by BGMjie** [comment]
百度云下载单文件可以达到1M/S
但是有文件夹的就会限制速度
我在下载东西的时候能感觉到网速没有占满，但是我液说不清楚为什么没占 满。

**Comment by monkeyWie** [comment]
这应该是下载资源的问题，参考FAQ 百度云下载速度太慢的问题
https://github.com/monkeyWie/proxyee-down/blob/master/.guide/FAQ.md

**Comment by BGMjie** [comment]
我感觉不是的，我这个按连接分的话，每个任务几十个分段（连接），按照连接数进行负载均衡的时候，这几十个连接就会只在一条线路里进行传输，而不是会到另外一个线路。
