### ISSUE TITLE
mac版本start点开之后没有启动

### ISSUE THREAD

**Issue by xihuanwang** [proxyee-down-org/proxyee-down#448]
### 操作系统－macos
![2018-06-04 21 42 55](https://user-images.githubusercontent.com/39913402/40921883-524504e6-67d6-11e8-93b7-a9648a6a5ca2.png)

**Comment by monkeyWie** [comment]
密码输入了吗

**Comment by leyle** [comment]
需要注意那个 start 脚本里面的，java 路径，他是写死了的，但是很有可能你的 java 不是那个路径
你可以先尝试一下 sudo  java -jar 文件名

**Comment by xihuanwang** [comment]
密码输了的，就是没有弹出安装成功的提示

**Comment by BlackHole1** [comment]
重新开启此问题

**Comment by monkeyWie** [comment]
下载3.0版本吧
