### ISSUE TITLE
视频类文件解压失败

### ISSUE THREAD

**Issue by qingjun6093** [proxyee-down-org/proxyee-down#449]
### win7
###首先膜拜大佬,最初这么给力的软件,我一度以为我可以抛弃百度云了. 当时没截图,我下载了3部网上的学习资源,有一步可以正常解压,另外一步部分能解压,还有一部根本解压不了.但是我在百度云下载,却可以正常解压,虽然速度可怕.
### 无日志

**Comment by monkeyWie** [comment]
用了下载器自带的解压工具吗？
