### ISSUE TITLE
启动无反应

### ISSUE THREAD

**Issue by neko-para** [proxyee-down-org/proxyee-down#451]
### 问题描述(必要)
使用java -jar proxyee-down.jar启动后直接退出,无任何窗口/托盘图标出现,无滞留java进程
### 版本号(必要)
2.54
### 操作系统(必要)
ubuntu 18.04 LTS x64
openjdk version "10.0.1" 2018-04-17
### 相关截图
![2018-06-05 18-34-32](https://user-images.githubusercontent.com/26452623/40971122-2c86b4ce-68ef-11e8-8e24-288730e88e74.png)
### 相关日志
无

**Comment by monkeyWie** [comment]
用Oracle jdk就行，或者安装javafx
