### ISSUE TITLE
设置同时下载的数量

### ISSUE THREAD

**Issue by SplitGemini** [proxyee-down-org/proxyee-down#455]
#### 想提供一点建议
1.希望能够设置同时下载的数量，如果有几十个等待下载的文件而且无人值守就只能全部一起同时下载了
2.如果可以克服百度多文件下载pack压缩包的问题就好了，这样就不需要下载完成后的解压步骤（虽然知道如果可以的话现在何必要加个解压步骤），就是给点鼓励
最后，软件非常棒
### 操作系统(必要)
Windows 10专业版（1803）
### 相关日志

**Comment by monkeyWie** [comment]
等3.0版本吧

**Comment by monkeyWie** [comment]
3.0已经支持
