### ISSUE TITLE
ubuntu16.04证书无效问题

### ISSUE THREAD

**Issue by 492162921** [proxyee-down-org/proxyee-down#456]
### 证书无效问题
 
下载 [百度云 proxyee-down-2.54-jar.zip](https://pan.baidu.com/s/1fgBnWJ0gl6ZkneGkVDIEfQ#list/path=%2Fproxyee-down%2F2.54)
使用的环境 **ubuntu16.04  +  java version "1.8.0_144" **
可正常启动程序，启动后生成 **/proxyee-down/proxyee-down-2.54/main/ssl/ca.crt**证书
按照[read.md](https://github.com/proxyee-down-org/proxyee-down/blob/master/.guide/common/ca/linux/read.md)方式导入
在google浏览器中导入提示：The Private Key for this Client Certificate is missing or invalid

**Comment by 492162921** [comment]
# 有建议吗，持续

**Comment by monkeyWie** [comment]
是导入在授权中心里吗

**Comment by 5452** [comment]
自带的CA证书内容是啥？颁发机构名称是啥

**Comment by 492162921** [comment]
”自带的CA证书内容是啥？颁发机构名称是啥“
Ubuntu 下载的jar包， 在tomcat运行部署后，会生成文件夹。 CA证书就是文件夹里面的。

**Comment by 492162921** [comment]
“是导入在授权中心里吗”
我在是谷歌浏览器中，按照官方指导导入的。不弄明白你所说“授权中心”是什么意思？

**Comment by monkeyWie** [comment]
@492162921 
![image](https://user-images.githubusercontent.com/13160176/41328237-a5615330-6ef9-11e8-8c13-07b9f09cf088.png)

**Comment by 492162921** [comment]
可以解决，多谢。
