### ISSUE TITLE
MACOSX 无法调用 GUI 显示

### ISSUE THREAD

**Issue by EkoWang** [proxyee-down-org/proxyee-down#457]
### 相关日志

**Comment by monkeyWie** [comment]
有log吗

**Comment by EkoWang** [comment]
单纯启动后，LOG未显示记录，为空。但是GUI的确无法显示。
我附上一个有报错的LOG，您查一下。
[error.2018-05-31.log](https://github.com/proxyee-down-org/proxyee-down/files/2088429/error.2018-05-31.log)

**Comment by monkeyWie** [comment]
托盘图标显示了吗?

**Comment by EkoWang** [comment]
Dock未能显示图标。顶部状态栏小图标在

**Comment by monkeyWie** [comment]
把UI模式切换成浏览器模式看看。

**Comment by EkoWang** [comment]
浏览器模式一直是可行的。不过虽然我默认是 Chrome，但是浏览器模式还是会自动调用 Safari

**Comment by monkeyWie** [comment]
那就用浏览器模式吧，gui可能兼容性不太好，估计和你装的什么软件冲突了
