### ISSUE TITLE
配置好了但是下载不了

### ISSUE THREAD

**Issue by liuyisheng01** [proxyee-down-org/proxyee-down#458]
###配置好了但是下载不了(必要)
###2.03(必要)
###win10 x64(必要)
### 
![8i d 6s adfmz5 dlv o7](https://user-images.githubusercontent.com/40027360/41097213-c3501d78-6a89-11e8-994b-38f42f135520.png)

### 相关日志

**Comment by SADAME-UNMEI** [comment]
同样的问题。

**Comment by monkeyWie** [comment]
升级到最新版本即可
