### ISSUE TITLE
更新总是99%就停了

### ISSUE THREAD

**Issue by dg8806** [proxyee-down-org/proxyee-down#459]
### 相关日志

**Comment by monkeyWie** [comment]
可以下载-jar.zip进行手动覆盖更新

**Comment by dg8806** [comment]
嗯，我好几个版本都是这么干的
2018-06-08 

dg8806 



发件人：monkeyWie <notifications@github.com>
发送时间：2018-06-08 17:36
主题：Re: [proxyee-down-org/proxyee-down] 更新总是99%就停了 (#459)
收件人："proxyee-down-org/proxyee-down"<proxyee-down@noreply.github.com>
抄送："dg8806"<dg8806@163.com>,"Author"<author@noreply.github.com>

可以下载-jar.zip进行手动覆盖更新
