### ISSUE TITLE
无法下载， "error_code":31034,"error_msg":"pcs refuse service"， 任务区没有正在下载的文件

### ISSUE THREAD

**Issue by apprenticepeng** [proxyee-down-org/proxyee-down#461]
### 相关日志  日志为空 (0 kb)
![dl](https://user-images.githubusercontent.com/30119039/41139692-d95f43a4-6b1b-11e8-83d9-1434338315ff.jpg)

**Comment by monkeyWie** [comment]
参考FAQhttps://github.com/monkeyWie/proxyee-down/blob/master/.guide/FAQ.md

**Comment by monkeyWie** [comment]
换个资源下载试试看，可能是资源的问题吧。
