### ISSUE TITLE
开启软件后，登录百度网盘网页版不显示软件图标

### ISSUE THREAD

**Issue by xiaorui2017** [proxyee-down-org/proxyee-down#462]
### 问题描述(必要)
开启软件后，登录百度网盘网页版不显示软件图标
### 版本号(必要)
2.54
### 操作系统(必要)
win7 64
### 相关截图
![2018-06-08_210336](https://user-images.githubusercontent.com/26056113/41159602-a33c981e-6b5f-11e8-96c1-19d49c04924e.png)
![2018-06-08_210505](https://user-images.githubusercontent.com/26056113/41159630-beb2db80-6b5f-11e8-82e5-57cef1e83654.png)

### 相关日志

**Comment by ted423** [comment]
嗅探模式那里有看么？edge?
有装管代理的扩展没？如果有扩展的话，嗅探模式会不起作用
