### ISSUE TITLE
进度条超过100%，在往200%的路上逛奔……

### ISSUE THREAD

**Issue by qzz420** [proxyee-down-org/proxyee-down#463]
请问这种问题如何解决，
今天下载有两个任务，其中一个达到100%后进度条失去百分比显示，但仍然在下载（有速度），删掉任务重新下载成功。
另外一个任务，已经下载到103%了。
版 本为2.54，电脑是win7-64bit

![default](https://user-images.githubusercontent.com/40137917/41199993-1a913224-6ccf-11e8-9272-ab1dd3b4548b.PNG)

### 相关日志

**Comment by monkeyWie** [comment]
软件的bug，新版本会修复掉的。可以重新下载
