### ISSUE TITLE
程序员大神，我想知道你开发的这个软件是用什么来设计gui的？

### ISSUE THREAD

**Issue by LoveCodingPanda** [proxyee-down-org/proxyee-down#464]
#我也是一个java爱好者，想知道gui部分是用什么开发的？最好详细点说说#

![pan](https://user-images.githubusercontent.com/38828763/41200664-cef06292-6cdb-11e8-93e1-602dbc562f2e.png)

**Comment by monkeyWie** [comment]
界面是用vue.js+Element UI做的，就是内嵌了个浏览器访问网页

**Comment by LoveCodingPanda** [comment]
浏览器部分怎么实现呢？

**Comment by monkeyWie** [comment]
可以看下源码https://github.com/proxyee-down-org/proxyee-down/blob/master/ui/src/main/java/lee/study/down/gui/HttpDownApplication.java
