### ISSUE TITLE
和蓝灯冲突

### ISSUE THREAD

**Issue by zhoupengqin** [proxyee-down-org/proxyee-down#465]
### 问题描述(必要)
开启软件后，无法使用蓝灯。嗅探模式：百度云，蓝灯：HTTP(S)代理服务器：127.0.0.1:50191、SOCKS代理服务器：127.0.0.1:50190
### 版本号(必要)
2.54
### 操作系统(必要)
macOS 10.12.6
### 相关日志
error.2018-06-10.log 无记录

**Comment by monkeyWie** [comment]
参考https://github.com/proxyee-down-org/proxyee-down/issues/207#issuecomment-376229390
