### ISSUE TITLE
Include instructions for OpenJDK (JRE) + OpenJFX

### ISSUE THREAD

**Issue by gojpdchx** [proxyee-down-org/proxyee-down#466]
### Problem Description
[The guide](https://github.com/proxyee-down-org/proxyee-down/blob/master/.guide/linux/read.md) in ` proxyee-down/.guide/linux/read.md` contains the instructions for Oracle JDK (JRE) only. However, with OpenJFX installed, OpenJDK (JRE) can be used with proxyee-down.

Considering that most Linux distributions include OpenJDK (JRE) and OpenJFX (instead of Oracle JDK/JRE) in their official repositories, we can recommend using OpenJDK (JRE) (Version 8) + OpenJFX for those who do not have Java installed. Package managers (dnf, apt, pacman, etc.) will "automagically" handle the installation and update of the Java environment.

### proxyee-down version
Not applicable

### OS
Linux

**Comment by monkeyWie** [comment]
Thanks,I will consider modifying the Linux guide.
