### ISSUE TITLE
想提一个想法

### ISSUE THREAD

**Issue by I-love-study** [proxyee-down-org/proxyee-down#468]
### 问题描述(必要)
提一个想法：
就是做另外一种程序，只获取真正的下载路径，然后在通过局域网把下载路径传输到下载机里下载。或者直接显示真正的下载地址
甚至于用QQ，微信之类的传输（曾在Github看过这样的传输）
这样子就有能力在手机上制作（虽说难度更大）
（本人不是学Java的，只是Python初学者，只是在此提个建议）
### 版本号(必要)
2.54
### 操作系统(必要)
win 10专业版 17134

**Comment by Zhangzijing** [comment]
这样的程序已经有了，[BaiduPCS-GO](https://github.com/iikira/BaiduPCS-Go)
lt 命令可以实现你说的功能

**Comment by monkeyWie** [comment]
第一段的话现在已经支持的，第二段没太明白
