### ISSUE TITLE
点击下载后无法跳转到软件界面

### ISSUE THREAD

**Issue by pplayerr** [proxyee-down-org/proxyee-down#470]
### 问题描述(必要)
在百度网盘网页上点击下之后会跳出来一个选择软件的弹窗，并不会跳转到proxyee界面，无法进行下载
### 版本号(必要)
2.22
### 相关截图
![default](https://user-images.githubusercontent.com/16116257/41332376-2e23efe6-6f10-11e8-9dc7-591c528e859f.PNG)
![default](https://user-images.githubusercontent.com/16116257/41332381-32af05a0-6f10-11e8-826c-d6cb792926bf.PNG)

### 相关日志

**Comment by monkeyWie** [comment]
软件升级到2.54
