### ISSUE TITLE
请问一下能不能在wget中设置代理

### ISSUE THREAD

**Issue by Shedarshian** [proxyee-down-org/proxyee-down#471]
请问一下能不能在wget中设置下载通过这个软件的代理...由于目的是想通过Xshell终端，从百度云下载到linux服务器，通过终端在linux服务器上使用网页浏览器会很麻烦...而可以在外部获取下载链接之后用wget下载百度网盘的文件，所以想问一下能不能设置...

**Comment by monkeyWie** [comment]
新版本会出命令行版的。

**Comment by monkeyWie** [comment]
可以用https://github.com/proxyee-down-org/pdown-core
支持命令行下载
