### ISSUE TITLE
Ubuntu 下运行软件没有反应（运行后直接结束）

### ISSUE THREAD

**Issue by Ricardo-lu** [proxyee-down-org/proxyee-down#472]
Java 版本应该是10.0.1
系统版本 Ubuntu 18.04 LTS
下载软件版本 2.54 
描述：
使用命令 `java -jar ./proxyee-down.jar` 没有任何输出，直接运行完毕，状态栏没有出现图标
如下图
![2018-06-13 20-50-46](https://user-images.githubusercontent.com/30211094/41352471-25618616-6f4c-11e8-99e2-04c01acc4228.png)

**Comment by monkeyWie** [comment]
应该是没装javafx。

**Comment by wozuishuai13768** [comment]
装了 `openjfx` 以后还是这样

**Comment by monkeyWie** [comment]
试试用orcale jdk

**Comment by Ricardo-lu** [comment]
尝试安装 javafx 解决 ：运行命令 `sudo apt-get install openjfx`

**Comment by wozuishuai13768** [comment]
还是不行啊...

**Comment by BlackHole1** [comment]
@monkeyWie

**Comment by LeeReindeer** [comment]
遇到同样的问题，在安装 `openjfx` 之后可以使用。
![screenshot from 2018-07-19 16-49-12](https://user-images.githubusercontent.com/22074258/42932008-bf819edc-8b73-11e8-9e33-5469098382f5.png)
