### ISSUE TITLE
MacOS 下程序安装停住

### ISSUE THREAD

**Issue by djm888** [proxyee-down-org/proxyee-down#473]
输完密码,走到这一步安装时程序不动了,程序栏出现图标,也无法点
2.54
MacOS 10.12.6
![2018-06-14 21 49 57](https://user-images.githubusercontent.com/40270026/41416380-4e81f4be-701d-11e8-873c-c273c0a8e87f.png)

**Comment by whidy** [comment]
我是点击了下载创建任务的时候卡住了,不知道怎么回事, 但是卡到最后他会自己下载完.. 但是一直未响应..

**Comment by monkeyWie** [comment]
这个是启动完了啊，没有托盘图标出现吗？
