### ISSUE TITLE
选定文件进行点击下载后，直接跳出百度云关联链接显示，无法关联启动proxyee-down；

### ISSUE THREAD

**Issue by qingchuhun** [proxyee-down-org/proxyee-down#474]
描述：选定文件进行点击下载后，直接跳出百度云关联链接显示，无法关联启动proxyee-down；
嗅觉模式：全局/百度云
switch模式：proxyee-down下载
版本号：2.2
操作系统：window7

![oj9huz9t_t58zayi 8fbc9](https://user-images.githubusercontent.com/29964317/41416948-a603a2e0-701e-11e8-9306-66ea1d1081de.png)
![abv skb_d8 7 l1 s6 o n](https://user-images.githubusercontent.com/29964317/41416951-a67ddace-701e-11e8-81b0-92e5cd05517c.png)

相关日志：下载失败，日志为空。

**Comment by Darren9801** [comment]
我也是这个问题，之前都不会的

**Comment by Darren9801** [comment]
小文件可以下，大文件都跳转百度云管家了

**Comment by monkeyWie** [comment]
升级到2.54就行
