### ISSUE TITLE
希望精简

### ISSUE THREAD

**Issue by 123456ds** [proxyee-down-org/proxyee-down#477]
觉得可以只保留下载部分

像aria2一样，只下载

用户界面在浏览器内通过访问127.0.0.1 显示

新建任务直接用浏览器脚本提取的链接，还可以支持其他的下载协议【如，ftp】

没有安装脚本时，新建任务时输入pan.baidu.com/s/*****，软件可以自动提取出下载链接并下载

通过嗅探的方法下载，让用户无法100%设置成功
软件启动速度也比较慢

/*个人拙见*/

**Comment by BlackHole1** [comment]
感谢反馈，我们也在对项目进行精简，下个版本应该就会好很多。
关于直接输入pan的url。是可以做到的，但是会比较麻烦，我们会抽时间进行编写。感谢你的建议
