### ISSUE TITLE
经常下载失败

### ISSUE THREAD

**Issue by DpangD** [proxyee-down-org/proxyee-down#478]
### 问题描述(必要)
经常在下载中下载失败（256线程），点击继续后可以断点续连，然后过会儿又下载失败，再点击继续后又能继续下载。下载一个资源要点好几次。
### 版本号(必要)
2.54
### 操作系统(必要)
win10
### 相关截图
![tim 20180618204103](https://user-images.githubusercontent.com/33514128/41536366-fc8570f0-7337-11e8-880a-f7aff2eb6f1b.png)
### 相关日志
有日志，可是日志为空，不过看之前的日志，大都是响应码异常403和 远程主机强迫关闭了一个现有的连接。

**Comment by monkeyWie** [comment]
可以在设置里把重试次数调高点
