### ISSUE TITLE
[bug]下载多个文件时文件名会乱。

### ISSUE THREAD

**Issue by wgf4242** [proxyee-down-org/proxyee-down#482]
### 问题描述(必要)
下载多个文件时文件名会乱。
比如part1 --- part6。。。 1g 1g ... 600m
下载的时候文件名为part4变成600m。。。文件名是对不上的。
### 版本号(必要)
2.54
### 操作系统(必要)
Win10x64

**Comment by monkeyWie** [comment]
这个是px的插件有问题，反馈下给插件作者吧。。
