### ISSUE TITLE
每次需重新解压打开，百度网盘才能显示proxyee-down

### ISSUE THREAD

**Issue by BusyHe** [proxyee-down-org/proxyee-down#484]
### 10.13.5 (17F77)

**Comment by ted423** [comment]
没看懂

**Comment by BusyHe** [comment]
@ted423 比方说我把压缩包解压了，按正常流程走可以用，下一次开机我直接从解压后的文件打开，就用不了。只能重新解压文件再打开，是不是缓存相关的东西

**Comment by monkeyWie** [comment]
是没运行软件？

**Comment by BusyHe** [comment]
proxyee-down文字没有显示。我试过重启cherome 和 proxyeedown，甚至电脑都不能，每次都是重新解压再打开就可以了。如果我这个是个例的话，可以关闭此问题

**Comment by BusyHe** [comment]
找到原因了，不能放到中文目录下
