### ISSUE TITLE
建议使用JavaFX，看了一下，你这个包太大了

### ISSUE THREAD

**Issue by claer-ding** [proxyee-down-org/proxyee-down#485]
![javafx](https://user-images.githubusercontent.com/30252550/41638080-e673737c-7489-11e8-9f9e-540c6a4f9049.png)

**Comment by monkeyWie** [comment]
javafx打包也是把jre打进去吧，体积还是一样大

**Comment by shamashii** [comment]
@monkeyWie 现在最低jre要求是多少？1.8.0?

**Comment by monkeyWie** [comment]
@shamashii 是啊，怎么了

**Comment by shamashii** [comment]
@monkeyWie 最新版里没带jre,确认下而已

**Comment by claer-ding** [comment]
@monkeyWie 可以使用JDK9版以上，现在模块化了

**Comment by claer-ding** [comment]
https://blog.csdn.net/dev_csdn/article/details/79020557

**Comment by claer-ding** [comment]
https://www.cnblogs.com/IcanFixIt/p/7110790.html

**Comment by claer-ding** [comment]
http://ifeve.com/jep-282-jlink/

**Comment by claer-ding** [comment]
https://github.com/steve-perkins/jlink-demo

**Comment by monkeyWie** [comment]
谢谢你的建议，新版本会尝试用java9模块化的

**Comment by monkeyWie** [comment]
看了下现在依赖的组件基本都不支持模块化打包
