### ISSUE TITLE
自动弹出很多广告下载

### ISSUE THREAD

**Issue by jkunlin** [proxyee-down-org/proxyee-down#486]
### 问题描述(必要)
打开软件的时候，自动弹出很多广告下载，例如com.xiaobint.xiaobinjinrong.1806060938.apk，从名字来看都是理财app
### 版本号(必要)
2.54
### 操作系统(必要)
win10
### 相关日志

**Comment by monkeyWie** [comment]
换个代理端口，这是代理服务器被别的应用使用了。

**Comment by jkunlin** [comment]
请问为什么端口被其他应用使用，会弹出这些广告软件下载？因为代理软件内嵌了广告吗？

**Comment by monkeyWie** [comment]
我也不知道，之前碰到过这种情况 有个校园网拨号的软件会走这个代理，改了端口就好了

**Comment by jkunlin** [comment]
嗯，下午看了是jre占用了这个端口，很奇怪。改端口确实好了。
