### ISSUE TITLE
百度网盘不显示proxyee-down图标

### ISSUE THREAD

**Issue by lesterpang** [proxyee-down-org/proxyee-down#488]
![image](https://user-images.githubusercontent.com/3345912/41759802-d12dcdc4-7622-11e8-9625-daf545c670de.png)
软件已经打开了

**Comment by shunichio** [comment]
我今天也遇到这个问题。

**Comment by monkeyWie** [comment]
看看FAQ
https://github.com/monkeyWie/proxyee-down/blob/master/.guide/FAQ.md
