### ISSUE TITLE
不能下载了

### ISSUE THREAD

**Issue by zlf179** [proxyee-down-org/proxyee-down#489]
点击下载不能下载了
版本是2.54
win10 1803
浏览器是Cent浏览器
![37](https://user-images.githubusercontent.com/26280126/41785107-da35e02c-7641-11e8-9767-d19d0575ac1d.png)
重装过proxyee没用

**Comment by feiweilai** [comment]
我也是error_code: 31066,
error_msg: "file does not exist",不能下了

**Comment by zlf179** [comment]
我自己解决了  因为和我浏览器装的一个插件冲突
