### ISSUE TITLE
下载无法开始（无进度）

### ISSUE THREAD

**Issue by zaqws** [proxyee-down-org/proxyee-down#490]
可以启动下载，但完全无法开始下载。防毒关闭，链接刷新，登出下载，重装都试了。
v2.54
win10
Chrome浏览器
<img width="432" alt="picture1" src="https://user-images.githubusercontent.com/40509592/41804932-183cec18-76d2-11e8-9f72-5c77599d2100.png">
<img width="432" alt="picture2" src="https://user-images.githubusercontent.com/40509592/41804933-18809634-76d2-11e8-885a-8848eee8b723.png">

**Comment by BlackHole1** [comment]
尝试更换下IP试试

**Comment by monkeyWie** [comment]
麻烦提供下log文件
