### ISSUE TITLE
希望加入设置：是否默认勾选自动解压

### ISSUE THREAD

**Issue by OneWizard** [proxyee-down-org/proxyee-down#491]
首先谢谢作者的辛苦开发和辛勤维护

### 问题描述

现在下载，很多是压缩包，每次添加后都要把自动解压给点掉（其实有些带密码的也不好一一解压）
而且下载iso之类的自动勾选，真心没必要
个人觉得应该加入设置是否默认勾选自动解压
真正必要的我觉得应该是文件夹下载的pack.zip自动解压+解压后自动删除pack.zip

### 版本号
2.54
### 操作系统
Windows 10 1803 x64
### 相关截图
无
### 相关日志
无

**Comment by Danborad** [comment]
我也觉得，还有我喜欢自己解压，每次我都要把自动解压关掉

**Comment by monkeyWie** [comment]
参考下，并不是所有压缩包都会自动解压 https://github.com/proxyee-down-org/proxyee-down/issues/288
