### ISSUE TITLE
进入下载链接时无法取消，取消会导致界面卡住

### ISSUE THREAD

**Issue by wth461694678** [proxyee-down-org/proxyee-down#492]
### 问题描述(必要)
如题
### 版本号(必要)
2.54
### 操作系统(必要)
Mac
### 相关截图
![qq20180624-0](https://user-images.githubusercontent.com/39629728/41817514-16f5fc7a-77cf-11e8-9c9c-317afab41970.png)

### 相关日志

**Comment by BlackHole1** [comment]
是点击取消，页面就会卡死么？

**Comment by KingggWS** [comment]
你好，我点下载会显示 pan.baidu.com 发生错误！

**Comment by BlackHole1** [comment]
有相关的报错截图么？

**Comment by KingggWS** [comment]
整好了 是baidu-dl的锅

                                                        ————King👑

**Comment by BlackHole1** [comment]
好的

**Comment by monkeyWie** [comment]
mac系统下载前会预分配文件大小，所以会卡主，下个版本会针对这个问题修复的
