### ISSUE TITLE
ui线程阻塞

### ISSUE THREAD

**Issue by peterxm** [proxyee-down-org/proxyee-down#494]
### 问题描述(必要)
在任务页面勾选删除任务和文件删除文件时，如果该文件被占用将导致ui线程阻塞。
### 版本号(必要)
2.54
### 操作系统(必要)
Microsoft Windows [版本 10.0.17134.112]
### 相关截图
![2](https://user-images.githubusercontent.com/27820739/41818713-e86e1bf4-77e6-11e8-8deb-b5c57717511b.png)

### 相关日志
[error.2018-06-24.log](https://github.com/proxyee-down-org/proxyee-down/files/2130728/error.2018-06-24.log)

**Comment by BlackHole1** [comment]
感谢反馈，我们会在下个版本进行更新
