### ISSUE TITLE
WIN10 1803，已按教程安装证书，再次打开还是提示证书未安装

### ISSUE THREAD

**Issue by iwsbiwy** [proxyee-down-org/proxyee-down#496]

**Comment by BlackHole1** [comment]
请查考github上的FAQ:https://github.com/proxyee-down-org/proxyee-down/blob/master/.guide/FAQ.md

**Comment by iwsbiwy** [comment]
@BlackHole1 你指的是手动安装证书吗？我就是手动安装过证书，依然提示的。

**Comment by monkeyWie** [comment]
是什么浏览器呢？

**Comment by iwsbiwy** [comment]
@monkeyWie chrome
