### ISSUE TITLE
分卷压缩包下载时，每次添加都跳出检测到相同任务提示

### ISSUE THREAD

**Issue by jzmswe** [proxyee-down-org/proxyee-down#503]
PX批量下载脚本有问题，文件名乱序，已在作者发布作品的两个地方留言。我看到有人6月15留言。。。。
SO，老大是否能加上批量下载功能，如果不能，能否把这个提示去掉。
就是分卷压缩包part1.rar   part2.rar 这样一些文件，他们大小相同，所以被误识别为相同文件，每次都出提示。

**Comment by jzmswe** [comment]
每次添加任务，都要手动关闭自动解压，能否在设置里加个开关？
因为我经常下载分卷压缩包，全部下载完后，才能手动解压，只下载一个分卷包，是无法解压的。

**Comment by monkeyWie** [comment]
批量下载的话下个版本会考虑支持的。

**Comment by monkeyWie** [comment]
3.0已经支持
