### ISSUE TITLE
百度网盘内单文件下载提示“发生错误”

### ISSUE THREAD

**Issue by wizdzz** [proxyee-down-org/proxyee-down#508]
### 问题描述(必要)
百度网盘中，单文件点击下载，提示“发生错误！”

### 版本号(必要)
2.54

### 操作系统(必要)
Microsoft Windows 10 专业版

### 相关截图
![qq 20180630130909](https://user-images.githubusercontent.com/38684262/42121725-cb394d90-7c66-11e8-9b17-bfb4e4edb621.png)

### 相关日志
日志文件为 0 kb。

**Comment by BlackHole1** [comment]
请尝试刷新页面，或者更换其他的油猴脚本进行下载

**Comment by wizdzz** [comment]
要配合油猴脚本才能正常使用此软件下载是吗？
我用了这个: "https://github.com/syhyz1990/baiduyun"，可以正常下载了。

**Comment by BlackHole1** [comment]
那就好
