### ISSUE TITLE
在百度云盘页面没有proxyee-down项

### ISSUE THREAD

**Issue by NoSugarCoffee** [proxyee-down-org/proxyee-down#510]
### 问题描述(必要)
之前的有，现在不知道为什么没有了，是被和谐了吗
### 版本号(必要)
2.54
### 相关截图
![image](https://user-images.githubusercontent.com/25247325/42126015-6fd1e186-7cb3-11e8-82ee-89b7d3a538d7.png)
### 相关日志

**Comment by YourLuck** [comment]
建议尝试一下https://github.com/proxyee-down-org/proxyee-down/blob/master/.guide/FAQ.md

**Comment by BlackHole1** [comment]
请参考 @YourLuck 的回答

**Comment by linxuankent** [comment]
也没用出现我就用的插件

**Comment by hongming1218** [comment]
我的mac也没有  装的2.5.4  软件浏览器都重启了  不显示  安装switchy插件之后也不行。。。 开启无痕模式也无效
弄不明白了   现在只能是有下载链接手动创建任务了

**Comment by SciUnivMoring** [comment]
@hongming1218 switchy插件安装好后正确设置了吗

**Comment by 492162921** [comment]
我也常遇到该问题。
用重启电脑，运行proxyee ， 安装运行谷歌浏览器 ，清理浏览器缓存。 
即可。

**Comment by hongming1218** [comment]
@SciUnivMoring 没设置成功    可能是这个原因   每次导入备份设置的时候提示无法从备份文件恢复，可能备份文件损坏   官网下的和那个连接步骤下载的都试了一样   不太明白那块   干脆每次先网页下载   然后截取连接手动添加任务处理了

**Comment by zoukun120** [comment]
用重启电脑，运行proxyee ， 安装运行谷歌浏览器 ，清理浏览器缓存。
