### ISSUE TITLE
GUI界面乱码网页正常

### ISSUE THREAD

**Issue by LANXF** [proxyee-down-org/proxyee-down#511]
### 问题描述(必要)
GUI界面乱码，网页正常
### 版本号(必要)
2.54
### 操作系统(必要)
Windows10 家庭版 版本：1803
### 相关截图
![gui](https://user-images.githubusercontent.com/23370397/42130584-ea861ede-7d1b-11e8-8709-d3b23a1ca584.png)
![default](https://user-images.githubusercontent.com/23370397/42130585-eb28cada-7d1b-11e8-9968-e6f7a355f206.png)

### 相关日志

[error.2018-07-01.log](https://github.com/proxyee-down-org/proxyee-down/files/2152342/error.2018-07-01.log)

**Comment by BlackHole1** [comment]
请尝试，重新下载安装试试

**Comment by ted423** [comment]
电脑是什么语言环境？
