### ISSUE TITLE
用后电脑非常卡，出现假死，深度怀疑被用来挖矿了

### ISSUE THREAD

**Issue by fuckproxyee100** [proxyee-down-org/proxyee-down#518]
### 问题描述(必要)
4g运行内存的电脑中，使用proxyee-down下载文件经常假死，电脑变得非常慢，在没有使用这个软件之前我的电脑非常流畅，使用后连输入法显示文字的速度都比以前慢了
### 版本号(必要)
2.54
### 操作系统(必要)
win10和win7
### 相关日志

**Comment by evrmji** [comment]
你好 我的电脑使用了 E3 处理器, CPU 占用率都有时候会上升到 25%.
请检查您的电脑配置, 或者检查软件下载源, 怀疑有挖矿脚本可以尝试使用沙盒, 或者使用 x64dbg 进行调试.
当然最好的方式是检查源码然后自行编译, 如果编译后还有问题, 请检查源码.
您所讲述的问题我均没有遇到过, 请检查您的系统, 或者选择重装系统.
您的这个问题提的不具有建设性.

**Comment by dreamunicorn** [comment]
电脑配置贴上来再怀疑软件跑后台ok？而且代码都贴在那，怀疑程序有问题怎么不自己翻一遍代码看看有没有挖矿代码，编译一遍正常的代码然后跑一边看看占用？下图测试为256线程状态下的软件占用
![default](https://user-images.githubusercontent.com/21287731/42412195-24b585f4-823a-11e8-8201-cfb5dc2d32f3.png)
![default](https://user-images.githubusercontent.com/21287731/42412216-777393a8-823a-11e8-8fac-ee8cedba13b7.png)

**Comment by monkeyWie** [comment]
并不存在挖矿，卡的话可以把连接数调小点
