### ISSUE TITLE
打开主界面404，完全打不开

### ISSUE THREAD

**Issue by XYUU** [proxyee-down-org/proxyee-down#521]
### 问题描述(必要)
打开主界面404，完全打不开
### 版本号(必要)
![image](https://user-images.githubusercontent.com/9715021/42432632-0639b97a-837e-11e8-9767-0dde9ae98fa1.png)

### 操作系统(必要)
![image](https://user-images.githubusercontent.com/9715021/42432611-ea9e2cdc-837d-11e8-8ebd-7d49bc6685be.png)
### 相关截图
![image](https://user-images.githubusercontent.com/9715021/42432584-b7b5a7c8-837d-11e8-97c6-34961db68af1.png)
### 相关日志

**Comment by BlackHole1** [comment]
现在还存在这个问题么？

**Comment by monkeyWie** [comment]
更新到3.0
