### ISSUE TITLE
如果和 ShadowSocks(R) 同时使用，需要注意的事情

### ISSUE THREAD

**Issue by SciUnivMoring** [proxyee-down-org/proxyee-down#523]
### 问题描述(必要)
这个程序的一部分原理是修改系统代理，因此，如果和 ShadowSocks(R) 同时开启的话，会出现一些问题
比如， ShadowSocks(R) 现在是运行在PAC模式下，把系统代理改成了自己的pac，而这时启动proxyee-down 的话，系统代理设置会被覆盖，退出proxyee之后，需要重启 ShadowSocks(R) 
同样的，如果在proxyee运行期间开启或重启 ShadowSocks(R) ，就无法嗅探百度云，因为系统代理设置已经被 ShadowSocks(R) 修改了

因此，如果需要同时使用 proxyee 和 ShadowSocks(R) ，需要这样：
1、如果正在运行ShadowSocks(R) （pac模式），那么需要先把它的系统代理设置修改为“直连”，
2、然后开启proxyee-down，打开百度网盘页面创建下载任务，任务创建好了，开始下载了，把proxyee的“嗅探模式”设为关闭
3、然后再把 ShadowSocks(R) 的系统代理设置 改回 pac模式
如果接下来又遇到需要下载的百度网盘文件，先把ShadowSocks(R) 改成直连模式，再把proxyee的资源嗅探设为“百度云”，然后重复上面的2、3步
这样一来，proxyee-down和ShadowSocks(R)就不会发生代理设置的冲突，proxyee-down在那里下载文件，同时你可以用 ShadowSocks(R) 科学上网！

### 版本号(必要)
2.54

### 操作系统(必要)
Windows 7/8/8.1/10

**Comment by FangXiSaMa** [comment]
Mac系统要如何解决呀

**Comment by LoveFrea** [comment]
不一定需要重启ShadowSocks(R)，如果因开启了proxyee导致无法科学上网，你可以尝试更改系统代理模式来刷新它。

**Comment by kooljazz** [comment]
mac无法解决

**Comment by bososha** [comment]
其实个人觉得这个问题挺好解决的，把PD和SS看成代理池中提供的不同功能的代理就行了。这样，在浏览器上用SwitchyOmega管理代理，Windows/Mac系统的应用就用Proxifier管理代理。个人使用的过程中发现在百度云下载上PD还是比较稳定，用油猴+IDM下载总会出现莫名的错误，其它普通的下载用IDM甚至迅雷也能搞定，没有必要开嗅探。

**Comment by monkeyWie** [comment]
3.0版本如果要使用浏览器插件接管代理的话，参考这里的教程https://monkeywie.github.io/2018/09/05/proxyee-down-3-0-guide/#扩展模块
