### ISSUE TITLE
下载的文件移动时需要权限验证

### ISSUE THREAD

**Issue by xukangqi** [proxyee-down-org/proxyee-down#525]
### 问题描述(必要)
用这个软件下载成功以后移动下载的文件时都需要权限验证，提供密码或者touchid
### 版本号(必要)
2.54
### 操作系统(必要)
macos 10.13.6
### 相关截图
![image](https://user-images.githubusercontent.com/16576935/42551301-2a076ae6-8509-11e8-9121-6a5d32d2408b.png)

**Comment by xukangqi** [comment]
看了一下下载的文件权限“everyone”这一项只有“只读”，能不能改成“读和写”？

**Comment by Fyingcml** [comment]
我也遇到同样的问题

系统 macOS 10.13.6

**Comment by ycg31** [comment]
同样的问题，看到开发者已经列入3.0计划就放心，确实太不方便了，我现在解压出来的文件夹都删不掉，要去安全模式才能删，更改权限提示无法枚举。

**Comment by monkeyWie** [comment]
3.0会修复mac下文件权限问题的。

**Comment by monkeyWie** [comment]
3.0已发布
