### ISSUE TITLE
代理服务器拒绝连接是什么鬼？

### ISSUE THREAD

**Issue by klcb2010** [proxyee-down-org/proxyee-down#526]
电脑没有安装java  是这个原因吗？
![qq 20180713100449](https://user-images.githubusercontent.com/32628414/42668789-193c9a1a-8685-11e8-8641-77699cfbe68a.png)
![qq 20180713100510](https://user-images.githubusercontent.com/32628414/42668791-1e7ae72a-8685-11e8-8d72-a8c72fc6385a.png)
![qq 20180713100520](https://user-images.githubusercontent.com/32628414/42668793-2384a35a-8685-11e8-846b-59cf183a0520.png)

**Comment by klcb2010** [comment]
已解决 重新安装  问题没有复现  神奇了

**Comment by klcb2010** [comment]
恩  已经证实 PD自动转换的时候 要正常浏览百度网盘  必须先打开PD客户端  即使在不需要下载百度盘的时候

**Comment by monkeyWie** [comment]
是的，如果不下载可以把代理切换成直接连接
