### ISSUE TITLE
npm install 安装的时候会断掉

### ISSUE THREAD

**Issue by Jasonandy** [proxyee-down-org/proxyee-down#527]
### 问题描述(必要)
![image](https://user-images.githubusercontent.com/12879147/42670030-3258a362-868b-11e8-85eb-67f5b3dbd6ab.png)

### 版本号(必要)
V3.0

### 操作系统(必要)
Linux Centos7 
![image](https://user-images.githubusercontent.com/12879147/42670074-717b6854-868b-11e8-81ed-75b61bdadd23.png)

### 相关截图
![image](https://user-images.githubusercontent.com/12879147/42670058-5f327b74-868b-11e8-99c5-5e909eeb6a16.png)

**Comment by BlackHole1** [comment]
尝试了一下，没有复现成功，尝试使用下cnpm来进行安装

**Comment by Jasonandy** [comment]
嗯嗯 谢谢
