### ISSUE TITLE
程序已打开，为何还是不能用，请赐教

### ISSUE THREAD

**Issue by lee527hpu** [proxyee-down-org/proxyee-down#532]
之前还能用的，过一段时间后就不能用了，请大神赐教！

**Comment by BlackHole1** [comment]
请问不能用的话，是什么样的反馈？打不开？还是有报错信息？还是功能无法使用？

**Comment by lee527hpu** [comment]
点击文件下载后，出现百度网盘的链接，目前已解决，下载了EX-百度网盘脚本解决了，还是非常感谢
