### ISSUE TITLE
某次进程卡死后 再也无法正常添加下载 

### ISSUE THREAD

**Issue by c153747477** [proxyee-down-org/proxyee-down#533]
### Win10

**Comment by c153747477** [comment]
刚发现软件启动会有大概2w个各种本地回环 正常吗?

[hs_err_pid6972.log](https://github.com/proxyee-down-org/proxyee-down/files/2216132/hs_err_pid6972.log)

**Comment by BlackHole1** [comment]
@monkeyWie

**Comment by monkeyWie** [comment]
在哪看到的2w本地回环啊？

**Comment by c153747477** [comment]
netstat 
操作系统里

**Comment by monkeyWie** [comment]
试试3.0版本
