### ISSUE TITLE
貌似这个软件被屏蔽了？

### ISSUE THREAD

**Issue by Kiyohimedaze** [proxyee-down-org/proxyee-down#537]
第一次使用这个软件，安装正常，打开正常，但是软件开启后在浏览器中打开百度云的链接会失败
![qq 20180721000057](https://user-images.githubusercontent.com/41483755/43012714-78801b9c-8c79-11e8-9822-d5fd6e6de206.png)
![qq 20180721000251](https://user-images.githubusercontent.com/41483755/43012717-78c91d56-8c79-11e8-95b3-9d8d800d91a8.png)
版本号2.54
操作系统win10 1709

**Comment by SADAME-UNMEI** [comment]
同打开链接失败，你的错误日志上显示什么？

**Comment by zheshilixin** [comment]
{"error_code":31426,"error_msg":"user is not authorized, hitcode:116","request_id":105488006018026269}  打开有这样的报错
