### ISSUE TITLE
关于硬盘空间不足的提示

### ISSUE THREAD

**Issue by JamesLiAndroid** [proxyee-down-org/proxyee-down#538]
### 问题描述
最近硬盘空间不够用了，然后下载大文件的时候没注意，我以为是软件出了问题。但是希望能添加这个功能，以免用户怀疑软件层面出现问题！
### 版本号
v2.5.4
### 操作系统
win10 1803

**Comment by BlackHole1** [comment]
好的，我们会考虑这个建议的。
