### ISSUE TITLE
启用此软件后无法进入百度云的网页

### ISSUE THREAD

**Issue by SADAME-UNMEI** [proxyee-down-org/proxyee-down#541]
问题描述：启用此软件后无法进入百度云的网页，其他网页都能正常进入
版本号：2.54
操作系统：win10 64bit 1709
相关截图：
![default](https://user-images.githubusercontent.com/31981500/43041520-cd08640e-8d95-11e8-8179-005f0f1c63a2.PNG)
![368](https://user-images.githubusercontent.com/31981500/43041526-e791bdca-8d95-11e8-88d9-80839368d538.png)
相关日志：
[error.2018-07-22.log](https://github.com/proxyee-down-org/proxyee-down/files/2216664/error.2018-07-22.log)

**Comment by monkeyWie** [comment]
把设置页面截图发来看看
