### ISSUE TITLE
下载a，a里面有b,c压缩文件。下载完成后a可以解压出来，但是解压出的bc压缩文件，却解压出错

### ISSUE THREAD

**Issue by Yhooooo** [proxyee-down-org/proxyee-down#544]
### 相关日志
下载一个文件夹a，a里面有b,c压缩文件。下载完成后a可以通过软件自带的百度云在线解压出来，但是解压出的bc压缩文件，却解压出错。
![default](https://user-images.githubusercontent.com/33347939/43082017-93ba242c-8ec5-11e8-8860-bf191b011706.png)
![default](https://user-images.githubusercontent.com/33347939/43082025-989fc640-8ec5-11e8-8232-1f266a9f7092.png)
下载解压a都没问题，但是a里面包含的bc压缩文件（.rar）却解压出错。bc文件肯定没问题，使用百度网盘客户端下载下来解压成功。难不成是软件在下载的时候出现的传输错误？下载期间网络一切正常。

**Comment by hy345** [comment]
@monkeyWie 这个是不兼容现在的核心的吗？我试了一下，编译之后改名并没有用。能不能请问下如何用这个核心下载百度云的内容？还是暂不支持？谢谢。

**Comment by monkeyWie** [comment]
3.0已经发布
