### ISSUE TITLE
每次打开下载一段时间后会稳定卡死，只能强制关闭

### ISSUE THREAD

**Issue by skepsun** [proxyee-down-org/proxyee-down#545]
每次打开软件新建任务后，在正常下载一段时间之后（切换到浏览器窗口），会稳定卡死，表现为点击无反应，提示软件无响应。强制关闭后打开后会重复上述过程。
2.5.4
win10
[error.2018-07-24.log](https://github.com/proxyee-down-org/proxyee-down/files/2221837/error.2018-07-24.log)

**Comment by zhz1237ok** [comment]
java写的大多都这样

**Comment by monkeyWie** [comment]
降级到2.53试试看
