### ISSUE TITLE
Mac OS 下无法启动

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [proxyee-down-org/proxyee-down#552]
### 问题描述(必要)
Mac OS 下最新版本启动无响应
### 版本号(必要)
Java Runtime Version 8 Update 181 
### 操作系统(必要)
Mac OS 10.13.6

**Comment by hy345** [comment]
同mac，我是启动等五分钟之后有响应，但是自动下载了之后等多久都没有响应了= =

**Comment by xuchaofei** [comment]
我的也是Mac，报出./jre1.8.0_162/Contents/Home/bin/java: command not found这个问题  我以为是没装Java的问题  专门装了Java后重启  还是这个问题   请问这是为什么啊

**Comment by monkeyWie** [comment]
3.0版本已经修复该bug。
