### ISSUE TITLE
macos下下载路径无法选择挂载的ntfs硬盘

### ISSUE THREAD

**Issue by xukangqi** [proxyee-down-org/proxyee-down#553]
### 问题描述(必要)
ntfs硬盘已经用Tuxera软件进行挂载，能够正常进行读写，但是在新建下载任务弹窗中没有找到挂载的硬盘，希望能够修复一下
### 版本号(必要)
2.54
### 操作系统(必要)
macos 10.13.6

**Comment by monkeyWie** [comment]
手动输入路径试试看

**Comment by xukangqi** [comment]
手动输入路径可以

**Comment by monkeyWie** [comment]
好的，新版本会尝试修复这个问题的
