### ISSUE TITLE
Mac OS X 下自动下载失去响应

### ISSUE THREAD

**Issue by hy345** [proxyee-down-org/proxyee-down#557]
### 问题描述(必要)
在Mac OS X下每次通过自动下载下载了东西后，就会无法打开，显示应用程序失去响应。等了很久还是这样，需要 `sudo killall java` 然后重新打开才可以继续使用。
### 版本号(必要)
2.54
### 操作系统(必要)
Mac OS X 10.10.5
### 相关日志
失去响应后会产生日志，但是大小均为 $0\ Byte$，就不上传了。

**Comment by hy345** [comment]
我个人的解决方法是把 `uiModel` 改成 2 然后用网页端进行操作，可以有响应。

**Comment by monkeyWie** [comment]
硬盘的文件格式是什么？

**Comment by LiWeiQiangAndroid** [comment]
最新Mac测试版系统10.14b6设置自动下载GUI会卡死，应该是瞬间创建磁盘空间过大卡死

**Comment by monkeyWie** [comment]
3.0版本已经修复该bug。
