### ISSUE TITLE
建议提供关于代理设置的相关说明

### ISSUE THREAD

**Issue by qq938403611** [proxyee-down-org/proxyee-down#559]
我原本就用Omega管理梯子，貌似嗅探模式直接无法正常工作。
添加相关模式和规则后，关闭嗅探模式刷新梯子的pac设置，系统代理恢复正常，下载工作正常

只是经过测试，即使分段数拉满，e3 cpu占用率15%左右，下载速度仍然不到10mb/s，相比用Aria2的Pandownload的5%占用率和满速25+mb/s速度来说相形见绌。

**Comment by monkeyWie** [comment]
如果装了插件的话教程里有写的。
