### ISSUE TITLE
下载发送到Aria2下载

### ISSUE THREAD

**Issue by 1424753988** [proxyee-down-org/proxyee-down#560]
### 问题描述(必要)
能否增加一个功能，就是将下载发送到centos6 系统已经搭建好的Aria2里面进行下载？因为服务器的速度比本地快太多。
### 版本号(必要)
2.54
### 操作系统(必要)
win10
### 相关截图
类似于这个插件的功能
<img src="https://i.loli.net/2018/08/02/5b62cb624f065.png" alt="360截图17900101297745.png" title="360截图17900101297745.png" />

**Comment by monkeyWie** [comment]
现在软件还不支持已纯命令行版本的服务运行，如果你的服务器是支持窗口程序的话就可以实现你的功能。
