### ISSUE TITLE
淘宝上看到有贩卖该软件的，希望能关注一下。

### ISSUE THREAD

**Issue by wangjiewen** [proxyee-down-org/proxyee-down#562]
https://detail.tmall.com/item.htm?id=572210946858&spm=a1z09.2.0.0.512f2e8dcpOLub&_u=21kq10dl5030
以上为淘宝链接，一个卖3.3元，已经有2000多的评论。
找淘宝投诉找了半天只有投诉延迟发货的。。。无奈来这边提个issue
![1448381906](https://user-images.githubusercontent.com/23210529/43587407-c0d4bbf0-969c-11e8-9ee3-2d1557359f36.jpg)
![740843545](https://user-images.githubusercontent.com/23210529/43587413-c49fa178-969c-11e8-82be-94ddd2c99c21.jpg)

**Comment by monkeyWie** [comment]
首先谢谢你的反馈，不过在中国你懂的，这种情况怕是举报了也没什么用。。 希望被收智商税的人能在软件里看到这个是一个开源免费的软件吧。

**Comment by hsiayuchih** [comment]
淘宝真的是个神奇的网站，什么都能卖。之前还看到很多人在卖工口本资源，举报后官方并没有回复我

**Comment by BlackHole1** [comment]
还是谢谢你的反馈，后期我们可以在软件的"关于"里，注明是免费开源软件的 @monkeyWie
