### ISSUE TITLE
mac版下载自动大文件自动跳转到客户端下载

### ISSUE THREAD

**Issue by HanMessi** [proxyee-down-org/proxyee-down#564]

**Comment by BlackHole1** [comment]
@henry-huan Has the certificate been installed?

**Comment by fafactx** [comment]
Clearly its a big problem，maybe should we delete it

**Comment by fafactx** [comment]
已经解决了你，用百度网盘网页版本，先自己分享下你要下文件，在用分享页面进入下载按钮就好。
