### ISSUE TITLE
2018年8月4日发现用不了了

### ISSUE THREAD

**Issue by bingcheng1998** [proxyee-down-org/proxyee-down#567]
### 问题描述(必要)
2018年8月4日发现用不了了
### 版本号(必要)
2.54
### 操作系统(必要)
macOS High Sierra
### 相关截图
![1](https://ws1.sinaimg.cn/large/006tNc79ly1ftxzv0j8vgj31kw0w5t9m.jpg)
![2](https://ws3.sinaimg.cn/large/006tNc79ly1ftxzw7qf0tj31kw0zkdij.jpg)

**Comment by monkeyWie** [comment]
看看代理是否设置正确

**Comment by bingcheng1998** [comment]
怀疑插件被百度云屏蔽了。上次是用不了，现在（8月7日）直接只要是打开插件就百度云网站显示无法建立安全连接，直接整个网页不加载（MACOS，safari）。

**Comment by BlackHole1** [comment]
测试没有问题，请尝试更换其他的油猴插件
