### ISSUE TITLE
可不可以做成web服务界面

### ISSUE THREAD

**Issue by dream1986** [proxyee-down-org/proxyee-down#570]
用下载机，或者nas的情况下，如果软件做成web服务在nas上运行的话，会比较方便，

**Comment by monkeyWie** [comment]
现在server是有了，不过ui界面的话还没做呢
https://github.com/proxyee-down-org/pdown-rest

**Comment by SilverLeaves** [comment]
前端，用Vue做成SPA或者PWA会好很多。

**Comment by BlackHole1** [comment]
@SilverLeaves 单独分离出去的话，其实目前已经分离的，只是没有分的那么彻底。
@dream1986  ui界面我们3.0正在做
