### ISSUE TITLE
建议修改”剩余下载时间“计算方法

### ISSUE THREAD

**Issue by luminouser** [proxyee-down-org/proxyee-down#572]
如图中红框所示。
根据木桶原理，这样计算会不会比较合适：
设在某一次下载任务中，总数据量为 A 兆字节，分段数为 B 个，时间过去 t 秒后，所有分段中**已下载数据量最少的**那个分段下载的数据量为 s(t) 兆字节，该分段当前下载速度为 k(t) 兆字节/秒，则剩余下载时间 F(A, B, t) 为

![image](https://user-images.githubusercontent.com/27768328/43814666-22eeeef4-9afe-11e8-8fca-6a6d1a02235b.png)

![image](https://user-images.githubusercontent.com/27768328/43783034-4fc7aeb8-9a93-11e8-862a-61912cdce568.png)

**Comment by BlackHole1** [comment]
感谢你的建议，由于这块不是我负责的，帮你at下相关的负责人 @monkeyWie 。 @monkeyWie 如果你觉得这个建议不错，可以把当前issue的labels设置为`enhancement`，然后加入到`Project`中的`Enhancement Card`下

**Comment by BlackHole1** [comment]
刚才问了一下 @monkeyWie ，请问是否可以提供此方案和目前软件的方案 有什么优缺点么？我们没有看出有什么优缺点

**Comment by luminouser** [comment]
假设：
1. 该软件通过将文件分段，同时下载。
2. 各分段的下载速度没有相关性，在0 - 100 KB/s之内。
3. 目前软件的方案认为**剩余下载时间**只取决于**剩余待下载数据量**以及**当前总下载速度**。
4. 此方案提出：剩余下载时间应由**最慢的那个分段**决定。

先考虑一种极端情况，只要某一个未完成的分段下载速度为 0 并一直持续下去，则该文件在不刷新链接的情况下是无法下载完成的。即：剩余下载时间不可计算。

进而可以一般性地说，剩余下载时间遵循木桶原理。也就是说，此次任务的下载时间，**仅仅**取决于所有分段中速度最慢、任务时间最长的那一个。这也是多增加分段可以减少下载时间的原因。

**Comment by BlackHole1** [comment]
感觉非常不错，不过因为这个属于优化的范围，且功能非必须，我们将会把task移到4.0版本去做，或者3.0版本上线后的一段时间内，我们将发布一个小版本进行优化

**Comment by BlackHole1** [comment]
还是十分感谢你提出来的建议
