### ISSUE TITLE
对于分段数的一点建议

### ISSUE THREAD

**Issue by dawn-lc** [proxyee-down-org/proxyee-down#576]
建议加入根据文件大小自动计算建议分段数的功能，无论文件大小都是默认分段数感觉有点不方便

**Comment by dawn-lc** [comment]
而且自动解压也不应该默认开启

**Comment by dawn-lc** [comment]
比如：每4mb分一段
如果是1024mb根据上面的就是1024/4=256段

**Comment by luminouser** [comment]
百度对分段数的限制解除了吗，我记得好像分段数大于60多就不怎么好用了

**Comment by BlackHole1** [comment]
自动计算分段数，需要通过当前网速以及大小进行计算，暂时觉得这个task不是特别的重要。我们后期可以去尝试做下，但是近期(3.0版本)可能不会上线

**Comment by ruixingchen** [comment]
个人感觉没有这个必要, 每个人的网络情况都不一样, 要是路由的承载能力或者机器的处理能力跟不上, 还不如每次下载都手动去调整分段, 我在办公室下载, 不限速的情况下, 会导致办公室整个断网, 与之相比, 加一个限速才是最主要的, 我现在都是通过在虚拟机中下载然后通过网络工具来限速, 哈哈

**Comment by monkeyWie** [comment]
分段数这个和文件大小没关系，取决与你的带宽和服务器下载的带宽。
