### ISSUE TITLE
输入密码时说初始化失败？？

### ISSUE THREAD

**Issue by aaa20023003** [proxyee-down-org/proxyee-down#577]
### 问题描述(必要)
启动时，输入密码后就说error occurred，具体请看下图

**Comment by BlackHole1** [comment]
检查下jdk的环境变量，如果没有问题，尝试重装jdk试下

**Comment by aaa20023003** [comment]
谢谢！




| |
夏
邮箱：aaa20023003@163.com
|

签名由 网易邮箱大师 定制

在2018年08月08日 13:34，Black-Hole 写道：

检查下jdk的环境变量，如果没有问题，尝试重装jdk试下
