### ISSUE TITLE
能不能使用已安装的jre

### ISSUE THREAD

**Issue by efsg** [proxyee-down-org/proxyee-down#580]

**Comment by monkeyWie** [comment]
可以啊，直接下载jar包运行

**Comment by efsg** [comment]
proxyee-down.jar和main文件夹中的proxyee-down.jar有什么区别，只有main文件夹中的proxyee-down.jar才能打开

**Comment by efsg** [comment]
mac使用时safari会提示此连接为非私人连接

**Comment by monkeyWie** [comment]
用main里的jar运行就好了，私人连接的问题是需要安装证书。具体看看FAQ.
