### ISSUE TITLE
程序的证书与SSR代理冲突

### ISSUE THREAD

**Issue by 15372843021** [proxyee-down-org/proxyee-down#586]
switchy自动切换里设置了youtube用酸酸乳，百度云用proxyee。
当我能正常使用proxyee的时候，酸酸乳会没用。
切换酸酸乳的代理模式后，酸酸乳能正常使用，proxyee就会没用，左上角没有标志
### 2.54
###win10专业版 1803

**Comment by 15372843021** [comment]
不是证书，就是程序，忘了修改了

**Comment by BlackHole1** [comment]
这是一个已知的bug，我们将会在3.0进行修复
