### ISSUE TITLE
Mac从OneDrive下载proxyee-down时被卡死

### ISSUE THREAD

**Issue by xiebruce** [proxyee-down-org/proxyee-down#589]
首先我要说一下，我说的这个问题不是proxyee-down的问题，我只是想吐槽一下OneDrive顺便看看有没有人跟我一样中招的？

这个OneDrive真是厉害，我电脑是Mac，我用谷歌浏览器从OneDrive上下载本软件的时候，无法选择下载到哪个盘符（正常都会自动选择Downloads的），我手动选择竟然卡死了，无法下载，我找Sarafi下载，可以下载，但是Finder打不开了，按住option右击Finder重启试了，无效！option+command+esc找到浏览器打浏览器强制关了，找到finder强制重启，无效，Finder还是打不开，没办法，那我注销登录Mac总可以了吧？就剩一彩色小圆圈一直在转，等了好久还转，无奈长按电源键重启了，不知道其他人有遇到这样的问题吗？真是奇怪啊，一个网页把我电脑给整挂了！

**Comment by monkeyWie** [comment]
额 网页下载还没厉害到能把电脑弄死机的程度吧。

**Comment by xiebruce** [comment]
@monkeyWie 真心不骗你哦，你可以试试， 这个我也是第一次见，我系统是10.13.1，一直没升级，因为没有大版本，而且经常一升级我的Parallel Desktop就不管用了
