### ISSUE TITLE
网盘的下载非常棒，但不能用在分享中，怎么办

### ISSUE THREAD

**Issue by shenyoucn** [proxyee-down-org/proxyee-down#590]
### 相关截图

![1](https://user-images.githubusercontent.com/34588394/44242628-25eeb980-a1fd-11e8-8524-6299af0bcf12.jpg)
![2](https://user-images.githubusercontent.com/34588394/44242650-3ef76a80-a1fd-11e8-853a-d6859a9e5da8.jpg)

### 相关日志
网页版中，网盘浏览的时候没有问题，可以用proxyee下载
但点边上的分析，群组中的文件就出不来proxyee，点击下载还是跳出百度网盘客户端
怎么办？

**Comment by BlackHole1** [comment]
感谢你的赞赏，更换别的油猴脚本就好。

**Comment by shenyoucn** [comment]
看了你的回复，下了tampermonkey用了百度网盘直接下载助手，还是不行
能再指点一下应该用那个吗，谢谢

**Comment by shenyoucn** [comment]
反复地试了一下，结果还是一样，网盘部分没有问题，分享里不能使用
![qq 20180824132433](https://user-images.githubusercontent.com/34588394/44568121-00872000-a7a8-11e8-8695-83b8e637ccbf.jpg)
![qq 20180824132309](https://user-images.githubusercontent.com/34588394/44568128-067d0100-a7a8-11e8-969e-75bb5e8b4e15.jpg)
