### ISSUE TITLE
mac 10.13.1 启动时无法输入密码 版本号2.54

### ISSUE THREAD

**Issue by mnbgtyujh** [proxyee-down-org/proxyee-down#594]
![image_1534580861 972437](https://user-images.githubusercontent.com/42489385/44297422-b7e0ea00-a303-11e8-899f-dac68bfa57a5.jpg)
mac 10.13.1
启动时无法输入密码
版本号2.54

**Comment by fafactx** [comment]
不存在的。我的刚刚试了可以。

**Comment by mnbgtyujh** [comment]
不行啊，按键盘完全没有反应，那个图标带锁，不是正常的光标

**Comment by BlackHole1** [comment]
mac以及linux终端下输入密码是不会显示出来的。。

**Comment by monkeyWie** [comment]
更新到3.0https://github.com/proxyee-down-org/proxyee-down/tree/v3.0#%E8%BD%AF%E4%BB%B6%E4%B8%8B%E8%BD%BD
