### ISSUE TITLE
批量下载速度只有几十K/S

### ISSUE THREAD

**Issue by yabalababoom** [proxyee-down-org/proxyee-down#596]
### 相关截图
![default](https://user-images.githubusercontent.com/29530605/44300320-808c3080-a337-11e8-9a2f-6e576916f52a.png)

**Comment by jc654123** [comment]
是不是链接数太多呢？最好不要超过64.

**Comment by BlackHole1** [comment]
没有复现成功，可能是你当时网速环境不太好
