### ISSUE TITLE
在国外的网盘上无法下载文件

### ISSUE THREAD

**Issue by gitgit2018** [proxyee-down-org/proxyee-down#598]
### 问题描述(必要)
国外的网盘上，比如Rapidgator, 在文件分享页上点击下载，proxyee-down里下的是 .js格式的文件，而不是想要下的文件。另外，不知道能不能实现像网盘中转站一样的功能？只用文件的网址就可以生成下载链接？
### 版本号(必要)
2.54
### 操作系统(必要)
mac os 10.13.1

**Comment by monkeyWie** [comment]
你可以用浏览器下载，然后在浏览器里把真实的下载链接复制出来创建任务

**Comment by gitgit2018** [comment]
试了这个方法，还是下载不了：无法识别文件，识别成了.xxx格式，而且不支持分段。

**Comment by monkeyWie** [comment]
那可能是要带cookie下载吧

**Comment by gitgit2018** [comment]
怎么带cookie下载啊？

**Comment by gitgit2018** [comment]
不知道能不能实现像网盘中转站一样的功能？只用文件的网址就可以生成下载链接？

**Comment by monkeyWie** [comment]
试试用全网嗅探模式下载

**Comment by gitgit2018** [comment]
一直都是用的全网嗅探模式，还是下载不了

**Comment by monkeyWie** [comment]
全网嗅探，没用代理插件吧？

**Comment by gitgit2018** [comment]
用了SwitchyOmega插件也还是无法下载
