### ISSUE TITLE
无限地弹出"未知文件.xxx"的下载

### ISSUE THREAD

**Issue by cxwithyxy** [proxyee-down-org/proxyee-down#601]
### 描述

启动steam后, 可能由于steam的自动更新, 导致 proxyee-down 不断弹出下载

另外, "开始任务"的弹框 层级比 "确认取消"弹框 要高, 因此导致 "开始任务"的弹框 无法 "取消" , 只能 "创建"了

**Comment by monkeyWie** [comment]
把嗅探模式关了先

**Comment by monkeyWie** [comment]
@164738777 可以把代理的端口换一下
