### ISSUE TITLE
百度云页面不显示proxyee-down标记

### ISSUE THREAD

**Issue by capilano-1** [proxyee-down-org/proxyee-down#602]
### 相关日志： 我尝试了-1.删除Chrome Cache; 关闭重启Chrome。无效.2.关闭重启Proxyee-Down。无效。
提前感谢！

**Comment by BlackHole1** [comment]
证书安装了么

**Comment by Tiandians** [comment]
@BlackHole1 
我有同样问题
![2](https://user-images.githubusercontent.com/35755846/44967938-5eb9bd00-af77-11e8-884f-9effca276706.png)
版本：3.0-Beta
证书已按指导安装
操作系统：Skip跳跃预览版 Windows10 1803 18219.1000
使用浏览器：Chromium 69.0.3493.5，[Free-VPN](https://github.com/free-vpn/chrome)内置代理VPN版
后又使用FireFox61.0.2测试，仍无显示（火狐已按教程手动安装证书）
![3](https://user-images.githubusercontent.com/35755846/44968088-48f8c780-af78-11e8-8e37-dcc84f5055bd.png)

**Comment by sungda** [comment]
我的2.54没了，下载了新版的3.0，发现还是如此
系统：windows7
浏览器：chrome或其它

**Comment by monkeyWie** [comment]
在3.0版本里，使用了SwitchyOmega 插件的可以看看这里的教程
https://monkeywie.github.io/2018/09/05/proxyee-down-3-0-guide/#%E6%89%A9%E5%B1%95%E6%A8%A1%E5%9D%97
