### ISSUE TITLE
获取选中文件失败

### ISSUE THREAD

**Issue by licoba** [proxyee-down-org/proxyee-down#604]
### 问题描述(必要)
获取选中文件失败
### 版本号(必要)
2.54
### 操作系统(必要)
win7 64位
### 相关截图
![Alt text](http://image.licoba.top/2579507e79ab4079a84700f7314f7865.png)

**Comment by BlackHole1** [comment]
更换别的油猴脚本尝试一下

**Comment by monkeyWie** [comment]
更新到3.0 https://github.com/proxyee-down-org/proxyee-down/tree/v3.0#%E8%BD%AF%E4%BB%B6%E4%B8%8B%E8%BD%BD
