### ISSUE TITLE
检测更新 服务器异常

### ISSUE THREAD

**Issue by mmmaomao21** [proxyee-down-org/proxyee-down#607]

**Comment by mmmaomao21** [comment]
![image](https://user-images.githubusercontent.com/23095457/44594078-c8a7c900-a7f7-11e8-8854-aa9c6f8fc643.png)

**Comment by BlackHole1** [comment]
开下全局代理上尝试下

**Comment by monkeyWie** [comment]
请手动更新到3.0https://github.com/proxyee-down-org/proxyee-down/tree/v3.0#%E8%BD%AF%E4%BB%B6%E4%B8%8B%E8%BD%BD
