### ISSUE TITLE
有没有机会加上目录自动同步功能，基于百度网盘来做

### ISSUE THREAD

**Issue by Aliador** [proxyee-down-org/proxyee-down#614]
最近百度网盘的同步功能开始收费了，不过我盘倒是挺大的，想基于它来做一个文件同步的工具，可行吗？

**Comment by hy345** [comment]
他没法获取你的网盘里面有啥啊……他的下载原理大概是把下载链接不给浏览器下而是拦下来自己下，得要本来是浏览器下载的东西才可以下载吧

**Comment by BlackHole1** [comment]
目前项目只支持下载。上传不支持。这是一个下载器。而不是专门为百度网盘开发一个破解版百度网盘。如果你想做同步功能的话。推荐去看下这里：https://github.com/iikira/BaiduPCS-Go
