### ISSUE TITLE
老大，这是啥浏览器的扩展？？无法导入chrome

### ISSUE THREAD

**Issue by wangyujie96** [proxyee-down-org/proxyee-down#616]
Unrecognized manifest key 'contentScripts'.
Unrecognized manifest key 'proxyWildcards'.
Unrecognized manifest key 'title'.

完全无法使用啊，，，，
而且我之前手动添加了  "manifest_version":2, 一行 = =不然还要多一个错误

**Comment by monkeyWie** [comment]
这个插件不是浏览器的插件哦，是下载器扩展模块的
