### ISSUE TITLE
3.0.0 测试版 Mac 报错

### ISSUE THREAD

**Issue by hy345** [proxyee-down-org/proxyee-down#617]
### 问题描述(必要)
3.0.0 测试版运行报错
### 版本号(必要)
3.0.0 beta
### 操作系统(必要)
MAC OS X 10.12.6
### 相关日志
20:03:35.408 [Thread-6] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
20:03:35.403 [Thread-5] ERROR org.pdown.gui.DownApplication - initMacTool error
java.lang.NullPointerException: null
	at org.pdown.gui.DownApplication.lambda$initMacTool$3(DownApplication.java:160)
	at java.lang.Thread.run(Thread.java:748)

**Comment by monkeyWie** [comment]
@hy345  mac版本现在还没有出
