### ISSUE TITLE
3.0版本:使用SwitchyOmega时,点击批量推送下载无反应,但用全局代理时可以正常推送

### ISSUE THREAD

**Issue by xy-233** [proxyee-down-org/proxyee-down#618]
3.0版本
使用SwitchyOmega时,点击批量推送下载无反应,但全局代理时可正常推送

**Comment by hsiayuchih** [comment]
3.0版本哪里有的下？只看到有linux未编译版...

**Comment by monkeyWie** [comment]
3.0版本扩展模块设置说明https://github.com/proxyee-down-org/proxyee-down/tree/v3.0#%E6%89%A9%E5%B1%95%E6%A8%A1%E5%9D%97
