### ISSUE TITLE
3.0 有mac版的吗？

### ISSUE THREAD

**Issue by winyeer** [proxyee-down-org/proxyee-down#619]

**Comment by monkeyWie** [comment]
mac版本现在还没有出

**Comment by z793242777** [comment]
现在显示的那个版本Mac不能用吗？怪不得一直打不开

**Comment by monkeyWie** [comment]
3.0版本已经发布https://github.com/proxyee-down-org/proxyee-down/tree/v3.0#%E8%BD%AF%E4%BB%B6%E4%B8%8B%E8%BD%BD
