### ISSUE TITLE
3.0应用打开及扩展问题 

### ISSUE THREAD

**Issue by fanghuan27** [proxyee-down-org/proxyee-down#620]
![image 025](https://user-images.githubusercontent.com/1284794/44936989-b6a2c900-ada9-11e8-9b16-96b1148c4fff.png)
![image 027](https://user-images.githubusercontent.com/1284794/44937101-2f098a00-adaa-11e8-9c6a-f392bd5fe3a3.png)

**Comment by ttxhxz** [comment]
同上，win10打开直接显示错误。。。
![snipaste_2018-09-01_10-50-26](https://user-images.githubusercontent.com/24288387/44941699-ec10dc00-add4-11e8-90b3-ba45d14c84cc.jpg)

**Comment by hsiayuchih** [comment]
你们在哪里下的？我这边看没有windows版的啊，只有linux下的

**Comment by monkeyWie** [comment]
@fanghuan27 用谷歌浏览器，目前测试版只支持谷歌浏览器
@ttxhxz 是不是在中文目录下启动的
@hsiayuchih  在群里发了测试版

**Comment by ttxhxz** [comment]
@monkeyWie 不是的，是英文路径，我下的是github里面Releases你发布的3.0版本，
![image](https://user-images.githubusercontent.com/24288387/44951584-7b33f780-ae9a-11e8-8111-2b6cccf2d8f6.png)
打开还是一样的效果。系统是win10  1803版本的

**Comment by wubo-minions** [comment]
![bug](https://user-images.githubusercontent.com/36689025/44954253-df25e280-aed1-11e8-99a3-44b8cff88755.png)
linux 启动报错

**Comment by hsiayuchih** [comment]
@monkeyWie 打算等正式版了再发布到github上吗？

**Comment by ZouLlChenYd** [comment]
用管理员启动

**Comment by ttxhxz** [comment]
@ZouLlChenYd .jar文件没的用管理员启动啊

**Comment by ZouLlChenYd** [comment]
![tim 20180904101545](https://user-images.githubusercontent.com/22631731/45006441-81a5a900-b02b-11e8-90fb-0d132c39b8ec.png)

**Comment by UnaHe** [comment]
请问~~~ 3.0测试版要怎么用?

**Comment by hustarbor** [comment]
3.0正式版，win10 1804，同时有JRE10和8u181，把JRE10卸载后一切正常

**Comment by monkeyWie** [comment]
3.0版本已经修复该bug。
