### ISSUE TITLE
3.0 推送任务偶尔失败，批量推送会创建多余文件夹

### ISSUE THREAD

**Issue by lanmeilove** [proxyee-down-org/proxyee-down#622]
### 问题描述
1 批量推送任务会为每一个文件创建单独的文件夹。任务一多就出现了海量的冗余文件夹。
2 创建直链任务或者批量推送任务，会偶尔的失败。等一下重新创建又可能成功。见日志的内存问题。
3 创建批量推送任务，成功后，下载任务列表没显示，需要手动刷新一下才能显示出来

### 版本号
3.0 beta

### 操作系统
Windows 10

### 相关截图
![sketch1](https://user-images.githubusercontent.com/13329261/44943716-b46a5a00-adfd-11e8-8a6b-88cef0c26943.png)
![sketch2](https://user-images.githubusercontent.com/13329261/44943717-b6ccb400-adfd-11e8-95c2-27844de053ff.png)
![sketch3](https://user-images.githubusercontent.com/13329261/44943718-b92f0e00-adfd-11e8-834c-cb1bc394eeac.png)

### 相关日志
error 都是雷同的，内存问题
[pdown-error.2018-09-01.log](https://github.com/proxyee-down-org/proxyee-down/files/2342151/pdown-error.2018-09-01.log)
比如
2018-09-01 15:04:46.718 [nioEventLoopGroup-8-1] ERROR org.pdown.core.boot.HttpDownBootstrap - down onChunkError:
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 117440519, max: 129761280)

**Comment by xy-233** [comment]
创建分享,在分享链接里下载就不会推送失败了

**Comment by monkeyWie** [comment]
bug已经修复了，把百度云扩展升级到最新版本。
