### ISSUE TITLE
打开软件提示“class org/pdown/gui/runner not found”和"failed to launch jvm”

### ISSUE THREAD

**Issue by kfkdxd** [proxyee-down-org/proxyee-down#624]
### 相关截图
![Uploading QQ图片20180901165911.png…]()
![Uploading Snipaste_2018-09-01_16-59-07.png…]()
### 相关日志
[Uploading pdown-error.2018-08-31.log…]()

**Comment by monkeyWie** [comment]
目前测试版中文目录运行有问题，不要解压到 中文目录运行就好
