### ISSUE TITLE
打开软件时上方提示“程序异常，拒绝访问”

### ISSUE THREAD

**Issue by s648846217** [proxyee-down-org/proxyee-down#625]
win10 1803 64位系统，版本3.0，尝试过还原hosts以及管理员运行均无法解决，文件路径也是英文的，但可以正常浏览软件界面。

**Comment by zzzliang** [comment]
一样的情况，管理员权限也是禁止访问

**Comment by monkeyWie** [comment]
这个问题不影响使用，bug原因已经确认了会在新版本修复的

**Comment by zzzliang** [comment]
我好像不能用，软件打开后浏览器没有提示，也不能用，插件也装了

**Comment by s648846217** [comment]
chrome最新版没有出现PD下载，折腾过证书也没用，不知道哪里有问题，打开软件上面一直是”程序异常，拒绝访问“，软件能设置也能保存，就是不能下载，手动用脚本提取链接新建下载提示“响应状态码异常”，2.54版本倒是可以用。

**Comment by zzzliang** [comment]
开全局代理 我的直接就能用了

**Comment by s648846217** [comment]
已解决，代理冲突问题，关了代理就好了=。=，谢谢大佬。
