### ISSUE TITLE
2.54 自动解压后的压缩文件解压报错

### ISSUE THREAD

**Issue by amostang** [proxyee-down-org/proxyee-down#630]
问题描述：最近下载的文件都是自动解压后，我经常不能成功解压里面的文件，基本都是报错损坏，或者一堆文件有部分无法解压
版本号 2.54
操作系统(  win 10 x64

**Comment by amostang** [comment]
@YourLuck 现在最新版本不是2.54吗，我自动检测升级也不行？

**Comment by monkeyWie** [comment]
@amostang 3.0版本下载https://github.com/proxyee-down-org/proxyee-down/tree/v3.0#%E8%BD%AF%E4%BB%B6%E4%B8%8B%E8%BD%BD
