### ISSUE TITLE
能否支持文件保存除本地磁盘外的其他盘 如本地nas的盘

### ISSUE THREAD

**Issue by laynexx** [proxyee-down-org/proxyee-down#634]
### 相关截图 
![image](https://user-images.githubusercontent.com/41958288/45052773-9b420180-b0ba-11e8-919c-9431e1776440.png)
![image](https://user-images.githubusercontent.com/41958288/45052814-c4629200-b0ba-11e8-9e62-b55217299eaf.png)

**Comment by monkeyWie** [comment]
3.0版本已经支持了
