### ISSUE TITLE
希望3.x版本任务栏右键加上 嗅探模式 真的很好用

### ISSUE THREAD

**Issue by 646222123** [proxyee-down-org/proxyee-down#635]
### 问题描述(必要)
希望3.x版本任务栏右键加上 嗅探模式 真的很好用
### 版本号(必要)
3.0
### 相关截图
![image](https://user-images.githubusercontent.com/26131201/45068338-90f32800-b0f9-11e8-8ac2-7b6a18e8b769.png)
![image](https://user-images.githubusercontent.com/26131201/45068422-ecbdb100-b0f9-11e8-9578-2a12b081430e.png)

**Comment by 646222123** [comment]
![image](https://user-images.githubusercontent.com/26131201/45068403-dca5d180-b0f9-11e8-9233-989a20acd653.png)

**Comment by monkeyWie** [comment]
3.0之后已经没有嗅探模式了，全部基于扩展模块来使用

**Comment by monkeyWie** [comment]
会出一个全网嗅探的扩展，到时候装上使用就行

**Comment by 646222123** [comment]
nice , 谢谢回复



sunyigao@foxmail.com
 
发件人： monkeyWie
发送时间： 2018-09-06 16:10
收件人： proxyee-down-org/proxyee-down
抄送： 孙毅高; Author
主题： Re: [proxyee-down-org/proxyee-down] 希望3.x版本任务栏右键加上 嗅探模式 真的很好用 (#635)
会出一个全网嗅探的扩展，到时候装上使用就行

**Comment by monkeyWie** [comment]
3.0扩展商店已经加上了，去下载最新的3.0版本吧
