### ISSUE TITLE
3.0 外网访问

### ISSUE THREAD

**Issue by bcc290786** [proxyee-down-org/proxyee-down#639]
### 问题描述(必要)
3.0 无法使用外网访问
### 版本号(必要)
v3.0
### 操作系统(必要)
win10 x64
### 相关截图
![default](https://user-images.githubusercontent.com/6201233/45132527-ea278e00-b1c3-11e8-852f-cfb22adce546.jpg)

**Comment by bcc290786** [comment]
Fixed.

**Comment by monkeyWie** [comment]
为什么要在外网访问，这是个本地应用。

**Comment by bcc290786** [comment]
2.54 可以远程访问，就想问问3.0怎么拿掉了
另外我想外网 是因为我架在VPS上

**Comment by monkeyWie** [comment]
如果要访问的话用7478端口，或者把ui模式设置成浏览器模式打开就能看到网址了。
