### ISSUE TITLE
建议在3.0中增加解压缩模块。

### ISSUE THREAD

**Issue by kevinraines** [proxyee-down-org/proxyee-down#641]
在2.54版本中的解压缩工具模块非常有用，建议在3.0中也加入改模块，提供单独解压入口。

**Comment by monkeyWie** [comment]
压缩工具会独立出来，因为3.0要做一个纯粹的下载器，而不是某盘的下载器

**Comment by kevinraines** [comment]
独立出来最好，您说的对，proxyee-down应当是通用型的下载器，期待后续版本。赞赞赞！

**Comment by monkeyWie** [comment]
已经独立开源出来了：https://github.com/monkeyWie/bdy-unpack

**Comment by kevinraines** [comment]
欧克。收到。





在 2018-09-13 11:16:17，"monkeyWie" <notifications@github.com> 写道：


已经独立开源出来了：https://github.com/monkeyWie/bdy-unpack
