### ISSUE TITLE
请教：2.54有可执行的exe文件，可以正常使用。3.0-RC 如何安装使用？

### ISSUE THREAD

**Issue by zhukai168** [proxyee-down-org/proxyee-down#642]

**Comment by SugarKowalczyk** [comment]
排一下。

**Comment by monkeyWie** [comment]
3.0有可执行文件下载了，具体请看：https://github.com/proxyee-down-org/proxyee-down/tree/v3.0#%E8%BD%AF%E4%BB%B6%E4%B8%8B%E8%BD%BD
