### ISSUE TITLE
请教：3.0 是否支援 windows-x86 ，好像2.54 版？

### ISSUE THREAD

**Issue by JYeung111** [proxyee-down-org/proxyee-down#643]
请問 3.0 是否支援 windows-x86，好像2.54 版？
那處有可执行的exe文件下載？

現在 的 3.0-RC jar 版 在 winXP x86 32bit 中 使用上出現問題:
能起動但不能修改 system setting 和儲存!
不能人手添加任務！

![pyee1](https://user-images.githubusercontent.com/41117798/45165560-acf4e780-b227-11e8-80f5-dc220a1201e5.png)
![pyee2](https://user-images.githubusercontent.com/41117798/45165570-afefd800-b227-11e8-9e58-3ecf8b735400.png)
![pyee3](https://user-images.githubusercontent.com/41117798/45165575-b2523200-b227-11e8-9528-d574625a298c.png)

**Comment by monkeyWie** [comment]
暂时不支持windows xp
