### ISSUE TITLE
mac打开报错

### ISSUE THREAD

**Issue by JianWirt** [proxyee-down-org/proxyee-down#644]
### 
<img width="392" alt="2018-09-07 12 14 46" src="https://user-images.githubusercontent.com/17246517/45170736-27773480-b233-11e8-9dc6-6bfa8a88ca03.png">

**Comment by shawneluis** [comment]
看起来是JRE版本的问题，pd好像只支持8，你用的应该是9或者10吧。
解决办法就是下载JDK8并安装
```
cd ~
atom .bash_profile
```
然后添加新的环境变量
```
# JDK versions
export JAVA_8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
...
export JAVA_HOME=$JAVA_8_HOME
```
这个时候可以在terminal查看`java -version`，如果是`java version "1.8.0_131"`，就成功了。（记得重开terminal或者source .bash_profile）
```
cd jar包所在的位置
java -jar proxyee-down-main.jar
```
一劳永逸的办法就是把bash command写到.bash_profile里
```
# Proxyee-down 3
alias proxyee3="cd ~/proxyee3 && java -jar proxyee-down-main.jar"
```
这样每次打开terminal，输入proxyee3就可以运行了。

**Comment by monkeyWie** [comment]
下载最新的3.0看看

**Comment by liushihao456** [comment]
下载了releases里最新的版本，还是有同样的问题。我用的是jre10

**Comment by monkeyWie** [comment]
@liushihao456 3.0版本下载
https://github.com/proxyee-down-org/proxyee-down/tree/v3.0#%E8%BD%AF%E4%BB%B6%E4%B8%8B%E8%BD%BD

**Comment by shawneluis** [comment]
@monkeyWie mac好像一直都有jre的问题，pd只支持8，我试过9跟10全都出错了，所以最好下载链接附带上jre8，这样应该不会出错了！

**Comment by monkeyWie** [comment]
@shawneluis mac上已经打包成原生的app自带了jre8的

**Comment by shawneluis** [comment]
@monkeyWie 
`String JAVA_CMD_PATH = System.getProperty("java.home") + File.separator + "bin" + File.separator + "java";`
看了眼源码好像调用的是系统的jdk，如果不是8的话，就会报错了。
