### ISSUE TITLE
3.0版无法设置下载路径

### ISSUE THREAD

**Issue by halkong** [proxyee-down-org/proxyee-down#645]
![bug](https://user-images.githubusercontent.com/43053617/45193896-1524e700-b283-11e8-9235-6e2782293b86.JPG)

3.0版进入“软件设置”，点“下载设置”——“路径”，弹出选项卡后无法响应，只能强行退出软件。

**Comment by monkeyWie** [comment]
什么操作系统呢，在创建任务的时候选择路径也会开始吗？

**Comment by monkeyWie** [comment]
参考：https://github.com/proxyee-down-org/proxyee-down/issues/792
