### ISSUE TITLE
启动时不显示主窗口的选项在 3.0 版本上缺失 | Hide Main Window option is missing since version 3.0

### ISSUE THREAD

**Issue by chenyiping1995** [proxyee-down-org/proxyee-down#652]
### 问题描述(必要)
在 2.8 版本上有的启动时不显示主窗口的选项，在 3.0 的设置里似乎没有找到。

### 版本号(必要)
3.0

### 操作系统(必要)
Windows 10 LTSB 2016 (14393.2457) amd64
Java 1.8.0_181 amd64

**Comment by BlackHole1** [comment]
因为3.0只是测试版，可以等正式版发布之后，再看
