### ISSUE TITLE
Windows 版本双击托盘区图标会忽略“UI模式”的设置

### ISSUE THREAD

**Issue by chenyiping1995** [proxyee-down-org/proxyee-down#653]
### 问题描述
即使设置了 UI 模式为“浏览器”，在 Windows 下双击托盘图标也依然会打开程序主窗口 (但是显示白屏)。

使用托盘区菜单里的“显示”无此问题。

### 版本号
3.0

### 操作系统
Windows 10 LTSB 2016 (14393.2457) amd64
JRE 1.8.0_181 amd64

**Comment by monkeyWie** [comment]
已修复
