### ISSUE TITLE
Firefox总是提示Your connection is not secure

### ISSUE THREAD

**Issue by saikyliu** [proxyee-down-org/proxyee-down#657]
Firefox总是提示Your connection is not secure。这在2.X版本还好，但到了3.0版本，页面用的无刷新技术就压根死在页面上了。链接传不到proxyee这，调用不起proxyee来。
版本3.0。
win7系统。

**Comment by monkeyWie** [comment]
扩展功能使用：https://github.com/proxyee-down-org/proxyee-down/issues/709
另外火狐浏览器需要手动安装证书：https://github.com/proxyee-down-org/proxyee-down/blob/v2.5/.guide/common/ca/firefox/read.md
