### ISSUE TITLE
How to set second proxy in v3.0?

### ISSUE THREAD

**Issue by derrrr** [proxyee-down-org/proxyee-down#659]
### 问题描述(必要)
In v2.54, we could set a second proxy.
But I don't find second proxy setting in v3.0.
How to set it?

### 操作系统(必要) Win 7

**Comment by BlackHole1** [comment]
Because 3 is just beta, we haven't added this function yet. You can wait for the official version to go online.

**Comment by monkeyWie** [comment]
Already supported set second proxy in V3.03+.
