### ISSUE TITLE
百度云单文件文件下载特别慢

### ISSUE THREAD

**Issue by yabalababoom** [proxyee-down-org/proxyee-down#660]
### 相关截图
![default](https://user-images.githubusercontent.com/29530605/45253771-85c12600-b39f-11e8-8c2c-75aefb79e7df.png)

**Comment by zhouhounan** [comment]
我默认的64分段数，下载 2M多，还不会加我微信kxphezuo哈。我教你
<img width="675" alt="wx20180909-224516 2x" src="https://user-images.githubusercontent.com/17348292/45265728-5f27eb80-b482-11e8-91e3-899cc6bd596c.png">

**Comment by ovack** [comment]
@yabalababoom 打包压缩下载试试, 我下载单文件也是,打包就满速了

**Comment by BlackHole1** [comment]
可能是账号限制或IP限制
