### ISSUE TITLE
请教3.0如何使用

### ISSUE THREAD

**Issue by eman613** [proxyee-down-org/proxyee-down#661]
### 问题描述(必要)
请教下这个到底要怎么用啊，只有个jar包，解压缩用吗？也没看到exe文件呢？能不能出个新版的使用手册啊？

**Comment by mlgexyz** [comment]
装个jre环境可以直接运行jar文件，或者去RM那边下3.0的win版启动器

**Comment by eman613** [comment]
请问在哪里下呢？

**Comment by mlgexyz** [comment]
RM....

**Comment by BlackHole1** [comment]
可以等3.0正式发布之后，我们会推出的
