### ISSUE TITLE
3.0 onedrive 和 windows 无法下载

### ISSUE THREAD

**Issue by amostang** [proxyee-down-org/proxyee-down#662]
onedrive:
不成功
很抱歉，在 imhx-my.sharepoint.com 目录中找不到 amostang@outlook.com。请稍后再试，同时我们尝试为您自动修复此问题。

windows:
404

**Comment by mlgexyz** [comment]
我这边也是，好像这个od盘的链接不是公开链接...

**Comment by mlgexyz** [comment]
从master主分支RM那边的od盘链接可以找到win版的3.0启动器

**Comment by monkeyWie** [comment]
链接已经更新
