### ISSUE TITLE
无法打开软件

### ISSUE THREAD

**Issue by sherlockHlb** [proxyee-down-org/proxyee-down#663]
Oops! An unrecoverable error occurred.
Please contact your software vendor.
The application will stop now.

版本：3.0
系统版本：win10 X64
没有日志文件

**Comment by zjcxdcq** [comment]
同上。

**Comment by amaztony** [comment]
同上，3.0所有版本都是，且点x后，软件内操作会提示软件异常、拒绝访问。

**Comment by mlgexyz** [comment]
需要jre和启动器，系统装的jre直接运行jar有问题（版本问题？还是需要其他函数入口？）

**Comment by Freezing1** [comment]
所以该怎么解决

**Comment by monkeyWie** [comment]
谢谢反馈，目前版本用命令行工具运行jar包的话，只支持java8

**Comment by Freezing1** [comment]
重新下载了3.02版本，正常了

**Comment by monkeyWie** [comment]
已经修复，需要下载3.03的64版本
