### ISSUE TITLE
3.0 mac版设置异常以及百度云插件无法使用

### ISSUE THREAD

**Issue by xukangqi** [proxyee-down-org/proxyee-down#664]
### 问题描述
![image](https://user-images.githubusercontent.com/16576935/45259842-30b9fa00-b409-11e8-8447-90a0f7745f14.png)
mac版在设置下载路径，限速时，点击保存会显示程序异常。
另外，百度云插件安装后没有显示，就是没有”pd下载“的按钮
### 版本号
3.0 最新那个
### 操作系统
macos 10.13.6
chrome为最新的69版本

**Comment by monkeyWie** [comment]
安装百度云扩展，并开启全局代理

**Comment by c-ly** [comment]
开启全局代理后，扩展中心那里啥都没有，死都刷新不出来
