### ISSUE TITLE
3.0 版本怎么没有百度云解压功能了？

### ISSUE THREAD

**Issue by 919715629** [proxyee-down-org/proxyee-down#665]
3.0 版本怎么没有百度云解压功能了？这个功能很好用啊，为什么要去掉

**Comment by BlackHole1** [comment]
目前3.0还处于测试版，这个功能还没有增加，可以使用2.54版本解压。这个功能后期会加上的

**Comment by monkeyWie** [comment]
独立出来了解压工具https://github.com/monkeyWie/bdy-unzip
