### ISSUE TITLE
添加右键命令

### ISSUE THREAD

**Issue by bngvip** [proxyee-down-org/proxyee-down#666]
提个小建议，建议在下载任务，添加右键。复制下载地址。记录下载地址当前网页。毕竟下载的大多部分都是网盘。不可能有的都做到转存网盘。所以有时候需要刷新下载的时候。地址都找不到了。刷新命令。也就是记录了下载地址。点击刷新命令。即可读取到当前任务的下载地址。直接出现刷新页面！
![1](https://user-images.githubusercontent.com/42488999/45260431-176d7980-b41a-11e8-805a-df10466f1cb6.jpg)

**Comment by DoveBoy** [comment]
点最右边的那个小眼睛图标，能看到下载地址

**Comment by monkeyWie** [comment]
下载器只会记录真实的下载地址，不会记录下载的网页地址。
