### ISSUE TITLE
建议增加智能网速功能

### ISSUE THREAD

**Issue by DoveBoy** [proxyee-down-org/proxyee-down#667]
能不能在新版中增加智能网速功能？类似迅雷的智能调节网速，下载的同时不影响浏览网页，现在下载对网速影响很大，下载的同时根本不能浏览网页了，网页直接无响应。另外问一下新版还支持自动更新百度网盘的链接吗？如果长时间没有下载只是加了下载任务，能通过重新下载的方式刷新下载链接吗？希望能够加入更多的网盘支援就完美了

**Comment by monkeyWie** [comment]
设置里有下载速度限制功能，需要的话可以手动设置下载速度限制
