### ISSUE TITLE
下载进度卡100%

### ISSUE THREAD

**Issue by mlgexyz** [proxyee-down-org/proxyee-down#668]
### 相关截图
![default](https://user-images.githubusercontent.com/21287731/45260935-b1d3ba00-b426-11e8-810e-9e57ad2b5782.png)

**Comment by mlgexyz** [comment]
现在我单任务下载时好像不会出现这个问题，上面的问题是多任务同时下载出现的

**Comment by monkeyWie** [comment]
升级到3.1版本之后就好
