### ISSUE TITLE
MAC下感觉卡顿严重跟放慢镜头似的

### ISSUE THREAD

**Issue by sleikang** [proxyee-down-org/proxyee-down#671]
### 问题描述(必要)
MAC下感觉卡顿严重跟放慢镜头似的
### 版本号(必要)
10.13.3
### 操作系统(必要)
MAC

**Comment by BlackHole1** [comment]
软件版本是多少

**Comment by sleikang** [comment]
应该是Java的原因，我的Mac运行java软件都卡

发自我的 iPhone
