### ISSUE TITLE
Proxy SwitchyOmega 插件提示请选择要下载的文件

### ISSUE THREAD

**Issue by zhangjianbinJAVA** [proxyee-down-org/proxyee-down#672]
### 问题描述(必要)
有时候，在 chrome 浏览器，已经选择了文件或文件夹，但就是一直提示  “请选择要下载的文件件”，使用批量推送下载工能，也会失败
### 版本号(必要)
proxyee-down 3.0
### 操作系统(必要)
windown 10    
Google Chrome | 68.0.3440.106 (正式版本) （64 位）
### 相关截图
![pic](https://user-gold-cdn.xitu.io/2018/9/9/165bdd95804b4f7d?w=1966&h=831&f=png&s=116966)

**Comment by Green-Hack** [comment]
遇到同样的问题...是3.0版本的浏览器插件设置问题？

**Comment by Green-Hack** [comment]
解决了，原来3.0版本搭配浏览器使用得重新配置。
https://github.com/proxyee-down-org/proxyee-down/tree/v3.0
