### ISSUE TITLE
升级Google chrome到最新版之后，无法使用了

### ISSUE THREAD

**Issue by JerryGreenLuan** [proxyee-down-org/proxyee-down#673]
昨天将谷歌浏览器升级到69之后，打开百度云，顶部栏目不再出现proxyee-down，并且百度云点击下载也无法自动打开proxyee-down了。是不是浏览器导致的呢

**Comment by JerryGreenLuan** [comment]
用的就是最新版，刚刚试了一下2.54，也不行

**Comment by zhouhounan** [comment]
@JerryGreenLuan @goodryb 

最新版也可以的，还不会加我微信kxphezuo哈。我教你
<img width="675" alt="wx20180909-224516 2x" src="https://user-images.githubusercontent.com/17348292/45265728-5f27eb80-b482-11e8-91e3-899cc6bd596c.png">
