### ISSUE TITLE
大佬，下载的百度云图片总是缺几张解压不出来

### ISSUE THREAD

**Issue by man2018** [proxyee-down-org/proxyee-down#675]
### 问题描述(必要)

有很多张照片在百度云里面，下载时需要打包下载，结果下载成功后在mac电脑上提示无法解压，在windows上电脑解压就缺几张，缺的几张是报错的

### 版本号(必要)

3.0

### 操作系统(必要)

Mac电脑
Parallels Desktop里面的windows 10虚拟机

### 相关截图

附件里面

### 相关日志

日志不知道咋提供
<img width="800" alt="xnip2018-09-09_20-41-51" src="https://user-images.githubusercontent.com/18020785/45264546-f97f3380-b470-11e8-8fe6-05f39d7c4ee1.png">
<img width="589" alt="xnip2018-09-09_20-42-33" src="https://user-images.githubusercontent.com/18020785/45264547-fa17ca00-b470-11e8-851c-1a307f32fab2.png">

**Comment by BlackHole1** [comment]
@monkeyWie

**Comment by shawneluis** [comment]
你这个跟下载器没关系的，是压缩包编码的问题，windows中文下估计是gb，mac一般都是utf8；你试试the unarchiver打开的时候选择能完整显示中文文件名的gb2313或者simpified Chinese (mac os).

**Comment by man2018** [comment]
# @shawneluis 我试了仍然提示文件损坏，是在mac上试的

**Comment by shawneluis** [comment]
@man2018 
<img width="519" alt="screenshot 2018-09-10 at 22 25 47" src="https://user-images.githubusercontent.com/42170260/45303747-18e98f80-b549-11e8-9ca7-13618f7f1ce6.png">
找不到测试文件，网上随便找的：）
我用的是这个，https://itunes.apple.com/cn/app/the-unarchiver/id425424353?l=en&mt=12

如果还不行的话那估计只能用百度自己的同步盘了！

**Comment by monkeyWie** [comment]
看看https://github.com/proxyee-down-org/proxyee-down-extension/tree/master/baiduYun#%E5%8E%8B%E7%BC%A9%E9%93%BE%E6%8E%A5%E4%B8%8B%E8%BD%BD

**Comment by man2018** [comment]
我解决了，谢谢各位。找到的解决方案就是“百度云会对超过100个文件的文件夹进行隐藏，要选定所有的文件才行”，也要用Unarchiver这个app来解压
