### ISSUE TITLE
百度云下载断断续续，而且速度上不去了

### ISSUE THREAD

**Issue by robin-zhigeng** [proxyee-down-org/proxyee-down#677]

**Comment by 1Eleven** [comment]
我也是

**Comment by BlackHole1** [comment]
哪个版本

**Comment by 1Eleven** [comment]
3.0

**Comment by aa1653239031** [comment]
2.53 无论怎么分段都只有2-3个分段有速度 速度几百k
3.02 速度在0到几百K间跳动 跟2.53一样慢
win10 x64

**Comment by monkeyWie** [comment]
是不是压缩链接下载的？

**Comment by aa1653239031** [comment]
批量推送，直链都不行，压缩链接报错超出大小..已升级百度云插件0.2

**Comment by monkeyWie** [comment]
速度慢的话可以把资源分享出去然后用隐私窗口下载(即不登录账号)

**Comment by monkeyWie** [comment]
具体机制不知道，反正不建议登录账号下载

**Comment by leon0420** [comment]
系统版本：Mac 10.13.6
软件版本：3.4 
问题描述：如果直接从自己云盘中点击下载，会下载失败；如果先分享，后下载，下载时速度会断断续续，大部分时间是没速度的。
![image](https://user-images.githubusercontent.com/19681201/48695778-052e6980-ec1b-11e8-86e7-2505d211876c.png)

**Comment by BlackHole1** [comment]
@1Eleven 正在下载的不要去动，去百度网盘链接里重新通过PD下载，后面软件会弹窗询问，此任务已经存在，是否刷新。这个时候点下刷新，就可以看到，又有速度了
