### ISSUE TITLE
3.02 Windows下载速度始终为0（附logs）

### ISSUE THREAD

**Issue by JamieShi** [proxyee-down-org/proxyee-down#683]
### 问题描述(必要)
任务开始后速度始终是0，状态是Unknown
### 版本号(必要)
3.02
### 操作系统(必要)
Windows 10
### 附件(log file)
[pdown-error.2018-09-10.log](https://github.com/proxyee-down-org/proxyee-down/files/2369143/pdown-error.2018-09-10.log)
### 相关截图
![capture](https://user-images.githubusercontent.com/22800023/45334933-040dfb80-b54b-11e8-92ca-18ee9d825b4e.PNG)

**Comment by monkeyWie** [comment]
尝试重新创建下载任务
