### ISSUE TITLE
teamview远程控制软件白屏

### ISSUE THREAD

**Issue by sweetasaki** [proxyee-down-org/proxyee-down#684]
上班时想控制家里的电脑下载东西，控制上去发现软件打开白屏，没法下载。

**Comment by sweetasaki** [comment]
暂时解决了问题，将Proxyee Down\main\pdown.cfg中的"uiMode"由1改为0，使用浏览器模式启动。

**Comment by monkeyWie** [comment]
这不是teamview的BUG吗 - -

**Comment by sweetasaki** [comment]
我用QQ的远程桌面也是白屏呀。
而且我百度一下，好像是因为软件开启了硬件加速的原因。基于这个原因，我于是改变了软件显示模式，就有了上面的解决方法。
> 这看起来像是teamview的BUG啊 - -
