### ISSUE TITLE
新建任务显示磁盘空间不足

### ISSUE THREAD

**Issue by ovack** [proxyee-down-org/proxyee-down#688]
### 问题描述(必要)
磁盘空间还有40G, 第一次下载了一个25G的文件, 下载完成后拷贝到移动硬盘, 然后删除这个25G的文件, 通过finder显示系统空间还有40G, 这时候新建另一个23G的任务提示磁盘空间不足.注销用户重新登陆后新建成功

### 版本号(必要)
3.0.2
### 操作系统(必要)
MACOS 10.14 Beta (18A384a)

**Comment by monkeyWie** [comment]
这个应该和系统有关吧，不像是软件的bug
