### ISSUE TITLE
获取下载链接失败，错误码：-6

### ISSUE THREAD

**Issue by wizdzz** [proxyee-down-org/proxyee-down#694]
### 问题描述(必要)
点击 pd下载 的任一个下载选项，提示“获取下载链接失败，错误码：-6”；
### 版本号(必要)
3.02
### 操作系统(必要)
win10
### 相关截图
![1](https://user-images.githubusercontent.com/38684262/45355903-43445700-b5f4-11e8-903e-65cb2bed61da.png)
![2](https://user-images.githubusercontent.com/38684262/45355904-43445700-b5f4-11e8-9212-7a5d27bbe9ec.png)
![3](https://user-images.githubusercontent.com/38684262/45355905-43dced80-b5f4-11e8-82fa-4817a594a288.png)
### 相关日志
日志为空

**Comment by trystudy** [comment]
如何插入截图的？

**Comment by monkeyWie** [comment]
扩展相关问题请到这里提：https://github.com/proxyee-down-org/proxyee-down-extension/issues
