### ISSUE TITLE
Mac 3.0.2版本客户端无法拦截到百度网盘下载

### ISSUE THREAD

**Issue by chengjiansunboy** [proxyee-down-org/proxyee-down#696]
### 问题描述(必要)
错误消息：响应状态码异常
### 版本号(必要)
Mac 3.0.2版本
### 相关日志
无

**Comment by monkeyWie** [comment]
具体原因见https://github.com/proxyee-down-org/proxyee-down-extension/tree/master/baiduYun#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97
