### ISSUE TITLE
版本3.02，创建任务失败，错误码400

### ISSUE THREAD

**Issue by Acurace** [proxyee-down-org/proxyee-down#699]
创建任务失败，错误码400
3.02
Win10 x64 17134.254

**Comment by ignatiusk** [comment]
创建任务失败，错误码400
3.02
debian 9 x64

**Comment by Bl66dG6at** [comment]
创建任务失败，错误码400 
3.02
win7 X64 PACK1

**Comment by ChloeDimen** [comment]
创建任务失败，错误码400
3.02 win7 X64

**Comment by ChloeDimen** [comment]
https://github.com/proxyee-down-org/proxyee-down-extension/tree/master/baiduYun 有解释原因（最后一行）

**Comment by monkeyWie** [comment]
实测2018年9月11号开始，百度云已经限制了压缩链接下载，当选择的文件总大小超过 300M 就不能下载了，建议使用批量推送来下载。
