### ISSUE TITLE
在下载文件需要下拉加载的时候会无法拦截到下载

### ISSUE THREAD

**Issue by Jsffyayoi** [proxyee-down-org/proxyee-down#700]
### 相关截图  
![orgr au8 r4dx3k exq](https://user-images.githubusercontent.com/33521701/45371327-e5783500-b61c-11e8-92e8-05504a841497.png)

![v yl89b h8v 42 9ue6ow](https://user-images.githubusercontent.com/33521701/45371384-080a4e00-b61d-11e8-9ce6-ef5684332eed.png)

![qq 20180911234747](https://user-images.githubusercontent.com/33521701/45371424-1fe1d200-b61d-11e8-95c4-ba878dfa413e.png)

### 相关日志  无

之后尝试将此文件保存在个人网盘后下载，结果是无限处于等待中页面。
![qq 20180912000416](https://user-images.githubusercontent.com/33521701/45372406-7d771e00-b61f-11e8-9798-773dcce9a139.png)

**Comment by monkeyWie** [comment]
扩展相关的issue请到https://github.com/proxyee-down-org/proxyee-down-extension/issues提，谢谢
