### ISSUE TITLE
选择文件夹下载时提示错误，单文件下载无问题

### ISSUE THREAD

**Issue by mercury1234** [proxyee-down-org/proxyee-down#702]
### 相关截图
<img width="716" alt="proxy 1" src="https://user-images.githubusercontent.com/43181924/45375671-478a6780-b628-11e8-85a1-fa605d789b9a.png">

**Comment by mercury1234** [comment]
![image](https://user-images.githubusercontent.com/43181924/45397265-cf489400-b671-11e8-93ac-6b3c956f68f6.png)

**Comment by monkeyWie** [comment]
下载最新的3.02安装百度云下载扩展并使用推送下载，具体原因见https://github.com/proxyee-down-org/proxyee-down-extension/tree/master/baiduYun#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97
