### ISSUE TITLE
下载速度也是很慢啊  十几二十kb

### ISSUE THREAD

**Issue by CaiXiaoBai** [proxyee-down-org/proxyee-down#704]

**Comment by note286** [comment]
@CaiXiaoBai [https://github.com/proxyee-down-org/proxyee-down-extension/tree/master/baiduYun](url) 

> 新建任务时调高分段数，若还是下载慢可以尝试将资源分享，然后退出帐号或者开启隐私窗口访问下载(避免帐号被限速)
