### ISSUE TITLE
批量推送下载失败

### ISSUE THREAD

**Issue by yongqingxie** [proxyee-down-org/proxyee-down#705]
### 问题描述(必要)
选中多个文件后,点击批量推送下载 无法启动下载

### 相关截图
![tim 20180912124312](https://user-images.githubusercontent.com/24885976/45402742-c9f74380-b689-11e8-93f3-f7a1d16f4ac4.jpg)

**Comment by monkeyWie** [comment]
扩展相关的issue到这里提：https://github.com/proxyee-down-org/proxyee-down-extension/issues
