### ISSUE TITLE
火狐浏览器百度云任务选中文件后点击PD下载提示 请选择要下载的文件

### ISSUE THREAD

**Issue by ohou524** [proxyee-down-org/proxyee-down#706]
### 问题描述(必要)
火狐浏览器中，百度云任务选中文件后点击PD下载提示会 请选择要下载的文件
### 版本号(必要)
proxyee-down 3.02
### 操作系统(必要)
Win10 64位 版本1803
### 相关截图
![1](https://user-images.githubusercontent.com/43197342/45405301-dd5bdc00-b694-11e8-9c6b-76de8e8ed059.JPG)

### 相关日志
日志为空

**Comment by CrazyCate** [comment]
我也遇到过，有时候重启一下软件或者浏览器可能会解决，有点随机性。

**Comment by monkeyWie** [comment]
扩展相关问题请到这里提：https://github.com/proxyee-down-org/proxyee-down-extension/issues
