### ISSUE TITLE
QQ群满了，怎么申请都不行

### ISSUE THREAD

**Issue by aohanhongzhi** [proxyee-down-org/proxyee-down#708]
### 相关截图
截图无法添加

### 相关日志
日志不会提取。

**Comment by monkeyWie** [comment]
linux上证书需要手动安装，代理也要手动设置
证书安装：https://github.com/proxyee-down-org/proxyee-down/blob/v2.5/.guide/common/ca/linux/read.md
代理切换：https://github.com/proxyee-down-org/proxyee-down/blob/v2.5/.guide/common/switchy/read.md
