### ISSUE TITLE
打开全局代理仍没有pd下载按钮

### ISSUE THREAD

**Issue by asteroit1lll** [proxyee-down-org/proxyee-down#709]
### 问题描述(必要)
chrome打开全局代理仍没有pd下载按钮
### 版本号(必要)
3.02
### 操作系统(必要)
window 7 chrome 69.0
### 相关截图
https://pan.baidu.com/s/1QJYtanO79oXd9HLkxabqiA（附件不知道怎么传上来）

**Comment by monkeyWie** [comment]
chrome是不是装了别的代理管理插件或者谷歌助手之类的
