### ISSUE TITLE
批量推送故障

### ISSUE THREAD

**Issue by CrazyCate** [proxyee-down-org/proxyee-down#711]
### 
![image](https://user-images.githubusercontent.com/35727786/45422249-3f7f0600-b6c2-11e8-9c61-73f80267ffd8.png)

### 相关日志
[pdown-error.2018-09-12.log](https://github.com/proxyee-down-org/proxyee-down/files/2374970/pdown-error.2018-09-12.log)

**Comment by monkeyWie** [comment]
扩展相关问题issue到这里提：https://github.com/proxyee-down-org/proxyee-down-extension/issues/
