### ISSUE TITLE
不显示扩展插件

### ISSUE THREAD

**Issue by sivicy** [proxyee-down-org/proxyee-down#712]
### 问题描述(必要)
安装证书后扩展管理页面不显示扩展插件
### 版本号(必要)
3.02
### 操作系统(必要)
win10 x64
### 相关截图
![snipaste_2018-09-13_01-30-54](https://user-images.githubusercontent.com/43216498/45442783-90f4b880-b6f5-11e8-8004-5e81baf0dc80.png)

**Comment by monkeyWie** [comment]
网络问题把，重新切换到扩展面板看看
