### ISSUE TITLE
建議新增功能與一點疑問

### ISSUE THREAD

**Issue by zhtw2013** [proxyee-down-org/proxyee-down#713]
### 3.02

1.希望能夠將程式右鍵選單加上「清除已完成任務」的選項

2.這裏的貼上跟複製沒有在地化，是不是無效功能呢？
![image](https://user-images.githubusercontent.com/9501406/45462111-02098f80-b739-11e8-8cf5-2ddd5ee26e6b.png)

**Comment by monkeyWie** [comment]
复制粘贴已经加上i18n
