### ISSUE TITLE
推送下载是不是最多只能推送一百条？

### ISSUE THREAD

**Issue by q359007027** [proxyee-down-org/proxyee-down#714]
### 相关截图  
<img width="360" alt="snipaste_2018-09-13_11-03-04" src="https://user-images.githubusercontent.com/10302584/45464957-85c97900-b745-11e8-8c0d-979bfe641171.png">
---------------------------------------
<img width="199" alt="snipaste_2018-09-13_11-11-11" src="https://user-images.githubusercontent.com/10302584/45465026-e789e300-b745-11e8-8a0f-bc39a130d297.png">

### 具体描述
**我有将近两千个文件需要下载，我在浏览器上把列表拉到最下面，把所有文件都选中了，点击推送下载，只得到了一百条推送，是不是最多只能推送一百条？**

**Comment by monkeyWie** [comment]
扩展相关问题请到这里提：https://github.com/proxyee-down-org/proxyee-down-extension/issues
