### ISSUE TITLE
直链下载创建任务失败

### ISSUE THREAD

**Issue by zxc5255105** [proxyee-down-org/proxyee-down#716]
在网盘下载单个文件时，采用直链下载，出现“创建任务失败，错误代码:400”

**Comment by 985154457** [comment]
我也是

**Comment by lahmy** [comment]
创建任务失败，错误码400
3.02
Win7 x32

我也是！！！

**Comment by lahmy** [comment]
已开启全局代理

**Comment by monkeyWie** [comment]
更新扩展，详见：https://github.com/proxyee-down-org/proxyee-down-extension/tree/master/baiduYun
