### ISSUE TITLE
3.02windows无法建立批量推送下载：错误码4007

### ISSUE THREAD

**Issue by runtutang** [proxyee-down-org/proxyee-down#717]
### 相关日志
问题如上，后来就变成了解析任务失败正在重试……虽然它一直就没有反应
以及为啥直链下载那么慢？

**Comment by monkeyWie** [comment]
![image](https://user-images.githubusercontent.com/13160176/45471439-a4d70380-b763-11e8-9175-349d854a9c45.png)
先把下载目录清空一遍

**Comment by cok3307788** [comment]
现在压缩包被限制的情况下，推送任务就成了批量下载的最好方式，所以能不能把批量推送和刷新任务相结合，推送时对旧有任务（已无速度的）自动进行刷新（甚至跳过确认步骤）？

**Comment by runtutang** [comment]
回各位，我用提取链接和创建任务刷新任务的方法解决了自己的需求，谢谢你萌

**Comment by monkeyWie** [comment]
@cok3307788 这里有https://github.com/proxyee-down-org/proxyee-down-extension/issues/10
