### ISSUE TITLE
直链下载创建任务失败，错误代码400

### ISSUE THREAD

**Issue by lahmy** [proxyee-down-org/proxyee-down#719]
问题描述(必要): 百度网盘文件下载时直链下载创建任务失败，显示错误代码：400。即使尝试批量下载也同样会失败。下载文件格式为MP4，大小为500MB，名称中不包含+号。

版本号(必要)：3.02 ； 扩展管理已开启全局代理，百度云下载版本为2.01。已安装全网嗅探，但是开关未开启。浏览器为360浏览器和搜狗浏览器。

操作系统(必要)：win7

**Comment by lahmy** [comment]
![qq 20180913161249](https://user-images.githubusercontent.com/42638817/45475770-df469d80-b76f-11e8-8d9d-6e9ce247c823.jpg)
![qq 20180913161238](https://user-images.githubusercontent.com/42638817/45475771-dfdf3400-b76f-11e8-91c9-1cb8f668cc89.jpg)

**Comment by lahmy** [comment]
![qq 20180913161341](https://user-images.githubusercontent.com/42638817/45476130-c094d680-b770-11e8-83d8-53d2ca748dd7.jpg)

**Comment by Nighting0518** [comment]
今天我也遇到了

**Comment by 985154457** [comment]
我也是这样啊，怎么办

**Comment by lahmy** [comment]
> 家里的老版本2.54可以正常运行 你们可以找一下

有时候2.54的版本也会出现没法获取下载链接的情况呢，最近2.54经常会报这个错。

已经好几天了

![qq 20180914085506](https://user-images.githubusercontent.com/42638817/45523439-e7e4b580-b7fb-11e8-857f-354f12b47714.jpg)

**Comment by lahmy** [comment]
{"error_code":31326,"error_msg":"user is not authorized, hitcode:122","error_info":"","request_id":5945973789894049572}

**Comment by weihaopeng** [comment]
同出现该情况，我是在2.5.4版本下载时发现突然开始间断（大概下载4%就会失败，然后继续下载又会进行4%～5%就又失败），然后安装了3.02，创建任务成功过两次，但是下载速度也很慢；后来也创建任务一直失败。操作系统macOS10.13.6，浏览器chrome 68.0.3440.106

**Comment by Tiandians** [comment]
这里3.02版本出现同样问题，系统win10 19H1 ，浏览器Chrome 70和FireFox 69

**Comment by YanHuiLi** [comment]
同样这个问题。

**Comment by monkeyWie** [comment]
把资源分享出去下载
