### ISSUE TITLE
3.02版本嗅探无效。

### ISSUE THREAD

**Issue by Rexlambert** [proxyee-down-org/proxyee-down#721]

**Comment by amostang** [comment]
我也是，试过所有拓展程序都关掉也不行，虽然关掉出现了pd下载，但pd下载也无法使用

**Comment by Rexlambert** [comment]
> 我也是，试过所有拓展程序都关掉也不行，虽然关掉出现了pd下载，但pd下载也无法使用

我是关掉或开启都不行，全局才可以，但是影响ssr。

**Comment by monkeyWie** [comment]
参考新版本扩展教程：https://github.com/proxyee-down-org/proxyee-down/wiki/安装扩展
