### ISSUE TITLE
3.02版本百度云没有PD下载按钮，已开启插件

### ISSUE THREAD

**Issue by tlerbao** [proxyee-down-org/proxyee-down#722]
### 问题描述(必要)
3.02版本百度云没有PD下载按钮
### 版本号(必要)
3.02
### 操作系统(必要)
Win10 专业版 and Chrome 69

**Comment by CRO2017** [comment]
建议用swichyomega代理

**Comment by tlerbao** [comment]
> 建议用swichyomega代理

嗯 安装了Chrome的SwichyOmega扩展，添加了情景有了 *PD下载* 按钮了。

新版界面比旧版要好看的多，干练的多，给个赞。

但新版需要配合代理扩展对于电脑小白来说不友好了。

**Comment by monkeyWie** [comment]
可以不用SwichyOmega扩展，但是要在扩展模块里开启全局代理。
