### ISSUE TITLE
希望继续支持Safari的下载

### ISSUE THREAD

**Issue by wongyeeboo** [proxyee-down-org/proxyee-down#729]
### 问题描述(必要)
    之前用Safari打开可以直接下载，现在不再出现PD下载按钮，Chrome安装swichyomega代理后才可正常使用
### 版本号(必要)
    2.54-3.02
### 操作系统(必要)
    Mac OS 10.13.6

**Comment by shawneluis** [comment]
mac必须开启全局代理才有按钮！

**Comment by wongyeeboo** [comment]
> mac必须开启全局代理才有按钮！
多谢多谢！
