### ISSUE TITLE
MAC停止下载后出现状态未知，不能继续下载的问题

### ISSUE THREAD

**Issue by hsy1992** [proxyee-down-org/proxyee-down#734]
### 相关日志 没有报错
![wechatimg1](https://user-images.githubusercontent.com/19618061/45541029-7c710700-b840-11e8-8045-126634d0e2d2.jpeg)

**Comment by hsy1992** [comment]
感觉不如之前好用了。。下载速度浮动太大

**Comment by LiWeiQiangAndroid** [comment]
还在不断改进的

**Comment by monkeyWie** [comment]
刷新下载链接，主页教程里有写

**Comment by LiWeiQiangAndroid** [comment]
刷新链接速度比较慢
