### ISSUE TITLE
安裝完證書無法獲得百度雲下載插件

### ISSUE THREAD

**Issue by ziyouzhe88** [proxyee-down-org/proxyee-down#736]
### 相关截图
![snap00016](https://user-images.githubusercontent.com/43246083/45548312-61d46900-b813-11e8-8b91-f2c744c12cb5.jpg)

**Comment by monkeyWie** [comment]
重启软件试试看

**Comment by ziyouzhe88** [comment]
> 重启软件试试看

重啟N遍所以和重啟無關，ui模式能調出插件，可是安裝長時間無響應，應該是不能識別繁體中文作業系統，望測試下

**Comment by monkeyWie** [comment]
可能是网络环境导致的，你试试访问下http://api.pdown.org/extension/search

**Comment by monkeyWie** [comment]
Haven't replied for a long time.
