### ISSUE TITLE
3.02版本百度云下载一直失败直链压缩批量都试过了全都失败win10

### ISSUE THREAD

**Issue by 007sky** [proxyee-down-org/proxyee-down#738]
### 相关截图
![qq 20180914234059](https://user-images.githubusercontent.com/43275553/45560471-c0cbc980-b877-11e8-9022-b0bc7c134bdd.png)
![qq 20180914234224](https://user-images.githubusercontent.com/43275553/45560499-dccf6b00-b877-11e8-9e28-5708bfa25bba.png)

**Comment by monkeyWie** [comment]
分享出去再下载
