### ISSUE TITLE
百度网盘首页不出现pd下载按钮

### ISSUE THREAD

**Issue by Nwj-9** [proxyee-down-org/proxyee-down#740]
### 
![default](https://user-images.githubusercontent.com/16277839/45580471-e979b080-b8c3-11e8-89e2-d1b53e093281.PNG)

**Comment by zhaosguo** [comment]
我也是这样

**Comment by SakumyZ** [comment]
我也是这样的问题，原来一直在用老版本，今天突然发现老版本用不了了，然后转3.02，结果没有出现下载按钮，不知道为什么Chrome浏览器

**Comment by monkeyWie** [comment]
扩展模块安装百度云下载扩展，并开启全局代理即可
