### ISSUE TITLE
將windows改成UI模式後無法再改回來

### ISSUE THREAD

**Issue by ziyouzhe88** [proxyee-down-org/proxyee-down#747]
### 相关截图
![snap00018](https://user-images.githubusercontent.com/43246083/45587937-658fea80-b8fc-11e8-9a9f-276a66475643.jpg)
![snap00017](https://user-images.githubusercontent.com/43246083/45587938-658fea80-b8fc-11e8-9950-3f0a9fb7226c.jpg)

**Comment by monkeyWie** [comment]
浏览器模式下不支持IE9以下的浏览器
