### ISSUE TITLE
无法刷新下载链接（已存在于列表中的任务无法再次解析）

### ISSUE THREAD

**Issue by Tiandians** [proxyee-down-org/proxyee-down#749]
**问题描述**：
已经存在于下载列表中的任务，在百度云中再次使用直链/批量推送下载时均出现错误，即无法刷新下载链接

**版本号**：
3.02

**操作系统**：
Windows10 Skip跳跃预览通道 18237.1000

**相关截图**：
列表：
![a](https://user-images.githubusercontent.com/35755846/45592296-ba367280-b99b-11e8-8f27-922e82a0fe34.png)
直链：
![aaa](https://user-images.githubusercontent.com/35755846/45592308-071a4900-b99c-11e8-8699-12549f7688a4.png)
批量：
![aa](https://user-images.githubusercontent.com/35755846/45592311-0e415700-b99c-11e8-8973-6c785216a035.png)

**相关日志**：
[pdown-error.2018-09-16.log](https://github.com/proxyee-down-org/proxyee-down/files/2386253/pdown-error.2018-09-16.log)

**说明**：
Proxy SwitchyOmega PAC/自动转换/全局模式均出现此问题
百度云下载插件已开启，证书已安装，软件以管理员权限启动

**Comment by monkeyWie** [comment]
看log是任务解析超时了，最好是先暂停掉所有的下载任务，不然可能影响
