### ISSUE TITLE
# 望改进！

### ISSUE THREAD

**Issue by jiangxiaoshaui** [proxyee-down-org/proxyee-down#751]
不能与ssr同时使用，需要切换代理有点麻烦，希望可以改进

**Comment by monkeyWie** [comment]
这两个必然有冲突的，因为都是使用代理的方式

**Comment by AnyWAT** [comment]
不知是否可行。。。先有
情景模式：Proxyee Down（HTTP:9999）及SSR（SOCKS5:1080）
再建“自动切换模式”：规则列表规则走SSR，默认情景模式走Proxyee Down（😂还是二者互换？）

**Comment by monkeyWie** [comment]
@AnyWAT 这样是可以，但是配置起来麻烦，还不如每次下载前切换下模式，毕竟下载不常有

**Comment by AnyWAT** [comment]
但 https://github.com/proxyee-down-org/proxyee-down/issues/805#issuecomment-424605817 pac?t= 后面的数字时变时新，顷刻即失常，😂 还是上述自建“自动切换模式”来得简单点？
