### ISSUE TITLE
访问百度网盘报不是私密链接

### ISSUE THREAD

**Issue by greedyhao** [proxyee-down-org/proxyee-down#753]
### 问题描述(必要)
使用SwitchyOmega切换到proxyee的PAC后，访问百度网盘报不是私密链接
```
NET::ERR_CERT_AUTHORITY_INVALID
Subject: pan.baidu.com
Issuer: ProxyeeDown CA
Expires on: 2028年9月13日
Current date: 2018年9月16日
```
### 版本号(必要)
3.02
### 操作系统(必要)
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

### 相关截图
![deepinscreenshot_google-chrome_20180916112214](https://user-images.githubusercontent.com/25771942/45592560-ae4eae80-b9a3-11e8-84d7-3c572a66e87c.png)

### 相关日志
log文件为空

**Comment by monkeyWie** [comment]
火狐浏览器需要手动安装证书：https://github.com/proxyee-down-org/proxyee-down/blob/v2.5/.guide/common/ca/firefox/read.md

**Comment by greedyhao** [comment]
@monkeyWie 可是我使用的是chrome，应该怎么装证书

**Comment by monkeyWie** [comment]
emm，没看到是Ubuntu，linux系统证书和代理都要手动设置的。
