### ISSUE TITLE
Proxyee Down BUG

### ISSUE THREAD

**Issue by G62510** [proxyee-down-org/proxyee-down#755]
### 问题描述(必要)
1、大批量创建下载任务后，手动暂停后再继续下载就没了速度，等很长时间依然如此；2、创建好任务后，反复几次关闭掉此软件再打开后，创建的任务就消失了，需要重新创建个新任务再切换选项卡才会显示出之前的所有任务；3、大批量创建好任务后，批量暂停、续传时，有的任务会显示等待下载，有的依然显示暂停状态，单独选择这几个暂停状态的任务继续下载依然是显示暂停。4、创建单文件下载后下载速度会跳速，一下速度是0，紧接着就有速度了，然后接着是0，接着又有速度。5、有点类似3的问题，有时暂停任务再继续下载后会显示没速度，切换一下选项卡后才会显示速度，有时不管怎么切换，退出重新启动该软件依然没速度。这个版本没以前的旧版本好用了，虽然旧版本也有问题。
### 相关日志

**Comment by JSYCX** [comment]
1、下载速度同样是会跳
2、百度网盘文件无法满载下载，最大下载速度700KB/S，可能存在百度单方面限速
3、2.54版本许多很好的功能在3.02版本上没有实现，比较可惜
4、对作者表示感谢。
版本3.02
操作系统win10 1803
