### ISSUE TITLE
Proxyee Down 建议

### ISSUE THREAD

**Issue by G62510** [proxyee-down-org/proxyee-down#756]
### 问题描述(必要)
建议：
1、Proxyee Down3.02版本使用“批量推送下载“时，创建好任务之前能弹出个选择自定义路径保存，现在一点这个批量推送下载就直接把任务创建好了，用的还是软件设置里默认的路径，批量下载时文件下载量大，文件也杂乱，全都在一个文件夹里，下载完再挨个去区分也费劲，若是中途有事离开或是挂机睡觉，等来了再看，一大堆文件，都分不出来。
2、创建好下载任务后，文件还没下完时，下载列表的操作一栏愣是没有打开文件所在位置的选项。下载多个文件时，单个创建的文件都在不同的文件夹里，创建的多了等想看下载的某个文件是哪个文件夹里的文件时，想看都看不成，还得费劲去找。

**Comment by monkeyWie** [comment]
第一点觉得没有必要，第二点已经实现了
