### ISSUE TITLE
mac 一直提醒26339端口被占用，查询并没有占用

### ISSUE THREAD

**Issue by tanrich** [proxyee-down-org/proxyee-down#757]
### 版本号(必要)
3.0.2
### 操作系统(必要)
mac 10.13.6

**Comment by pecdew** [comment]
me too

**Comment by monkeyWie** [comment]
没有重现这个bug，不要重复启动软件或者关掉别的占用此端口的软件

**Comment by tanrich** [comment]
查看了的，没有任何占用26339端口的应用。即使有我也 kill 了。3.0 3.0.2都是这样。我继续用2.54

**Comment by tanrich** [comment]
查看了的，没有任何占用26339端口的应用。即使有我也 kill 了。3.0 3.0.2都是这样。我继续用2.54

**Comment by tanrich** [comment]
现在2.54是不是被限速了？保守只有1m左右，原来都可以达到峰值。

**Comment by monkeyWie** [comment]
分享出去，隐私窗口下载
