### ISSUE TITLE
3.02版本无法设置前置代理了么？

### ISSUE THREAD

**Issue by Smith-Wang** [proxyee-down-org/proxyee-down#758]
### 问题描述(必要)
因为是公司内网，必须要设置代理才能访问外网，没有代理无法访问啊
### 版本号(必要)
3.02
### 操作系统(必要)
windows 10 64bit
### 相关截图
![default](https://user-images.githubusercontent.com/24584213/45595904-f2fb3980-b9e5-11e8-8ea6-95389f8f008b.png)
### 相关日志
无

**Comment by monkeyWie** [comment]
暂时还不支持，等新版本把

**Comment by monkeyWie** [comment]
3.03已支持
