### ISSUE TITLE
选择保存路径就卡死了

### ISSUE THREAD

**Issue by Ecolinnn** [proxyee-down-org/proxyee-down#759]
### 问题描述(必要)
选择保存路径就卡死了
2.54倒是没有问题
设置兼容xp模式可以用，但是运行速度就比较慢了
也不能在xp模式设置好再回到正常模式，因为配置会被清除
有没有别的方法修改保存路径？

### 版本号(必要)
3.0&3.02
### 操作系统(必要)
win7
### 相关截图
![qq 20180917104331](https://user-images.githubusercontent.com/43328172/45604407-a441b400-ba66-11e8-9aaf-d7a9f3ec270f.png)

### 相关日志
log是空的

**Comment by Ecolinnn** [comment]
补充一下，只要是设置兼容成win7（以及server2008）之外的就好了，什么vista也行

**Comment by monkeyWie** [comment]
@Ecolinnn  能加下我qq(263397478)远程调试下吗，因为我这没法重现这个问题

**Comment by hersdexim** [comment]
> @Ecolinnn 能加下我qq(263397478)远程调试下吗，因为我这没法重现这个问题

我的也是这样，版本3.4，系统win10，请问一下如何解决~

![image](https://user-images.githubusercontent.com/45645583/49556731-1926da80-f940-11e8-9ede-397419bdecdd.png)

**Comment by monkeyWie** [comment]
这个看样子是java的bug啊，只能用点麻烦的办法解决了。
参考下：#792
