### ISSUE TITLE
批量推送下载显示解析失败

### ISSUE THREAD

**Issue by RangerDzy** [proxyee-down-org/proxyee-down#761]
### 相关截图
![image](https://user-images.githubusercontent.com/43333228/45609801-03fe8600-ba8c-11e8-8828-50dc2cdc9d3d.png)

**Comment by yang201003** [comment]
> ### 问题描述(必要)使用批量推送下载功能，自第二个文件开始一直显示“解析任务失败，重试中”
> ### 版本号(必要)3.02
> ### 操作系统(必要)win10专业版
> ### 相关截图
> ![image](https://user-images.githubusercontent.com/43333228/45609801-03fe8600-ba8c-11e8-8828-50dc2cdc9d3d.png)
> 
> ### 相关日志

同样的问题。在批量推送566个文件中崩溃后，再也不能用了。

**Comment by monkeyWie** [comment]
按F12把network里的内容截图看看
