### ISSUE TITLE
3.02版本Mac出错

### ISSUE THREAD

**Issue by z793242777** [proxyee-down-org/proxyee-down#763]
<img width="1025" alt="2018-09-17 19 28 02" src="https://user-images.githubusercontent.com/23627514/45620597-0672d700-bab0-11e8-8721-5bfef71418f3.png">
一打开就会出现这个，无法使用，怎么解决？

**Comment by z793242777** [comment]
每次打开都会让我输一遍密码

**Comment by monkeyWie** [comment]
什么版本？

**Comment by z793242777** [comment]
3.02，最新的那个

**Comment by monkeyWie** [comment]
下载最新的版本看看
