### ISSUE TITLE
可否增加对URL Scheme的支持

### ISSUE THREAD

**Issue by Iranninn** [proxyee-down-org/proxyee-down#765]
现有的插件功能要求相应流量走http代理才能工作，使用时频繁切换代理还是蛮烦的……
如果增加对URL Scheme的支持的话，可以做到需要时再调起pd，开发浏览器拓展也会更加便利些

**Comment by monkeyWie** [comment]
这个做不到哦，代理的话不用频繁切换啊用pac就好
