### ISSUE TITLE
3.02百度云无法嗅探，而火狐浏览器使用Switchy插件无法设置PAC模式

### ISSUE THREAD

**Issue by EsperanzaChi** [proxyee-down-org/proxyee-down#777]
### 问题描述(必要)
2.54版本无法下载超300M的文件，因此升级为3.02版。3.02版安装后百度云无法嗅探，百度云并不显示Proxyee-down标志，使用百度云直链下载插件获取链接添加无效。另2.54版用直链添加任务显示未知文件，无法下载。同样，用IDM下载直链也会出现"错误请求“，无法下载。
### 版本号(必要)
3.02&2.54
### 操作系统(必要)
Windows10 1803

**Comment by EsperanzaChi** [comment]
![default](https://user-images.githubusercontent.com/37699470/45737336-127da680-bc20-11e8-831e-7c15ae977701.png)
不知是不是火狐版本不同的问题，用SwitchyOmege插件会显示无法使用PAC模式。
![default](https://user-images.githubusercontent.com/37699470/45737451-6c7e6c00-bc20-11e8-8192-86deff7ede12.png)
SwitchyOmega亦为测试版……如图

**Comment by MATOxu** [comment]
我是这样的。选第一个情景类型“代理服务器”，取个名字。然后设置成这样：
![01](https://user-images.githubusercontent.com/43372657/45737761-473e2d80-bc21-11e8-8960-09afc3d1a8cc.png)
然后云盘登录之后，选刚刚新建的模式，就出现这个PD下载了，你试试。
![default](https://user-images.githubusercontent.com/43372657/45737918-a734d400-bc21-11e8-845d-d2975fafde22.png)

**Comment by monkeyWie** [comment]
如果之前没用SwitchyOmega插件来设置别的代理的话建议不要安装SwitchyOmega，在下载器的扩展模块里把全局代理勾选就好了

**Comment by 71e6fd52** [comment]
@monkeyWie 那有用别的代理的呢？
