### ISSUE TITLE
下载慢

### ISSUE THREAD

**Issue by MATOxu** [proxyee-down-org/proxyee-down#778]
### 问题描述(必要)
下百度云的文件，一会儿有速度几百k，一会儿又是0kb。就不断这样变化，很不稳定，并且速度也不快。
### 版本号(必要)
3.02
### 操作系统(必要)
win10

**Comment by Ikcarus** [comment]
我也是同样的问题，上面还显示解析任务失败，重试中
看下载速度波动很大

**Comment by Cui-y** [comment]
解析失败， 速度跳动频率很高， mac端的

**Comment by Tiandians** [comment]
这里也有同样问题

**Comment by MATOxu** [comment]
刚刚试了新版，3.03。一样速度不稳定，波动很大。

**Comment by monkeyWie** [comment]
看这里：https://community.pdown.org/topic/52/%E5%85%B3%E4%BA%8E%E7%99%BE%E5%BA%A6%E4%BA%91%E4%B8%8B%E8%BD%BD%E9%80%9F%E5%BA%A6%E8%BF%87%E6%85%A2%E7%9A%84%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98
