### ISSUE TITLE
CPU占用率过高

### ISSUE THREAD

**Issue by swang93** [proxyee-down-org/proxyee-down#779]
### 问题描述(必要)
单任务CPU占用超过33%, 大于3个任务同时下载会卡死 (32连接数)，同时CPU能飙到100%,  试验过IDM 同时10任务 (32连接数) 没问题
### 版本号(必要)
3.02
### 操作系统(必要)
windowns 10 x64  cpu: i5 6200u 
### 相关截图
![wechat image_20180919010241](https://user-images.githubusercontent.com/42833304/45734353-eb848d80-bba9-11e8-833b-214756c8b0ce.png)
![wechat screenshot_20180919011526](https://user-images.githubusercontent.com/42833304/45734355-ecb5ba80-bba9-11e8-9fcc-9b3faffba89a.png)

**Comment by swang93** [comment]
![wechat image_20180919010241](https://user-images.githubusercontent.com/42833304/45734185-2f2ac780-bba9-11e8-8ae0-0e693ba76ccb.png)
![wechat screenshot_20180919011526](https://user-images.githubusercontent.com/42833304/45734258-8b8de700-bba9-11e8-88b4-caf0f21ff70a.png)

**Comment by monkeyWie** [comment]
升级到3.1版本
