### ISSUE TITLE
硬盘占用过高

### ISSUE THREAD

**Issue by 12697459** [proxyee-down-org/proxyee-down#780]
### 问题描述(必要)
下载时硬盘占用过高
### 版本号(必要)
3.02
### 操作系统(必要)
win10 1803
### 相关截图
![default](https://user-images.githubusercontent.com/21971550/45744014-013c9600-bc30-11e8-990d-a549722deae3.JPG)

**Comment by Lan-megumi** [comment]
老铁你应该把进程发出来看看
