### ISSUE TITLE
无法下载扩展

### ISSUE THREAD

**Issue by 71e6fd52** [proxyee-down-org/proxyee-down#782]
### 问题描述(必要)
在扩展中点击下载按钮没有反应
### 版本号(必要)
3.03
### 操作系统(必要)
Arch Linux
### 相关日志
没有报错

**Comment by monkeyWie** [comment]
更新新版本试试

**Comment by 71e6fd52** [comment]
更新了 3.12 还是一样

**Comment by monkeyWie** [comment]
估计和你网络有关系，你访问下这个url看看：http://api.pdown.org/recommend/soft

**Comment by 71e6fd52** [comment]
这个可以
btw，扩展信息是有的，但是下载按钮点不了

**Comment by 71e6fd52** [comment]
应该不是网络问题，挂代理也没有用

**Comment by 71e6fd52** [comment]
默认生成的 `pdown.cfg` 中 `extFileServers` 为 `null`
