### ISSUE TITLE
在网盘根目录下创建任务总是出现错误码400以及解析任务失败

### ISSUE THREAD

**Issue by arcbishopw** [proxyee-down-org/proxyee-down#788]
### 问题描述(必要)
在自己的网盘根目录下的文件，下载时出现错误码400，选择批量下载则出现解析任务失败
### 版本号(必要)
3.03
### 操作系统(必要)
Windows10 64位
### 相关截图
[https://imgchr.com/i/imuJ1O](url)

**Comment by monkeyWie** [comment]
更新软件版本和扩展版本
