### ISSUE TITLE
3.03的WIN32的不能运行了

### ISSUE THREAD

**Issue by bestive** [proxyee-down-org/proxyee-down#794]
感谢提供这么好的软件 .
我用它有一个月了,很好用.
我的是XP,更新之后3.03启动后,不弹出主界面,点托盘菜单无任何反应.
能否解决,谢谢.

**Comment by monkeyWie** [comment]
@bestive 你之前什么版本能在xp上运行？

**Comment by JYeung111** [comment]
我之前是 2.54 版能在 XP(x86) 暢順運作，只是起動時稍耗時！
在 3.0 版之後就不能運作，初時還可以看到web UI 頁面，但不能進行部份設置，儲存及添加任務等等；
但至最新3.0.3 版 ，就起動也不能，jar 起動後就自己停止工作，不見web UI 打開，見到它留在工作，可右鍵開 popup menu，但其所有選項均無效

![pyee](https://user-images.githubusercontent.com/41117798/45925630-d4e48a80-bf4b-11e8-88cd-d7176854710c.PNG)

**Comment by monkeyWie** [comment]
以后测试下xp的兼容性

**Comment by JYeung111** [comment]
現附上 message log 希望能助查找問題
[debug.log](https://github.com/proxyee-down-org/proxyee-down/files/2433086/debug.log)

**Comment by bestive** [comment]
@monkeyWie 以前的是2.54,很好用,现在完了.

**Comment by bestive** [comment]
@monkeyWie  @JYeung111  
咱们XP族的应该到问题区刷下存在感,不然被忽视了.

我只用XP上网,以其它任何版本都快,不想用高版本的.

**Comment by monkeyWie** [comment]
3.31版本已经兼容xp了

**Comment by JYeung111** [comment]
萬分感謝，我又可進行升級了！
