### ISSUE TITLE
3.03 win10 x64 批量下载任务推送速度太慢

### ISSUE THREAD

**Issue by calculusfan** [proxyee-down-org/proxyee-down#795]
你好，

3.03版本在win10 x64下运行时，在chrome上使用SwitchyOmega批量下载时，任务推送速度太慢，以至于已推送的任务下载完毕后还没有等到新的推送，外网上下行通常不低于10MB/s，峰值50MB/S。鉴于我并不了解软件的工作原理，且运行时CPU、内存和硬盘有明显占用，故附上电脑配置：
CPU：i7 4th
RAM：16GB
储存方式：SSD(软件所在盘)+HDD(下载文件夹)

希望问题可以得到回复和解决，谢谢~

**Comment by calculusfan** [comment]
另外我需要在网盘上大批量下载大文件，文件大小在500MB-2GB之间，这样的文件总共需要下载上千接近一万个，而我发现，如果一次性较大批量下载（100-200）会导致：1.第20个文件左右任务推送开始龟速 2.后续文件出现推送失败的概率大大提高 3.任务推送卡死 4.如果超过200个文件，将会导致浏览器提示页面无响应
所以我希望可以可视化推送状态，增加手动暂停、开始、重连的功能，最好可以提高任务推送的效率

**Comment by CRO2017** [comment]
建议每次推送少一点，本来一口气推送任务量就比较大，要是堆积了，记得清除队列，否则容易出现bug

**Comment by calculusfan** [comment]
> 建议每次推送少一点，本来一口气推送任务量就比较大，要是堆积了，记得清除队列，否则容易出现bug

然而问题是现在单次批量推送稳定数量是10左右，也就是超了10之后就有大概率推送变得巨慢，且容易出错。相比于成千上万的大文件，不仅要记下上次的截止位置，更难人为操作的是过一段时间后就需要重新刷新页面。

有没有可能增加一种方案，让我在软件上预订下我需要下载的项目，软件每次自动在清单里推送10个下载？这样既不增加单次推送的任务量，又减轻了人为机械操作的负担。

上述方案的一种可能实现是在脚本中“批量下载”下方多增加一个预约选项，虽然读取勾选信息并记录，但不对所有勾选内容立刻执行下载。个人意见，仅供参考。

另外，可否在软件窗口里增加一个“已完成”选项口？这样正在下载的就不会被已下载的挡住。（毕竟上千个已完成任务堆在前面，滚轮还得滚一阵才能到最下方的未完成任务）以及增加一个总速度的显示区域

**Comment by monkeyWie** [comment]
因为在推送的过程中下载占用了很大的网速，导致推送那边任务解析失败，最好是先全局限速一下，推送完再把限速关掉
