### ISSUE TITLE
3.03 win10 x64 下载一半 状态显示未知

### ISSUE THREAD

**Issue by LaughAtTheWolf** [proxyee-down-org/proxyee-down#797]

**Comment by iyangqiong** [comment]
加一

**Comment by cobob** [comment]
![default](https://user-images.githubusercontent.com/11517019/45911484-85686680-be46-11e8-9744-d5356ca3e93e.JPG)

**Comment by siyiye** [comment]
版本号(必要)3.03
操作系统(必要)win sev 2008R2

同楼主一样，下载过程中，突然进度未知，然后无任何流量了。

怎么回事？

**Comment by ibearye** [comment]
+1

**Comment by jasonxxp** [comment]
因为这个问题特意升级到最新版，还是无解决。然后过来看issue了

**Comment by dd011** [comment]
遇到同样问题，下载跳一下速度200，300k后就归0了，然后状态未知。没法满速下载了。

**Comment by monkeyWie** [comment]
下不动的可以尝试刷新下载链接：https://github.com/proxyee-down-org/proxyee-down/wiki/%E5%88%B7%E6%96%B0%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5
下载速度慢的看这里：https://community.pdown.org/topic/52/%E5%85%B3%E4%BA%8E%E7%99%BE%E5%BA%A6%E4%BA%91%E4%B8%8B%E8%BD%BD%E9%80%9F%E5%BA%A6%E8%BF%87%E6%85%A2%E7%9A%84%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98
