### ISSUE TITLE
在deepin中编译报错

### ISSUE THREAD

**Issue by YUOL-CCY** [proxyee-down-org/proxyee-down#799]
编译后报错。无法在模块路径中找到主题引擎：“adwaita”

**Comment by monkeyWie** [comment]
有详细日志吗

**Comment by YUOL-CCY** [comment]
![Uploading.png…]()

**Comment by YUOL-CCY** [comment]
![pic](https://user-images.githubusercontent.com/26436652/45929381-5acff800-bf83-11e8-9e32-614a5b7b43e1.png)

**Comment by monkeyWie** [comment]
看起来没什么问题啊，界面没出来吗

**Comment by YUOL-CCY** [comment]
不是,界面出来了,但是是乱码.

**Comment by monkeyWie** [comment]
你试试指定编码运行
```
java -jar proxyee-down-core.jar -Dfile.encoding=GBK
```

**Comment by SsorryQaQ** [comment]
> 你试试指定编码运行
> 
> ```
> java -jar proxyee-down-main.jar -Dfile.encoding=GBK
> ```

还是会乱码...O(∩_∩)O

**Comment by monkeyWie** [comment]
可能是缺少某种字体。。 用浏览器模式看看
