### ISSUE TITLE
最新版本3.03没有刷新下载任务功能

### ISSUE THREAD

**Issue by jianboy** [proxyee-down-org/proxyee-down#802]
### 问题描述(必要)
如图，添加多个任务，发现总有部分任务无法下载！而最新版本的pd没有刷新链接的功能。所以一直不能下载!

### 版本号(必要)
v3.03

### 操作系统(必要)
win10

### 相关截图
![baiduhi_2018-9-22_19-16-6](https://user-images.githubusercontent.com/11532015/45916662-5aa8fd00-be9c-11e8-870f-526fdfd62afb.png)

**Comment by AnyWAT** [comment]
https://github.com/proxyee-down-org/proxyee-down [刷新任务下载链接](https://github.com/proxyee-down-org/proxyee-down/blob/v2.5/.guide/common/refresh/read.md)

**Comment by jianboy** [comment]
老版本可以，新版本就不行了。。。

3.03版本，由于文件超过300M，采用下载多个文件方法，总有很多无法下载。然后也没法刷新任务！上面链接老版本试过可用。我说的是3.03版本。

**Comment by AnyWAT** [comment]
https://github.com/proxyee-down-org/proxyee-down/issues/786#issuecomment-423507884

**Comment by AnyWAT** [comment]
🤣根据楼上的说法，如下操作是否可行？
1、2.54 与 3.03 各自解压到不同路径，但下载文件保存在同一位置
2、运行 3.03 批量下载，适时停止该版本
3、运行 2.54 刷新链接继续接着下载

**Comment by Lan-megumi** [comment]
太久没看issue了，对我所说的 不支持大于 x GB文件下载做出修改：

根据其他人的说法，3.03的出现是因为度盘对文件做出了限制，然后3.03使用类似“分段”之类的下载方式来下载超出限制的文件（这个限制有人说300，但是我这2.54版本800M的3GB的能下同时900M又下不了）

**Comment by monkeyWie** [comment]
3.0版本支持刷新下载链接啊，和之前的操作一样的

**Comment by librix** [comment]
推送任务不支持刷新下载链接，直链下载支持。但是从很多文件中，去单个寻找哪一个文件再刷新，很麻烦。特别是失效文件比较多的时候。

建议为推送任务失效刷新直链添加操作方法和说明。

**Comment by monkeyWie** [comment]
3.11版本开始，推送下载支持自动刷新下载链接了，具体查看：https://github.com/proxyee-down-org/proxyee-down/releases/tag/3.1
