### ISSUE TITLE
3.03版本的下载按钮是否出现是随机性的

### ISSUE THREAD

**Issue by ykqmain** [proxyee-down-org/proxyee-down#803]
### 相关日志

下载按钮随机出现，Safari和Chrome都是这样，重启软件，开关插件都无效。

不能批量下载，总是出现400错误。

下载时经常速度在500k和0k之间跳动。

**Comment by monkeyWie** [comment]
并没有随机性，下载速度慢的看这里:https://community.pdown.org/topic/52/%E5%85%B3%E4%BA%8E%E7%99%BE%E5%BA%A6%E4%BA%91%E4%B8%8B%E8%BD%BD%E9%80%9F%E5%BA%A6%E8%BF%87%E6%85%A2%E7%9A%84%E8%A7%A3%E5%86%B3%E9%97%AE%E9%A2%98
