### ISSUE TITLE
响应状态码异常

### ISSUE THREAD

**Issue by haoqichangshu** [proxyee-down-org/proxyee-down#806]
### 相关截图
<img width="1280" alt="2018-09-22 23 26 38" src="https://user-images.githubusercontent.com/37166110/45918828-1b3fd800-bebf-11e8-92f6-e886f556c90d.png">

### 相关日志
[pdown-error.2018-09-22.log](https://github.com/proxyee-down-org/proxyee-down/files/2407913/pdown-error.2018-09-22.log)

**Comment by monkeyWie** [comment]
继续用pd下载的直链下载去创建任务，就可以刷新链接了

**Comment by AnyWAT** [comment]
首次使用贵软件成功下载第一个文件的经历，貌似只有 pd 下载的“直链下载”才成功（第一次点击好像启动了电脑上的“百度网盘”程序），是否可认为下载单个文件必须用此选项，即 pd 下载的“直链下载”改称“单个文件下载”更合适？

**Comment by Sakuradreancat** [comment]
> 继续用pd下载的直链下载去创建任务，就可以刷新链接了

抱歉我不是很懂，我遇到了同样的问题，我需要做什么？
