### ISSUE TITLE
批量推送下载解析任务失败

### ISSUE THREAD

**Issue by Lan-megumi** [proxyee-down-org/proxyee-down#807]
### 问题描述(必要)
RT，在使用批量推送下载时到某一个文件出现“解析任务失败，重试中：“文件名” ”的错误
重试挂着老半天也没什么反应，
目前自己解决方法是F5刷新网页，然后重新单个点击出问题的文件
然后单个点击有时候还要看脸=。=
建议添加监测直接跳过解析失败的任务？

### 版本号(必要)
3.03
### 操作系统(必要)
windows10 专业版 1703
谷歌浏览器Chorme  69.0.3497.100（正式版）
无浏览器插件

**Comment by Lan-megumi** [comment]
另外
一个一个下载貌似也出了问题
因为账号被小黑屋所以我是共享出来下载的
一个一个点直链基本上点到第二个就有大概率出现没弹出窗口，小概率网页没反应，过会弹出崩溃的提示
然后第一个下载完之后再去点击第二个又能弹出窗口了

**Comment by Lan-megumi** [comment]
自己找到问题了
下载速度太快有时候是没反应，什么直链啊...解析啊这些
在我自己调整了全局下载速度为带宽的一半的时候就都可以了

**Comment by monkeyWie** [comment]
关于推送的问题看这里：https://community.pdown.org/topic/42/%E8%AF%B7%E9%97%AEpd%E7%82%B9%E5%87%BB%E6%89%B9%E9%87%8F%E6%8E%A8%E9%80%81%E4%B8%8B%E8%BD%BD%E5%87%BA%E7%8E%B0%E4%BB%BB%E5%8A%A1%E5%A4%B1%E8%B4%A5%E6%80%8E%E4%B9%88%E5%8A%9E/7
