### ISSUE TITLE
部署在服务器上，做离线下载

### ISSUE THREAD

**Issue by yanweian** [proxyee-down-org/proxyee-down#816]
### 问题描述(必要)
可以将此软件直接部署在服务器上，然后本地机器通过访问相应web端口进行使用么？
如果这样的话，有什么需要注意的，比如需要对源码中的ip进行修改么，百度网盘的插件可以直接用么？
### 版本号(必要)
latest
### 操作系统(必要)
本机：macos  服务器：docker-centos7

**Comment by yanweian** [comment]
Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY

......服务器没有屏幕还启动不起来

可不可以不要Gui界面，只要一个web界面呢。。。。

**Comment by monkeyWie** [comment]
你可以考虑下[pdown-res](https://github.com/proxyee-down-org/pdown-rest)

**Comment by yanweian** [comment]
@monkeyWie 好的，谢谢

**Comment by yanweian** [comment]
@monkeyWie pdown-rest 的确可以，可是如何加载插件呢（主要是baiduyun插件）？参考pdown.js编一个油猴脚本可行么？

**Comment by monkeyWie** [comment]
可以，不过脚本得自己写了，或者提取直链的配合curl或者postman这种http客户端工具推送任务

**Comment by yanweian** [comment]
@monkeyWie 好的
