### ISSUE TITLE
已经开启软件，访问百度云下载页面，下载按钮链接不显示，防火墙已经关闭

### ISSUE THREAD

**Issue by heroliyaoa** [proxyee-down-org/proxyee-down#819]
问题描述：

已经开启软件，访问百度云下载页面，下载按钮链接不显示，防火墙已经关闭

版本：3.0.3

**Comment by AnyWAT** [comment]
摆脱网盘客户端-关于Proxyee-down 的配置教程-奇乐博客 - https://www.citlake.com/?p=140 新建情景模式，并创建，创建情景模式完成后会弹出情景模式的设置：协议选择 HTTP、服务器地址 127.0.0.1、服务器端口号 9999 并切换到该情景模式，刷新网盘文件网页，上面终于出现了“proxyee-down”。。。
或 https://github.com/proxyee-down-org/proxyee-down 扩展商店——扩展安装——并切换到该情景模式。。。

**Comment by monkeyWie** [comment]
参考社区[常见问题](https://community.pdown.org/topic/2/proxyee-down%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94/19)
