### ISSUE TITLE
3.03创建任务失败，undefined

### ISSUE THREAD

**Issue by lxb0852** [proxyee-down-org/proxyee-down#820]
<!--
在提issue之前可以先看看[常见问题列表](https://github.com/monkeyWie/proxyee-down/blob/master/.guide/FAQ.md)
请根据以下模版提issue，不提供必要信息的issue将直接关闭
日志文件在proxyee-down安装目录/main/log文件夹里
### 相关截图
![image](https://user-images.githubusercontent.com/32670290/45988457-a54b9480-c0a9-11e8-99dd-f4f129b0a0fb.png)

![failmission](https://user-images.githubusercontent.com/32670290/45989723-6f111380-c0af-11e8-9fcb-1e78e41b59c9.png)

**Comment by monkeyWie** [comment]
升级到3.12
