### ISSUE TITLE
版本3.03 win10 x64 点击安装按钮后无反应

### ISSUE THREAD

**Issue by sunjian0018** [proxyee-down-org/proxyee-down#822]
### 问题描述(必要)
点击安装按钮后没有任何提示，软件重启后还是如此
### 版本号(必要) 
3.03
### 操作系统(必要) 
win10 x64
### 相关截图
![image](https://user-images.githubusercontent.com/25860889/46010229-79093580-c0f4-11e8-9027-83cb8cc6d3e6.png)
![image](https://user-images.githubusercontent.com/25860889/46010240-83c3ca80-c0f4-11e8-8125-23c471227df3.png)
![image](https://user-images.githubusercontent.com/25860889/46010245-87efe800-c0f4-11e8-9535-8dde13135a05.png)

**Comment by monkeyWie** [comment]
提供下日志，在软件目录/main/log里

**Comment by sunjian0018** [comment]
日志文件为空

**Comment by monkeyWie** [comment]
应该是权限相关问题，尝试手动安装证书 在软件目录/main/ssl里找到ca.crt安装
