### ISSUE TITLE
建议×1、反馈×1

### ISSUE THREAD

**Issue by mlgexyz** [proxyee-down-org/proxyee-down#824]
建议：对于每个页面的框架构建，能否把滚动条设置为滚动页面内容，而非连同顶部菜单一起滚动。

反馈：对线程进行二次使用的过程，仍存在一些问题。现在百度云大文件最后1%的下载速度大概有几百K，但仍无法达到正常下载速度，如果是下载块划分算法的锅那就当我没说。

**Comment by monkeyWie** [comment]
第一点在3.11版本以上已经支持了
