### ISSUE TITLE
有关证书的问题

### ISSUE THREAD

**Issue by yanweian** [proxyee-down-org/proxyee-down#825]
### 问题描述(必要)
我修改了你们的源码，将其中的GUI部分删除了，并在自己的github开了一个项目
[https://github.com/yanweian/proxyee-down-server](https://github.com/yanweian/proxyee-down-server)
将此系统部署到了局域网中的一台服务器上，其他功能都完好，就是百度云插件加载后证书好像有问题？在SwitchyOmega中设置代理后，显示“您的链接不是私密链接”。请问应该如何解决，我搞了好久还是没搞出来。。。
### 版本号(必要)
基于3.03版本的源码进行修改的版本
### 操作系统(必要)
客户端（macos），服务器端（docker容器-centos7）
### 相关截图
![image](https://user-images.githubusercontent.com/22558120/46052704-1f475080-c172-11e8-9591-a8506dbb5d51.png)
### 相关日志
没有错误日志
![image](https://user-images.githubusercontent.com/22558120/46052782-69c8cd00-c172-11e8-85cf-806d4c813e45.png)
可以看端口也是全部启动了

**Comment by bj1507** [comment]
证书得重新生成，浏览器里得重新加载新证书

**Comment by yanweian** [comment]
@bj1507 对https不是很懂，意思是 服务器端要加载新证书，浏览器端也要加载新证书么？证书是哪个文件，因为我把GUI界面删除了，所以不会自动弹出框框让我点，只要我手动操作了

还请指教一下

**Comment by bj1507** [comment]
你浏览器需要证书啊，运行jar包后会在ssl目录生成。你导进浏览器里。


发送自我的三星盖乐世智能手机。
-------- 原始信息 --------发件人： yanweian <notifications@github.com> 日期: 2018/9/26  12:20  (GMT+08:00) 收件人： proxyee-down-org/proxyee-down <proxyee-down@noreply.github.com> 抄送： bj1507 <day2up@gmail.com>, Mention <mention@noreply.github.com> 主题： Re: [proxyee-down-org/proxyee-down] 有关证书的问题 (#825) 
@bj1507 对https不是很懂，意思是 服务器端要加载新证书，浏览器端也要加载新证书么？证书是哪个文件，因为我把GUI界面删除了，所以不会自动弹出框框让我点，只要我手动操作了
还请指教一下

**Comment by yanweian** [comment]
@bj1507 非常感谢！！！证书问题解决了！可是在推送任务的时候又出现新的问题了
![image](https://user-images.githubusercontent.com/22558120/46066112-79620900-c1a6-11e8-9f3a-f7682128eea2.png)
详细的请求头信息如下面：
![image](https://user-images.githubusercontent.com/22558120/46066181-a6162080-c1a6-11e8-8b81-de1ccee468d2.png)
我自己先研究哈。。。

**Comment by yanweian** [comment]
我怎么觉得这个问题有点严重诶

**Comment by monkeyWie** [comment]
@yanweian 推送有什么问题？我看请求好像没什么问题

**Comment by yanweian** [comment]
@monkeyWie 实在不好意思！！！学校最近太忙了。
![image](https://user-images.githubusercontent.com/22558120/46594025-23c12100-cb03-11e8-9815-78b5f9b2d611.png)
上面这张图是我修改的pdown.js（就是把请求地址修改为我局域网内的服务器地址了）
下面是目前的项目结构
![image](https://user-images.githubusercontent.com/22558120/46594427-7996c880-cb05-11e8-9eaf-007593a3194a.png)

![image](https://user-images.githubusercontent.com/22558120/46594336-08efac00-cb05-11e8-8a41-63d9bcf53082.png)

现在就是下面这一步，只要点击，直链下载或者推送下载就出错（压缩已经不行了）
![image](https://user-images.githubusercontent.com/22558120/46594881-31c57080-cb08-11e8-9498-f22562a26197.png)

**Comment by yanweian** [comment]
@monkeyWie 我如果直接访问请求中的url直链地址（就是下图划线部分的地址）
![image](https://user-images.githubusercontent.com/22558120/46595618-dbf2c780-cb0b-11e8-8d47-7c2cd2d57807.png)
就会出现下面的错误（盗链）
![image](https://user-images.githubusercontent.com/22558120/46595575-98985900-cb0b-11e8-8ac9-9bca4b92101e.png)

**Comment by yanweian** [comment]
@monkeyWie 
将地址中的d11改为d7就可以在浏览器中下载了，可是在pdown中创建任务还是回出错

![image](https://user-images.githubusercontent.com/22558120/46595882-ff6a4200-cb0c-11e8-858c-8a95f3ff30f9.png)

**Comment by monkeyWie** [comment]
可以加qq联系下：263397478
