### ISSUE TITLE
执行javascript函数scrollIntoView()后代理失效

### ISSUE THREAD

**Issue by bradleyasdf** [proxyee-down-org/proxyee-down#836]
问题描述：
登陆百度盘后，在页面执行javascript函数scrollIntoView()后，上方的proxyee-down图标消失，代理功能也暂时失效，需要刷新页面才恢复功能。
3.03下则pd菜单消失。
版本号2.54，3.03
操作系统windows 7, chrome 69， windows vista, chrome 50

**Comment by monkeyWie** [comment]
scrollIntoView是什么？
