### ISSUE TITLE
建议支持全局设置User-Agent来改善限速

### ISSUE THREAD

**Issue by BugKun** [proxyee-down-org/proxyee-down#840]
### 问题描述(必要)
建议支持全局设置User-Agent，而不是每个请求都要去使用HEAD来设置，我发现最近此软件的User-Agent似乎被加入黑名单，更换User-Agent前只有2m/s不到的速度，更换后立即满速。
### 版本号(必要)
3.03
### 操作系统(必要)
win10

**Comment by monkeyWie** [comment]
还有这种操作吗。是登录了账号下载的？

**Comment by BugKun** [comment]
我是把文件分享出去后，再用油猴脚本在匿名模式下提取链接，最后新建任务下载的。
我的百度网盘账号早已是黑户了，不敢在登陆的情况下，下载文件了。

**Comment by monkeyWie** [comment]
匿名下载不改UA也不限速的吧

**Comment by BugKun** [comment]
不行的，以前没问题，这个问题还是最近出现的，即使用256线程也没用，还是限制在2m/s一下，而且速度波动很大，最低只有500kb/s。研究了一会发现，修改User-Agent后，速度就恢复正常了。而User-Agent改什么都行，即使是 proxyee is asesome 也没问题。

**Comment by monkeyWie** [comment]
嗯 到时候可以考虑加到百度云扩展里，随机一个UA去下载任务

**Comment by BugKun** [comment]
百度云扩展能否做成油猴脚本？这样通用性会好很多。

**Comment by wangmingrui1989** [comment]
您好 bugkun

> 百度云扩展能否做成油猴脚本？这样通用性会好很多。


> 不行的，以前没问题，这个问题还是最近出现的，即使用256线程也没用，还是限制在2m/s一下，而且速度波动很大，最低只有500kb/s。研究了一会发现，修改User-Agent后，速度就恢复正常了。而User-Agent改什么都行，即使是 proxyee is asesome 也没问题。

你好 bugkun  怎么更改ua 呀， 新手小白 求指点哦 么么哒

**Comment by BugKun** [comment]
> 您好 bugkun
> 
> > 百度云扩展能否做成油猴脚本？这样通用性会好很多。
> 
> > 不行的，以前没问题，这个问题还是最近出现的，即使用256线程也没用，还是限制在2m/s一下，而且速度波动很大，最低只有500kb/s。研究了一会发现，修改User-Agent后，速度就恢复正常了。而User-Agent改什么都行，即使是 proxyee is asesome 也没问题。
> 
> 你好 bugkun 怎么更改ua 呀， 新手小白 求指点哦 么么哒

![example](//wx2.sinaimg.cn/large/0060lm7Tly1fvrtldjxokj30e009xmxg.jpg)

**Comment by wangmingrui1989** [comment]
> > 您好 bugkun
> > > 百度云扩展能否做成油猴脚本？这样通用性会好很多。
> > 
> > 
> > > 不行的，以前没问题，这个问题还是最近出现的，即使用256线程也没用，还是限制在2m/s一下，而且速度波动很大，最低只有500kb/s。研究了一会发现，修改User-Agent后，速度就恢复正常了。而User-Agent改什么都行，即使是 proxyee is asesome 也没问题。
> > 
> > 
> > 你好 bugkun 怎么更改ua 呀， 新手小白 求指点哦 么么哒
> 
> ![example](https://camo.githubusercontent.com/2d4601355533fdb854e331699b6e2704301e00c4/68747470733a2f2f7778322e73696e61696d672e636e2f6c617267652f303036306c6d37546c7931667672746c646a786f6b6a333065303039786d78672e6a7067)

谢谢大大大大神，还有作者辛勤滴付出，给你们个么么哒

**Comment by monkeyWie** [comment]
百度云扩展 0.29版本支持使用自定义ua或随机ua来下载，避免限速的情况
