### ISSUE TITLE
多文件（大于3个）压缩下载时会提示创建任务失败，错误代码：400

### ISSUE THREAD

**Issue by Bagener** [proxyee-down-org/proxyee-down#841]
### 问题描述(必要)
多文件（大于3个）压缩下载时会提示创建任务失败，错误代码：400
### 版本号(必要)
3.03
### 操作系统(必要)
Windows 8.1 pro
### 相关截图
![untitled](https://user-images.githubusercontent.com/35773805/46239437-4a78ac80-c3cb-11e8-8c3a-c094a84f96ad.png)

**Comment by monkeyWie** [comment]
更新百度云扩展，然后使用批量推送下载
