### ISSUE TITLE
[3.1]批量下载时疯狂推送

### ISSUE THREAD

**Issue by Tiandians** [proxyee-down-org/proxyee-down#845]
**问题描述**
批量下载3个视频，第二个开始失败重试，然后列表一下子蹦出47个任务来
**版本号**
3.1
**操作系统**
Windows10 1809 18247.1000
**相关截图**
![1](https://user-images.githubusercontent.com/35755846/46245500-26e05100-c421-11e8-81d0-2cd8a20548aa.png)
**相关日志**
[pdown-error.2018-09-29.log](https://github.com/proxyee-down-org/proxyee-down/files/2430606/pdown-error.2018-09-29.log)

**Comment by monkeyWie** [comment]
3.11已经修复了这个bug
