### ISSUE TITLE
推送任务后会在等待区出现多个正在下载的任务

### ISSUE THREAD

**Issue by RangerDzy** [proxyee-down-org/proxyee-down#846]
### 问题描述(必要)
1.选择了两个文件，点击批量下载，第二个文件一直显示“解析失败，重试中”，而第一个文件除了进行中的一个任务外，在等待列表中出现了23个同名任务；
2.上个版本下载的文件，暂停后重新下载一直显示状态未知，但程序却有下载和上传活动，速度均在400K~500K左右，更新后问题依然存在。
### 相关截图
![image](https://user-images.githubusercontent.com/43333228/46245494-0ca67300-c421-11e8-97c4-aaaf5040a33a.png)（列表显示41个文件，其中18个是其他文件，暂停后恢复下载没有速度）

![image](https://user-images.githubusercontent.com/43333228/46245531-83437080-c421-11e8-85bc-3d603421d907.png)（这是任务列表的任务下载情况和程序占用网速的情况）

**Comment by Tiandians** [comment]
我这里有同样情况

**Comment by monkeyWie** [comment]
3.11已经修复
