### ISSUE TITLE
[3.1]浏览器UI模式层叠错误

### ISSUE THREAD

**Issue by Tiandians** [proxyee-down-org/proxyee-down#847]
**问题描述**
如图，详细信息气泡被框架遮住了
**版本号**
3.1
**操作系统**
Windows 10 19H1 18247.1000
**相关截图**
![2](https://user-images.githubusercontent.com/35755846/46245538-9ce4b800-c421-11e8-8496-b77576e1aa43.png)
**相关日志**
无

**Comment by monkeyWie** [comment]
3.12版本已经修复,具体查看：https://github.com/proxyee-down-org/proxyee-down/releases/tag/3.12
