### ISSUE TITLE
代理端口无法固定。

### ISSUE THREAD

**Issue by mlgexyz** [proxyee-down-org/proxyee-down#854]
每次打开，扩展的代理端口都会发生变化，Firefox上的SwitchOmega不支持pac，无法自动同步新的端口，能否在软件设置或者扩展管理中加入自定义代理端口的选项呢？

**Comment by AnyWAT** [comment]
https://github.com/proxyee-down-org/proxyee-down/issues/751#issuecomment-425709133

**Comment by mlgexyz** [comment]
@AnyWAT 然而火狐用不了pac才是最烦的啊

**Comment by mlgexyz** [comment]
![default](https://user-images.githubusercontent.com/21287731/46271211-172a4f00-c57e-11e8-8a95-0434ad285ed9.png)
