### ISSUE TITLE
下载多数量文件时会导致下载状态变成未知

### ISSUE THREAD

**Issue by jinjuli11** [proxyee-down-org/proxyee-down#859]
### 相关日志
下载了50个分卷大小1G的压缩包，在完成十个左右的任务时下载会进入未知状态（包括待下载的文件也会变成未知），重启或者切换任务也还是未知状态

**Comment by jzmswe** [comment]
和楼主一样，下载美剧剧集1080P.BlrRay，变成未知状态，重启PC都不行。

**Comment by monkeyWie** [comment]
参考：https://github.com/proxyee-down-org/proxyee-down/wiki/%E5%88%B7%E6%96%B0%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5
