### ISSUE TITLE
WIN10 x64更改路径失败

### ISSUE THREAD

**Issue by ybc0320** [proxyee-down-org/proxyee-down#863]
### 问题描述(必要)
WIN10 x64更改路径失败
### 版本号(必要)
3.12
### 操作系统(必要)
WIN10  X64
### 相关截图
![0dqjw b73 6 ucw 1oe0o0](https://user-images.githubusercontent.com/28505451/46329102-f32e4280-c63d-11e8-8620-2a5510862874.png)
![iiajso_lr9yi6q7 19s54](https://user-images.githubusercontent.com/28505451/46329101-f295ac00-c63d-11e8-8e94-24bbe5b485fe.png)
![Uploading {IIAJSO_LR9YI6Q7{@19S54.png…]()
![Uploading 0DQJW`B73~6~UCW{(1OE0O0.png…]()

### 相关日志
[pdown-error.2018-10-02.log](https://github.com/proxyee-down-org/proxyee-down/files/2436468/pdown-error.2018-10-02.log)

**Comment by ctlmlcfq** [comment]
我也是同样情况。

**Comment by a22899666** [comment]
win8.1 x64一样情。。。。

**Comment by monkeyWie** [comment]
Duplicate of #792
