### ISSUE TITLE
下载路径放imdisk 的虚拟内存盘出错

### ISSUE THREAD

**Issue by zh2k2k** [proxyee-down-org/proxyee-down#864]
2.5版本没有这个问题，3.0以后一直有这个问题，3.0是创建文件时调用了java新的函数？imdisk也没有 scsi模式，有解决办法吗？

**Comment by ybc0320** [comment]
请问你2.5那个版本还能用吗，每次我下载都显示 package is too large

**Comment by monkeyWie** [comment]
老版本不能打包下载了，具体看这里https://github.com/proxyee-down-org/proxyee-down-extension/tree/master/baiduYun#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97

**Comment by monkeyWie** [comment]
虚拟内存盘的话没测试过，建议先存硬盘里吧
