### ISSUE TITLE
proxyee-down3.12在XP下不能正常启动

### ISSUE THREAD

**Issue by bestive** [proxyee-down-org/proxyee-down#866]
### 问题描述(必要)
proxyee-down3.12在XP(32位)下不能正常启动
在托盘区已经显示出来,但是浏览器上无反应,也不能正常下载,点击菜单也没有反应.以前2.X是可以的.
环境:有防火墙,已经关闭了360
### 版本号(必要)
3.12
### 操作系统(必要)
XP(32位)

**Comment by bestive** [comment]
pdown-error.XXXX.log 内无任何内容,空白.

托盘菜单除了"退出"有用外,其它一律没有反应.

**Comment by bestive** [comment]
再补充:关闭360,防火墙等,仍然一样无法运行.

**Comment by monkeyWie** [comment]
3.31版本已经兼容xp了
