### ISSUE TITLE
使用PD后，正常情况下百度云速度为0

### ISSUE THREAD

**Issue by istillmc** [proxyee-down-org/proxyee-down#872]
### 问题描述(必要)
使用PD后，正常使用百度云下载速度完全变成0，没有一点速度，是被封号了吗？如果这样，怎么避免？使用PD后会被百度云处理还是说PD修改了一些设置，导致出现了问题？
### 版本号(必要)
3.0.3
### 操作系统(必要)
windows7

**Comment by Tiandians** [comment]
#871 你可以参照这个Issues

**Comment by istillmc** [comment]
> #871 你可以参照这个Issues

感谢。应该是同样一个原因。。。但是手机端还是ok的。百度云好狠，看大神有解决方案不

**Comment by monkeyWie** [comment]
#871 已经有提到解决办法
