### ISSUE TITLE
批量推送下载失败

### ISSUE THREAD

**Issue by ybc0320** [proxyee-down-org/proxyee-down#873]
### 问题描述(必要)
浏览器是chrome，进行批量推送下载时失败
### 版本号(必要)
3.12
### 操作系统(必要)
win10
### 相关截图
![s 8ip 6yk31p n0sb hjqn](https://user-images.githubusercontent.com/28505451/46455054-d62f7600-c7db-11e8-83de-a77e720c036c.png)
### 相关日志
日志显示为空

**Comment by monkeyWie** [comment]
更新软件和扩展到最新版即可
