### ISSUE TITLE
一直“请求中”

### ISSUE THREAD

**Issue by Zero248** [proxyee-down-org/proxyee-down#877]
问题描述(必要)
一直“请求中”

版本号(必要)
3.12

操作系统(必要)
win10 x64

**Comment by monkeyWie** [comment]
是不是自己设置的代理地址啊

**Comment by seeyou363** [comment]
你可能是用了Firefox？

**Comment by Zero248** [comment]
是啊 用的火狐 自己设置的代理

**Comment by seeyou363** [comment]
用edge 或者 chrome 咯，

**Comment by seeyou363** [comment]
> 
> 
> 是不是自己设置的代理地址啊

建议 再readme 建议不要使用firefox，firefox 不采用系统证书，我自己电脑上firefox也是显示请求中（随便吐槽下其他提交issue的格式，真的无语

**Comment by Zero248** [comment]
哈哈哈 好吧 edge也挺好用的
