### ISSUE TITLE
请添加批量删除功能

### ISSUE THREAD

**Issue by NaixHw** [proxyee-down-org/proxyee-down#879]
下了一个软件的文件夹,把整个列表塞满,打钩只能全选,不能用shift 拖一整列.或者删了文件自动删除

**Comment by Tiandians** [comment]
这很不必要。如果要下载包含大量零碎文件的文件夹，可以使用压缩链接下载。

**Comment by NaixHw** [comment]
压缩包是百度打包的吗，试过几次大文件出错，有些修复不了要重下。视频的话还会中间少了一段

Zhu Baolin <notifications@github.com> 于 2018年10月5日周五 04:15写道：

**Comment by Tiandians** [comment]
我也不大清楚打包的原理。百度云打包肯定需要会员权限，所以不是百度云打的。反正我也不经常下软件文件夹，一般来说软件的分享都是分享压缩包的吧？

**Comment by NaixHw** [comment]
也有不一般的。里面有很多素材包，可能压完太大还要分开压，别人分享偷点懒也没什么好说的。

Zhu Baolin <notifications@github.com> 于 2018年10月5日周五 21:19写道：

**Comment by monkeyWie** [comment]
可以批量删除啊，太多的话建议全选直接删掉
