### ISSUE TITLE
快要下载完成时候老是显示状态未知

### ISSUE THREAD

**Issue by yongqingxie** [proxyee-down-org/proxyee-down#880]
### 相关截图
![unnamed qq screenshot20181005221408](https://user-images.githubusercontent.com/24885976/46540563-49c0a880-c8ec-11e8-843f-ffaa5f0c6276.png)

**Comment by 5high** [comment]
网页超时了，重新打开下载地址，再次点击下载，程序会继续下载你的文件，续传的，很方便。

**Comment by yongqingxie** [comment]
> 网页超时了，重新打开下载地址，再次点击下载，程序会继续下载你的文件，续传的，很方便。

如果文件非常多的时候 就很痛苦了 @5high

**Comment by monkeyWie** [comment]
扩展批量推送会自动刷新的，先升级软件和扩展吧
