### ISSUE TITLE
an internal error occurred ( error code 7)

### ISSUE THREAD

**Issue by yyhfut** [proxyee-down-org/proxyee-down#881]
### 问题描述(必要)
当我的系统从win10企业版ltsb2016直升为ltsc2019后（非重新安装），打开proxyee时，遇到报错：
an internal error occurred ( error code 7)。
### 版本号(必要)
Proxyee Down.3.12
### 操作系统(必要)
cn_windows_10_enterprise_ltsc_2019_x64
### 相关截图
![default](https://user-images.githubusercontent.com/43886429/46543041-7ecff980-c8f2-11e8-8594-950a10d8e94f.png)

**Comment by monkeyWie** [comment]
删了重新下载试试看
