### ISSUE TITLE
2018 10 6 MSI GT72VR 我遇见一个很严重的问题 导致了我的电脑不能上网

### ISSUE THREAD

**Issue by Laoxiang-Git** [proxyee-down-org/proxyee-down#884]
### 相关日志

这个问题是我开始用proxyee down的时候产生的，很影响我的使用。但是当我在提示这个消息的时候打开proxyee down的时候，网络就自动恢复正常了。有没有小伙伴和我一样的问题啊？

截图似乎上传不了

**Comment by Tiandians** [comment]
这很奇怪，这个问题应该和Proxyee-Down没有关系。
如果是PD的代理造成了影响，那么应该在你关闭PD时网络恢复正常，而不是开启之后。
那么这可能是你自己或者服务商使用的一些代理软件造成的。
你可以尝试关闭PD的全局代理，或者删掉PD再下一次。
如果无效，你可以尝试百度的[解决方案](https://zhidao.baidu.com/question/588910381131966685.html)

**Comment by monkeyWie** [comment]
可能是非正常退出导致全局代理没有还原回去吧，去IE里把代理设置取消掉就好
