### ISSUE TITLE
经常出现错误 400

### ISSUE THREAD

**Issue by MissMeat** [proxyee-down-org/proxyee-down#886]
### 问题描述(必要)
很多文件都会出现错误400
### 版本号(必要)
3.12
### 操作系统(必要)
win10
### 相关截图
![Uploading CZAA%JSONKV)8X`7%KGZG[G.png…]()

**Comment by tanrich** [comment]
我也存在这个问题，应该是百度网盘检测到了，短暂的封禁了接口？

**Comment by ShmilyLin** [comment]
> 我也存在这个问题，应该是百度网盘检测到了，短暂的封禁了接口？

如果是同一个文件，请先暂停下载之后再次点击网页中的下载即可刷新下载链接。如果未暂停则会出现400的提示

**Comment by monkeyWie** [comment]
升级到3.2，百度云扩展升级到0.26
