### ISSUE TITLE
Ubuntu 18.04百度云插件安装失败

### ISSUE THREAD

**Issue by Hui-Li** [proxyee-down-org/proxyee-down#891]

**Comment by monkeyWie** [comment]
linux上要手动设置代理：https://github.com/proxyee-down-org/proxyee-down/wiki/%E5%AE%89%E8%A3%85%E6%89%A9%E5%B1%95#%E4%BD%BF%E7%94%A8-switchyomega-%E6%8E%A5%E7%AE%A1%E4%BB%A3%E7%90%86
