### ISSUE TITLE
macOS无法嗅探到Chrome浏览器百度云下载请求

### ISSUE THREAD

**Issue by giantke** [proxyee-down-org/proxyee-down#892]
### 问题描述(必要)
macOS无法嗅探到Chrome浏览器百度云下载请求
### 版本号(必要)
3.12
### 操作系统(必要)
macOS
### 相关截图
![a8b308ba60cf02a87609d26f71984ab1](https://user-images.githubusercontent.com/22055709/46593063-f8d2cf00-cafa-11e8-87a9-fbb5e9592cd3.jpg)

**Comment by jsnjycwyz** [comment]
同，描述的清楚点，开全局在Safari里能够正常下载，在chrome里不管是pac还是全局，点击直链下载会一直卡在请求中。。求大佬修复

**Comment by monkeyWie** [comment]
升级软件到3.2，升级百度云扩展到0.27
