### ISSUE TITLE
下载器与系统应用存在网络冲突

### ISSUE THREAD

**Issue by haohaoxueba** [proxyee-down-org/proxyee-down#893]
### 问题描述(必要)
在打开下载器之后,系统的软件无法联网
### 版本号(必要)
3.12
### 操作系统(必要)
win 10
### 相关截图
http://127.0.0.1:7478/pac/pdown.pac?t=1538980405919
![tim 20181008152002](https://user-images.githubusercontent.com/37475997/46596052-a6e77480-cb0d-11e8-821d-16e6e3d49d69.png)
![image](https://user-images.githubusercontent.com/37475997/46596067-b8c91780-cb0d-11e8-8ae6-f7271848cd4b.png)

并且开启软件会自动打开,关闭图一中的开关后,下载 就不生效了
嗅探根本检测不到下载

**Comment by monkeyWie** [comment]
把全网嗅探扩展关掉

**Comment by haohaoxueba** [comment]
收到,感谢开发出这么好的软件!膜拜大神!


我在使用时感觉有一点不是很方便,下载任务暂停后,需要跳到另一个页签,点击继续下载又会跳到正在下载中,这些操作都需要手动点击,很麻烦,期待能改进!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: monkeyWie <notifications@github.com>
发送时间: Friday, October 12, 2018 6:01:26 PM
收件人: proxyee-down-org/proxyee-down
抄送: haohaoxueba; Author
主题: Re: [proxyee-down-org/proxyee-down] 下载器与系统应用存在网络冲突 (#893)


把全网嗅探扩展关掉

―

**Comment by monkeyWie** [comment]
你的意思是说暂停和继续之后自动跳转到相应的便签页吗？

**Comment by haohaoxueba** [comment]
是的大神

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: monkeyWie <notifications@github.com>
发送时间: Friday, October 12, 2018 6:07:50 PM
收件人: proxyee-down-org/proxyee-down
抄送: haohaoxueba; Author
主题: Re: [proxyee-down-org/proxyee-down] 下载器与系统应用存在网络冲突 (#893)


你的意思是说暂停和继续之后自动跳转到相应的便签页吗？

―

**Comment by monkeyWie** [comment]
3.3版本已经加上这个 功能了
