### ISSUE TITLE
pac修改建议

### ISSUE THREAD

**Issue by Cccsky** [proxyee-down-org/proxyee-down#894]
### 问题描述(必要) 
pac接管代理，在程序关闭时会导致百度盘相关网页无法打开，
建议将最后一句由
return match ? 'PROXY 127.0.0.1:9999' : 'DIRECT';
修改为
return match ? 'PROXY 127.0.0.1:9999;DIRECT' : 'DIRECT'; 
本机测试成功。
### 版本号(必要) 
 3.12
### 操作系统(必要)
 MacOS

**Comment by shawneluis** [comment]
想请问下，你编译3.12源码时，新建任务下载界面会同步刷新吗，就是进度条是正常的吗

**Comment by monkeyWie** [comment]
感谢，在下个版本加入试试
