### ISSUE TITLE
UI界面出现严重混乱！！！

### ISSUE THREAD

**Issue by 1357310795** [proxyee-down-org/proxyee-down#904]
### 问题描述(必要)
今天把软件开起来UI界面出现问题。然后又闪退了一下，重启软件后还是一样。然后（我文件下载好了）再退出，稍等片刻，再启动，就正常了。
![qq 20181010123424](https://user-images.githubusercontent.com/35869804/46714053-2733e400-cc8c-11e8-8f30-93354d9cd84f.png)
![qq 20181010123440](https://user-images.githubusercontent.com/35869804/46714055-27cc7a80-cc8c-11e8-9b0b-09f952bb6a8d.png)
![qq 20181010123447](https://user-images.githubusercontent.com/35869804/46714056-27cc7a80-cc8c-11e8-94c0-780ebc9a43e0.png)
![qq 20181010123454](https://user-images.githubusercontent.com/35869804/46714057-28651100-cc8c-11e8-897e-903cfabf8275.png)

### 版本号(必要)
3.12
### 操作系统(必要)
win7 32位
### 相关截图
见上
### 相关日志
[hs_err_pid9776.log](https://github.com/proxyee-down-org/proxyee-down/files/2463181/hs_err_pid9776.log)

**Comment by 1357310795** [comment]
上面的图片是截图，没有经过任何处理！

**Comment by bobcvx** [comment]
> 上面的图片是截图，没有经过任何处理！

是你字库炸了吧...

**Comment by monkeyWie** [comment]
。。这个锅肯定是你系统的
