### ISSUE TITLE
MacOS 有线连接网络不显示PD下载

### ISSUE THREAD

**Issue by wongyeeboo** [proxyee-down-org/proxyee-down#909]
### 版本号
    3.12
### 操作系统
    macOS Mojave

**Comment by monkeyWie** [comment]
可以试试[使用-switchyomega-接管代理](https://github.com/proxyee-down-org/proxyee-down/wiki/%E5%AE%89%E8%A3%85%E6%89%A9%E5%B1%95#%E4%BD%BF%E7%94%A8-switchyomega-%E6%8E%A5%E7%AE%A1%E4%BB%A3%E7%90%86)

**Comment by ArielCharlotte** [comment]
> 可以试试[使用-switchyomega-接管代理](https://github.com/proxyee-down-org/proxyee-down/wiki/%E5%AE%89%E8%A3%85%E6%89%A9%E5%B1%95#%E4%BD%BF%E7%94%A8-switchyomega-%E6%8E%A5%E7%AE%A1%E4%BB%A3%E7%90%86)

接管代理的端口配置多少呢？
