### ISSUE TITLE
3.2版本下着下着就下不动  重启任务也下不了

### ISSUE THREAD

**Issue by evilsong** [proxyee-down-org/proxyee-down#913]

**Comment by yjj008818** [comment]
win10 X64位系统，碰到同样问题，4.18G的文件，而且暂停后重启无速度，下载速度还会在0.00~正常速度之间跳动。

**Comment by monkeyWie** [comment]
刷新链接试试看

**Comment by sweetasaki** [comment]
> 刷新链接试试看

怎么刷新链接，我现在用3.20也总是遇到同样的问题。

**Comment by player2017** [comment]
+1，win10 64位，暂停重启、刷新链接都不行。。。这版很不稳定，没以前2.x版本稳定

**Comment by player2017** [comment]
> > 刷新链接试试看
> 
> 怎么刷新链接，我现在用3.20也总是遇到同样的问题。

刷新链接就是重新下载，它会提示你有相同任务

**Comment by kefei123** [comment]
我的也是如此，下了一大半就突然变成0，然后不管怎么刷新也没用了，始终就是0

**Comment by monkeyWie** [comment]
Duplicate of #978
