### ISSUE TITLE
3.2版 0下载速度， 请教下怎么配置啊？8月份用2.54挺好的， 现在也不能用了!

### ISSUE THREAD

**Issue by honkerSK** [proxyee-down-org/proxyee-down#919]
### 相关截图 
![c chmo5cxt42x rf7wo0v7a](https://user-images.githubusercontent.com/9138683/46916367-313b4700-cfec-11e8-82cf-0ade46fc9ed3.png)
![w7s _ o vkjx2 sezxh](https://user-images.githubusercontent.com/9138683/46916377-4912cb00-cfec-11e8-9278-38457ae1dc89.png)

**Comment by LeoMei** [comment]
同问

**Comment by MurasakiSeiFu** [comment]
同问

**Comment by lost-an** [comment]
同3.2版本 win10系统，连接进行中一直都是0速度，之前3.0版本用过还是好的。

**Comment by ahlixinjie** [comment]
mac系统也是

**Comment by zxcwillwin** [comment]
我的压缩链会卡23.05%


> 但我换压缩链接下载就可以了。无语的是，300Mb以上只能用直链
我的压缩链会卡23.05%

**Comment by monkeyWie** [comment]
Duplicate of #978
