### ISSUE TITLE
百度云盘页面不能批量推送下载，分享页面可以

### ISSUE THREAD

**Issue by me10zyl** [proxyee-down-org/proxyee-down#921]
### 百度云盘页面不能批量推送下载，分享页面可以
自己的百度云盘页面一点批量推送下载，这个Tab就卡死了（感觉是死循环一样），分享页面可以正常推送
### 版本号
3.12
### 操作系统
MacOS X 10.13.3
### 相关截图
![image](https://user-images.githubusercontent.com/7314597/46934710-58952100-d08b-11e8-9c7a-efbd29494615.png)
### 相关日志
无

**Comment by monkeyWie** [comment]
升级到3.2，百度云扩展也升级
