### ISSUE TITLE
en-US.js 重复定义

### ISSUE THREAD

**Issue by bcc290786** [proxyee-down-org/proxyee-down#922]
### 问题描述(必要)
en-US.js 重复定义
### 版本号(必要)
v3.2
### 操作系统(必要)
Windows 10 x64 1803
### 相关截图
![us](https://user-images.githubusercontent.com/6201233/46936659-9dbc5180-d091-11e8-8648-36c624c4549c.jpg)

**Comment by bcc290786** [comment]
辛苦了 不怎么重要的错误~

**Comment by monkeyWie** [comment]
谢谢提醒~
