### ISSUE TITLE
无法下载百度云盘内容

### ISSUE THREAD

**Issue by zlyylihuanyu** [proxyee-down-org/proxyee-down#924]
### 相关截图：
![snipaste_2018-10-15_22-17-45](https://user-images.githubusercontent.com/6366472/46956749-a2e8c300-d0c8-11e8-8bb8-feacb2b59980.jpg)

**Comment by lvhailong** [comment]
同样问题，貌似百度云又更新了验证机制

**Comment by monkeyWie** [comment]
问题已经修复，把百度云扩展升级到0.27即可，相关链接：https://community.pdown.org/topic/107
