### ISSUE TITLE
百度云任务刷新问题

### ISSUE THREAD

**Issue by cMc-Enhancer** [proxyee-down-org/proxyee-down#926]
### 操作系统：windows10 1803
1、当前正在下载中的任务速度为0，状态处于未知时，重新在百度云页面下载同一资源，触发刷新操作。当确认刷新后任务不会自动开始下载，仍处于未知状态。手动暂停->继续后开始恢复下载。
（是否可以自动开始下载？）
2、当触发过刷新操作后的下载任务完成（任务进度显示100.00%，下载文件可以成功解压）后，任务状态变为未知，如下图所示
![image](https://user-images.githubusercontent.com/26867387/47011978-c453b880-d175-11e8-93be-63a910bc5e5d.png)
下载目录中生成的.dat及.dat.bak文件不会自动删除

**Comment by Ryoui** [comment]
我是下载100%，但未完成。重新下载提示任务已存在，不会触发刷新操作。解压，也提示文件损坏。

**Comment by monkeyWie** [comment]
3.3版本已经修复此bug
