### ISSUE TITLE
下载不了，一直在请求中

### ISSUE THREAD

**Issue by wendy770** [proxyee-down-org/proxyee-down#933]
问题描述(必要)
点击单个下载一直在请求中”，点击推送下一直显示请勿，btw，请问大家下载都是在账号内下载还是在分享文件之后下载呢？我的不能在我的网盘账号里下载，要是在账号内点下载会显示“错误码-6”，必须要在分享之后才能下载

版本号(必要)
3.2

操作系统(必要)
macos high sierra 10.13.6

**Comment by doghua** [comment]
遇到了同样的情况

**Comment by JustDoItGoGo** [comment]
+1

**Comment by monkeyWie** [comment]
升级百度云扩展

**Comment by wendy770** [comment]
> 升级百度云扩展
谢谢，已解决问题
