### ISSUE TITLE
关于官网下载带宽低的解决办法

### ISSUE THREAD

**Issue by szkzn** [proxyee-down-org/proxyee-down#936]
官网下载
目前官网带宽非常低所以下载很慢，推荐用OneDriver下载。(如果有服务器或者 CDN 赞助的话可以联系我~)

目前可以考虑把文件放到蓝奏云上面，蓝奏云不限速，不限空间，缺点是限制单个文件大小100MB

**Comment by szkzn** [comment]
蓝奏云本身也是一个分享网盘，无任何广告，目测下载域名跳转跟百度网盘有些PY交易，还有下载网赚，目前不知道他的盈利方式，不限速。已经做了很久了，这个蓝奏云，稳定如斯。

**Comment by monkeyWie** [comment]
暂时先放在onedriver上面了，谢谢提供意见
