### ISSUE TITLE
proxyee-down3.2 重下载等待下载队列问题？

### ISSUE THREAD

**Issue by peterdocter** [proxyee-down-org/proxyee-down#937]
### 相关日志
proxyee-down3.2
当百盘某目录文件下载失败之后，整个目录重下载时发现只有此文件没有下载过才正常。。。
而且当队列最前的文件是已经存在，就不会跳过或清除让整个下载死掉或无限等待。。。
为了补下载某目录文件，只有把整个已经下载目录删除重下载才正常。。。

**Comment by monkeyWie** [comment]
Invalid question.
