### ISSUE TITLE
Mac 3.2批量推送解析错误

### ISSUE THREAD

**Issue by wth461694678** [proxyee-down-org/proxyee-down#938]
### 问题描述(必要)
批量推送下载每个解析都会出现错误，然后不断重试，解析速度极慢
### 版本号(必要)
 3.2
### 操作系统(必要)
Mac
### 相关截图
![image](https://user-images.githubusercontent.com/39629728/47199354-be431f00-d3a3-11e8-8dd3-6ff119badc83.png)

### 相关日志

**Comment by monkeyWie** [comment]
更新扩展就好
