### ISSUE TITLE
【下载相关问题】

### ISSUE THREAD

**Issue by configdx** [proxyee-down-org/proxyee-down#939]
**###问题描述(必要)**
1)下载文件到100%，有时会卡住。

2)已暂停文件，继续下载，有时无法跳转到“进行中”列表继续下载。

**### 版本号(必要)**
proxyee-down_3.2

**### 操作系统(必要)**
windows 8.1 X64 Pro

**### 相关截图**
动态行为，无法展示

**### 相关日志**
[pdown-error.2018-10-19.zip](https://github.com/proxyee-down-org/proxyee-down/files/2494767/pdown-error.2018-10-19.zip)

**Comment by monkeyWie** [comment]
3.3版本已经修复
