### ISSUE TITLE
点击“下载”后proxyee down工具没有反映。

### ISSUE THREAD

**Issue by z6555123** [proxyee-down-org/proxyee-down#940]
问题:下载安装后，从百度网盘选中要下载的文件，然后点“下载”后，浏览器跳出一个新页面，新页面上面显示：{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","request_id":6766405154943112184}   
并且proxyee down里面没有看到任何要下载的东西。希望大神给予帮助，谢谢.
版本：2.54
系统：mac
<img width="2048" alt="2018-10-19 5 22 19" src="https://user-images.githubusercontent.com/44289472/47211416-f4929580-d3c7-11e8-96f7-4198de6b698c.png">

**Comment by lyf1134** [comment]
用户未经授权
是你没有登陆吗

**Comment by z6555123** [comment]
要登录什么啊？

**Comment by lyf1134** [comment]
百度账号

**Comment by z6555123** [comment]
已经登录过百度账号了，然后进入百度网盘，选择我要下载的文件，然后点“下载”后，就跳出来这个页面。
<img width="1567" alt="2018-10-19 5 42 48" src="https://user-images.githubusercontent.com/44289472/47210797-7e416380-d3c6-11e8-95d6-7cc832bde668.png">

**Comment by lyf1134** [comment]
。。。不知道
我获取连接用的是脚本

**Comment by z6555123** [comment]
请问还有其他方式吗？

**Comment by lyf1134** [comment]
什么其他方式

**Comment by z6555123** [comment]
出现这种问题，还有没有别的解决方法

**Comment by lyf1134** [comment]
我没出现过这种状况
我怀疑是百度云扩展崩了
你可以用我用的脚本试试

**Comment by monkeyWie** [comment]
社区里有说这个问题：https://community.pdown.org/topic/128
