### ISSUE TITLE
下载一直没速度或到23.05%突然没速度

### ISSUE THREAD

**Issue by zxcwillwin** [proxyee-down-org/proxyee-down#944]
### 问题描述(必要)
直链下载速度为0或到23%左右突然降速至0并超过10分钟无反应
压缩链某些正常某些下载到23.05%突然降速至0并超过10分钟无反应
### 版本号(必要)
3.2
### 操作系统(必要)
Windows 10 x64 家庭版
### 相关截图
![image](https://user-images.githubusercontent.com/44295949/47222964-a642be00-d3ea-11e8-9ba0-c07a7e64a506.png)

下面3个是压缩链

**Comment by zxcwillwin** [comment]
会不会是Java环境的问题

**Comment by zxcwillwin** [comment]
![image](https://user-images.githubusercontent.com/44295949/47223889-dee39700-d3ec-11e8-9b44-8e812ee8b3ac.png)

**Comment by AnyWAT** [comment]
jre1.8.0_191

**Comment by Leo-dawn** [comment]
遇到同样的问题，完全没速度。

**Comment by coolguy001tv** [comment]
+1 同样的问题中

**Comment by zxcwillwin** [comment]
> 从自己网盘直接下没速度的可以试试，把要下载的文件公开分享，然后从分享链接下载，我试过几个，这样都有速度了

试了还是不行

**Comment by SeAL80s** [comment]
Arch linux ,chrome+Switchy,PAC是在proxyee里copy的.java -jar proxyee.jar .浏览器里下载文件有PD.CA证书是在chrome设置里导入的,也没看提示.地址栏有红色标记不安全.PD直接下载或者批量推送都能接收到,就是没速度.PD全局代理关了,只探测百度云.

**Comment by monkeyWie** [comment]
尝试刷新下载链接：https://github.com/proxyee-down-org/proxyee-down/wiki/%E5%88%B7%E6%96%B0%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5
