### ISSUE TITLE
在网盘下载提示error code 400

### ISSUE THREAD

**Issue by SpaceEggs** [proxyee-down-org/proxyee-down#952]
### 问题描述(必要)

在“我的网盘”页面下下载报 error code 400 错误，但是创建分享链接后下载是正常的。

测试了一下其他资源也是一样，在自己的网盘网页端下东西都报这个错误。只能创建分享链接后才能下载。

![](https://ws1.sinaimg.cn/large/626c316fly1fwflvbd4bsj207z02rgli.jpg)

### 版本号(必要)

v3.2

### 操作系统(必要)

win10 1803

### 相关截图

![](https://ws1.sinaimg.cn/large/626c316fly1fwflvbd4bsj207z02rgli.jpg)

### 相关日志

创建了error log 但是log是空的。
![](https://ws1.sinaimg.cn/large/626c316fly1fwfm2hgul0j20gw02zdg9.jpg)

**Comment by kentcc88** [comment]
我也出现400错误，无法下载情况，或者直接处在“请求中...”画面一直打转！

**Comment by SpaceEggs** [comment]
> 我也出现400错误，无法下载情况，或者直接处在“请求中...”画面一直打转！

找到解决方法了，在程序中更新百度云拓展即可。这里一直没提示，就没注意到。
