### ISSUE TITLE
下载时间过长时，会没网速，下载速度变为0，状态未知

### ISSUE THREAD

**Issue by YangPei1993** [proxyee-down-org/proxyee-down#960]
### 问题描述(必要)
下载时间过长，会没网速，下载速度变为0，状态未知
### 版本号(必要)
3.2
### 操作系统(必要)
OsX10.14

**Comment by zslkeer** [comment]
刷新下链接就行了

**Comment by szkzn** [comment]
补充问题，刷新任务后，能继续下载到99%-100%，然后一直状态未知，等待下载完成，明显100%了，一直没完成，转移到已完成队列，最后没办法重新下载了
