### ISSUE TITLE
批量推送产生的重复任务及其衍生错误

### ISSUE THREAD

**Issue by Stractor** [proxyee-down-org/proxyee-down#962]
### 问题描述(必要)
1、批量推送可以添加重复任务，而不是将其刷新；
2、批量推送添加的重复任务不可重复启动，否则会出现程序错误的提示；
3、批量推送添加的重复任务，删除（未下载的重复任务）时选择同时删除任务和文件，会将已下载的文件删掉。
### 版本号(必要)
3.2
### 操作系统(必要)
win10专业版

**Comment by monkeyWie** [comment]
3.3版本已经修复此bug
