### ISSUE TITLE
已安装扩展列表及PD下载按钮重复

### ISSUE THREAD

**Issue by Ox727xO** [proxyee-down-org/proxyee-down#964]
### 问题描述(必要)
经过简单的试验
在扩展中心或扩展列表中将某个扩展关闭再开启，然后重启程序
已安装扩展列表中会多一个对应的扩展
如果多的是百度云下载的话，百度云的界面上PD下载按钮会重复显示
每个扩展最多存在两个
但好像不影响正常使用
### 版本号(必要)
3.2
### 操作系统(必要)
win10 
### 相关截图
![Image1](https://github.com/Ox727xO/pictures/raw/master/批注.png)
![Image2](https://github.com/Ox727xO/pictures/raw/master/批注2.png)

**Comment by monkeyWie** [comment]
删除重复扩展即可

**Comment by monkeyWie** [comment]
3.3版本已经修复重复扩展bug
