### ISSUE TITLE
centos7环境下程序窗口空白

### ISSUE THREAD

**Issue by Gaara3** [proxyee-down-org/proxyee-down#965]
### 版本号(必要)
使用的是最新刚clone下来的版本进行编译,系统为centos7，java版本oracal jdk 1.8.0_191

执行java -jar后会弹出proxyee down窗口，不过是空白的。顶部任务栏图标处为黑块
### 相关日志
![issue_attach](https://user-images.githubusercontent.com/7713343/47409163-84ec2400-d794-11e8-8b3f-e65b36bd4c3d.png)

**Comment by 14SHIKE** [comment]
试试浏览器模式
在浏览器地址栏输入http://127.0.0.1:7478

**Comment by huanmsf** [comment]
空白的情况我也遇到，修改loadUri()
![Screenshot from 2019-04-20 18-14-08](https://user-images.githubusercontent.com/26873621/56455967-996c3c00-6333-11e9-959d-6ddaeb70aa38.png)
还有，把端口指定一样的。虽然我不清楚是不是有两个服务，但是运行后我的只有一个服务
```
front:
  port: 8080
api:
  port: 8080
```
最后我的是这样的，不知道正确的启动也没是不是这样的：
![Screenshot from 2019-04-20 18-18-58](https://user-images.githubusercontent.com/26873621/56456022-48a91300-6334-11e9-9ca4-ba0aac15eabe.png)
