### ISSUE TITLE
下载速度为0

### ISSUE THREAD

**Issue by waterlogithub** [proxyee-down-org/proxyee-down#971]
今天发现解析任务全部400（3.2版本，百度云下载0.25），卸载百度云下载后安装0.27版本，可解析任务，但所有任务速度都是0。
版本号(必要)3.2
操作系统(必要)win7
相关截图
![1](https://user-images.githubusercontent.com/22746557/47434822-f3050b00-d7d5-11e8-832d-7eabf4a8f474.PNG)
![2](https://user-images.githubusercontent.com/22746557/47434838-f8faec00-d7d5-11e8-8757-9440c7e4c918.PNG)

**Comment by fennykk** [comment]
昨天还可以，今天不行了，不知道是不是我账号被封了？

**Comment by LCJ822059927** [comment]
百度好像升级了，几个工具都不行了

**Comment by Eisx11o** [comment]
今天不行了，下载速度 0

**Comment by cookpu** [comment]
+1 我的也突然变成0了 我还以为只有我出问题了 5555

**Comment by garydevil** [comment]
+2 我的也突然变成0了 我还以为只有我出问题了 5555

**Comment by hihila** [comment]
我的也突然变成0了 :(

**Comment by mianzhiwx** [comment]
我要去多点几遍广告，希望程序员大哥治死baidu

**Comment by thornfieldhe** [comment]
确实是，Baidu网盘又升级了

**Comment by WeddingCandy** [comment]
> 确实是，Baidu网盘又升级了

人家云盘的人也是看这个软件哒

**Comment by monkeyWie** [comment]
已修复，具体看看社区：https://community.pdown.org/topic/128
