### ISSUE TITLE
添加链接的时候提示“响应状态码异常”，是不是得更新了

### ISSUE THREAD

**Issue by lgq1205** [proxyee-down-org/proxyee-down#972]

**Comment by YanHuiLi** [comment]
同问。

**Comment by YanHuiLi** [comment]
我最后解决了，我发现是我的百度云插件没有升级。

**Comment by plus-zhang** [comment]
> 我最后解决了，我发现是我的百度云插件没有升级。

怎么做的？ 不是很清楚。升级的什么插件啊老弟？

**Comment by plus-zhang** [comment]
扩展中心更新插件就行了。。。

**Comment by lgq1205** [comment]
> 我最后解决了，我发现是我的百度云插件没有升级。

百度云插件    是  指 proxyee-down 里面的插件吗？

**Comment by lgq1205** [comment]
> 扩展中心更新插件就行了。。。

好像还是不行。。。一样的提示，添加不了下载

**Comment by monkeyWie** [comment]
装好扩展看扩展主页的使用教程，不是通过提取直链下载
