### ISSUE TITLE
下载速度0，进度0%，状态未知

### ISSUE THREAD

**Issue by zhyit** [proxyee-down-org/proxyee-down#978]
### 问题描述(必要)
界面显示0%进度，下载速度0，状态未知，使用了分享后，无痕后在分享页面下载，重新下载也是一样

### 版本号(必要)
3.2
### 操作系统(必要)
win 10

**Comment by wfzlh** [comment]
我也是，现在下载没用了。

**Comment by Littlefisher619** [comment]
同样的情况。

**Comment by whoami6689** [comment]
我的也是。。。。

**Comment by UserLeeZJ** [comment]
同样的情况,状态未知 #958 
![i e9b4m4c8 a21uqiyj0](https://user-images.githubusercontent.com/32706013/47559532-5adb6300-d948-11e8-989d-99b365169ad2.png)

- #

**Comment by wuhaiwang** [comment]
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","error_info":"","request_id":6933317257470899084}

**Comment by Mee-orz** [comment]
3.2版本，扩展0.28。从添加以后速度就为0。

**Comment by qinkaiabc** [comment]
我也是，下载没速度了

**Comment by vonsj0210** [comment]
我的也是，我还以为就我自己这样呢

**Comment by amostang** [comment]
一樣

**Comment by zenochan** [comment]
+1

**Comment by liningchuan** [comment]
我之前也是，升级3.2之后就不好用了。重新下载客户端就好了

**Comment by NAMEs** [comment]
+1

**Comment by hxx094438** [comment]
mac 版本3.2  复现问题

**Comment by Antecer** [comment]
+1

**Comment by monkeyWie** [comment]
已修复：https://community.pdown.org/topic/128
