### ISSUE TITLE
3.2不知道怎么关掉启动打开界面

### ISSUE THREAD

**Issue by withero** [proxyee-down-org/proxyee-down#981]
3.2版，在Win7开始菜单→启动中添加Proxyee Down快捷方式，以实现开机自动运行，但Proxyee Down启动会打开窗口，比较麻烦，之前有这个选项，现在没有了，不知道怎么关掉启动打开界面

**Comment by monkeyWie** [comment]
3.3版本已经支持设置启动弹窗选项
