### ISSUE TITLE
百度云里确定任务后，软件经常没有反应

### ISSUE THREAD

**Issue by lessthanobsessiveness** [proxyee-down-org/proxyee-down#984]
### 问题描述(必要)
百度云里确定任务后，软件经常没有反应
### 版本号(必要)
2.45
### 操作系统(必要)
win10

**Comment by lessthanobsessiveness** [comment]
解决了，我忘了开代理的设置脚本。但是2.45的问题没有解决

**Comment by 14SHIKE** [comment]
请仔细查看教程，版本不需要代理插件
https://github.com/proxyee-down-org/proxyee-down/wiki/安装扩展
![2018-11-04_225332](https://user-images.githubusercontent.com/37872513/47965662-a3032f80-e084-11e8-8791-388fd6d43744.png)
