### ISSUE TITLE
任务创建失败，错误码400

### ISSUE THREAD

**Issue by zj1123581321** [proxyee-down-org/proxyee-down#992]
### 问题描述(必要)
任务创建失败，错误码400
### 版本号(必要)
3.2
### 操作系统(必要)
win10 1803
### 相关截图
![snipaste_2018-10-29_19-29-11](https://user-images.githubusercontent.com/33171229/47647234-54035900-dbb1-11e8-8b6d-fb623a156244.png)

### 相关日志

显示是空文件
![image](https://user-images.githubusercontent.com/33171229/47647296-83b26100-dbb1-11e8-95f5-d5c827dd15e5.png)

**Comment by cuevven** [comment]
same issue

**Comment by rch0903** [comment]
macOS Mojave(10.14) client(3.2)  same issue

**Comment by Steve-Leo** [comment]
windows 7 same issue

**Comment by Mrtj2016** [comment]
我也有这个问题，但是将百度云下载的插件更新后就好了

**Comment by cuevven** [comment]
thx @Mrtj2016 
i try upgrade the baiduyun plugin, can now created task, but the task cannot begin download.

**Comment by MonsterYoker** [comment]
> 我也有这个问题，但是将百度云下载的插件更新后就好了
请问具体怎么操作的，可以详述一下吗？另外这个工具需要百度云插件吗，请问插件名称是什么？

**Comment by cnlzxin** [comment]
错误码 400 见 #977 
下载进度为 0 见 #971

**Comment by monkeyWie** [comment]
升级软件和扩展就好
