### ISSUE TITLE
进度不会自动更新

### ISSUE THREAD

**Issue by xiaomai515** [proxyee-down-org/proxyee-down#994]
### 相关截图 
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/41110178/47659029-f4468700-db8b-11e8-8c93-c5c02e5cd4f0.png">

**Comment by xiaomai515** [comment]
另外，为了支持你继续努力，给你donate了10元。

**Comment by monkeyWie** [comment]
更新新版本吧，已经发布3.3了
