### ISSUE TITLE
创建任务下载提示“响应状态码异常”

### ISSUE THREAD

**Issue by SUChilia** [proxyee-down-org/proxyee-down#997]

**Comment by Shenjieping** [comment]
已经成功安装，点击下载出现 package is too large
版本：2.5.4
系统： MAC OS 10.12.6
![image](https://user-images.githubusercontent.com/25164911/47764585-cafb3780-dd00-11e8-86f5-68bd40b235ce.png)

**Comment by monkeyWie** [comment]
更新版本，使用扩展下载
