### ISSUE TITLE
关于【文件完整性】的疑问；

### ISSUE THREAD

**Issue by softshild** [proxyee-down-org/proxyee-down#998]
1、文件下载过程中，移动文件，会不会导致文件受损？-- 我试过下载过程中可以移动文件（当前磁盘内移动），不提示也不报错。  如果换作成磁盘间移动呢？

2、强制退出下载工具、电脑突然断电会不会导致文件受损？

3、文件下载完成后，有没有做文件的校验？或是说文件分片校验？ md5 hash 

版本：3.2

帮忙回答一下，非常感谢。

**Comment by monkeyWie** [comment]
1. 下载过程中移动会损坏文件
2. 强退和断电不会损坏文件
3. 没有文件校验，因为无法得知真实的hash
