### ISSUE TITLE
文件大小的判断有误

### ISSUE THREAD

**Issue by lyf1134** [proxyee-down-org/proxyee-down#999]
### 相关截图       
![1](https://user-images.githubusercontent.com/42033610/47730543-5b079580-dc9d-11e8-84e7-faddcb300576.JPG)
![2](https://user-images.githubusercontent.com/42033610/47730545-5d69ef80-dc9d-11e8-99cb-5def9a3479af.JPG)

**Comment by monkeyWie** [comment]
是文件大小显示有误，3.3版本已经修复
